### ISSUE TITLE
[QUESTION] nested filter query possible?

### ISSUE THREAD

**Issue by Seibold** [sensedeep/dynamodb-onetable#101]
Is it possible to create a query with a filter on a nested field?

Something like the following query:

![image](https://user-images.githubusercontent.com/3463962/129872104-a096dbf5-e41f-4015-a6e3-012a9ba015b1.png)

**Comment by mobsense** [comment]
Yes, see https://github.com/sensedeep/dynamodb-onetable/blob/main/test/nested.ts for examples.

```
    user = await User.update({id: user.id}, {set: {
        'location.zip': '{"98011"}',
        'tokens[1]': '{white}',
        status: '{active}',
        balance: 0,
    }})

```
