### ISSUE TITLE
[BUG]: Use table delimiter in createUnique

### ISSUE THREAD

**Issue by sdemjanenko** [sensedeep/dynamodb-onetable#105]
I noticed that `createUnique` constructs a `pk` and `sk` with colons instead of the configured table delimiter. Fixing this would be a breaking change.

**Comment by mobsense** [comment]
The hard-coded ":" is a bug and as you say, fixing will be a breaking change.

Looking at the format of the unique:

    _Unique:MODEL:ATTRIBUTE:VALUE

it is possible, but extremely unlikely that someone could encode data values with ":" when they are using "#" as a delimiter and this could clash.

However, we and others are developing tooling to view and manage OneTable designs and having a separator mis-match may break such tooling. So we need to fix it.

So, I think we need to push a SemVer major release number change (1.8) and flag this prominently. We could also provide a Table params legacyUnique that would preserve the ":" unique separator for those that want to upgrade but not migrate their data.

Lastly, we could provide a Gist snippet for a OneTable Migrate pattern to upgrade unique fields.

**Comment by mobsense** [comment]
Just committed test code for updateUnique. Let me know if this works for your use case.  update.ts has been updated with a few additional tests.

**Comment by mobsense** [comment]
Some notes:

* Update with unique fields. Can check if an update for the unique item for a unique field is required. If the value does not change. Then an update is not required.
* If the schema changes and a field becomes unique in the schema, then the remove of the old unique value will fail. Internally set exists: null to ignore such errors.

## Compatibility Notes

The implementation up to 1.7.x has hard coded colon (:) separators in the unique items created when you define an item as unique in the schema. It should use the defined table delimiter which defaults to (#).  The unique items also do not have a "unique" prefix. While the values will probably not clash with other items as they are of the form:

    Entity:ATTRIBUTE:VALUE

It is possible they could clash. 

To address this while preserving compatibility with existing code and data, we're adding a Table param "legacyUnique".

The legacyUnique table param can be set to a separator to use in unique items. This can be set to colon (:) or hash (#) or anything you like. If unset in version 1.7.x, it will default to (:). 

Starting with version 1.8, the default will be reversed and it will default to your defined table delimiter (probably #). Additionally, a "unique" prefix will be added to the unique items. So they will use the form:

    unique:Entity${SEP}ATTRIBUTE${SEP}VALUE

If you have existing databases with unique items, you may want to set legacyUnique explicitly to ":".  This will ensure that your existing unique items are observed. Preferably, you migrate your data to use the new form with version 1.8. You can do this by simply doing an update on all items with unique attributes which will then create the new unique items.

In version 1.8, the default for legacyUnique will be to use the table delimiter. In version 2.0, legacyUnique will be removed.

Recommendations .. What should I do:

* If you don't have unique items in existing data, set legacyUnique to false in your table params until 1.8 is released.
* If you do have unique items but are in development and can easily recreate your data, set legacyUnique to false and recreate your dev data.
* If you have production data using unique items, set legacyUnique to true. Then before 2.0 is released (and preferably as soon as possible), run a migration where you do an update on all items with unique attributes with legacyUnique set to false. This will update to use the new unique item format.

Please email me if you have any questions or concerns: mob AT sensedeep.com.
