### ISSUE TITLE
[BUG]: .find returns wrong type

### ISSUE THREAD

**Issue by spearmootz** [sensedeep/dynamodb-onetable#115]
model.Find returns the following type

const model: Paged<Entity<{Schema}>[]>

but Paged already extends an array so it should be 

const model: Paged<Entity<{Schema}>>

**Comment by mobsense** [comment]
Thanks. Looks good.

**Comment by mobsense** [comment]
Thank you for the pull request. Merged and targeted for 1.7.6

**Comment by spearmootz** [comment]
this was actually released in 1.7.5 and looks good on my end
