### ISSUE TITLE
[BUG]: AWS SDK V2 dependency

### ISSUE THREAD

**Issue by chowlett** [sensedeep/dynamodb-onetable#127]
**Describe the bug**
dynamodb-onetable unnecessarily publishes aws-sdk v2

**To Reproduce**
Inspect node_modules after importing.

**Expected behavior**
aws-sdk should not be published. It is used only for running tests.

**Additional context**
aws-sdk is a little chubby (65M uncompressed) so worth optimizing out of the package.

I suggest moving aws-sdk from "dependencies" to "devDependencies". Or, find a way to initialize test credentials with aws-sdk V3. The latter may not be straightforward. I tried that myself many months ago in a similar context, and came up empty. But that's just me :-)

**Comment by mobsense** [comment]
The question is: how do we provide dependencies for either V2 or V3 SDK. Some people are using the V2 SDK and not V3?

Should we make both a peer dependency?

**Comment by mobsense** [comment]
When V3 first came out, it didn't have DocumentClient. So we created a helper "Dynamo.js" which provides the setup. Unfortunately, this imports the SDK v3 to get access to the various V3 marshall, unmarshall and *Commands which we need to call.

I would love to get an easy way for users to call OneTable and pass in a V3 client and OneTable be able to call the V3 APIs without importing them.

**Comment by mobsense** [comment]
After more thought .... we don't directly call V2 APIs and the caller is expected to pass in a configured V2 DocumentClient. So we probably can remove the V2 dependency. That still leaves the problem of having a fixed V3 dependency in package.json for users of V2.

**Comment by chowlett** [comment]
Removing the V2 dependency is a nice improvement. The fixed V3 is an imperfection but even less serious than the fixed v2 because of the v3 modularization. It's just not as chubby. 18M compared to 65M, from my memory.

**Comment by mobsense** [comment]
Okay, have removed V2 dep in 1.8.2 released now

**Comment by ebisbe** [comment]
> Should we make both a peer dependency?

In think so. From what I've read that is for what it's used ( https://indepth.dev/posts/1187/npm-peer-dependencies ).  In my case I'm using this package in lambdas and it's adding extra size to each one for no reason other than being declared in dependency.

**Comment by mobsense** [comment]
Question. If I install both V2 and V3 as peer dependencies and I deploy without using tree shaking, won't both get included? i.e. do peer dependencies get bundled by SAM/Serverless etc?

**Comment by ebisbe** [comment]
> Question. If I install both V2 and V3 as peer dependencies and I deploy without using tree shaking, won't both get included? i.e. do peer dependencies get bundled by SAM/Serverless etc?
Without tree shaking everything on dependecies is included. My guess is peer dependecies is treate as a dependecy if it is intalled ( my guess ).

**Comment by mobsense** [comment]
But you said when you package your Lambdas you are getting added extra size. But converting to peer dependencies wont reduce this as the code will still get bundled?

Frameworks like serverless will specifically exclude bundlingling the AWS SDKs.

**Comment by ebisbe** [comment]
I'm having the issue ( extra size ) with the V3 dependecies ( not peerdependecies) of the sdk. The v2 sdk is not bundled as you said by serverless. 

As v3 are 'dependencies' are automatically installed so they are bundled but I think that if we move them to peerDependecies and I don't install them they will not be bundled. 
I should make a sample repo and try it out, as I'm not 100% sure
