### ISSUE TITLE
[BUG]: Updating an item that contains a unique flagged field always does a get op when not needed

### ISSUE THREAD

**Issue by garretcharp** [sensedeep/dynamodb-onetable#129]
**Describe the bug**

Whenever you have a model that contains a unique field every update query will always do a get request on the item even if the unique field is not sent in the update request. This causes unnecessary get requests to the database.

**To Reproduce**

Run the following code (ensure a local dynamo is running on port 8000)

```
const aws = require('aws-sdk')
const { Table } = require('dynamodb-onetable')

const client = new aws.DynamoDB.DocumentClient({
  endpoint: 'http://localhost:8000',
  region: 'local'
})

const table = new Table({
  client,
  name: 'MyTable',
  schema: {
    indexes: {
      primary: {
        hash: 'pk',
        sort: 'sk'
      }
    },
    models: {
      Account: {
        pk: { type: String, value: 'account:${name}' },
        sk: { type: String, value: 'account:' },

        name: { type: String },
        email: { type: String, unique: true },

        description: { type: String }
      }
    }
  },
  logger: true
})

const account = table.getModel('Account')

const run = async () => {
  try {
    await table.createTable()
  } catch (error) {}

  await account.update({ name: 'test', description: 'something' })
}

run()
```

**Expected behavior**

Running the code above you should expect an error from dynamo saying the item does not exist (the condition check that pk/sk exists should be the error) as you never made it, but instead, you get an error from onetable saying it cannot find the item to update. When I am not updating the `email` attribute in this case it should really only do the update request and not as a transaction.

**Comment by mobsense** [comment]
Thanks. I'll see if we can optimize that case when the unique field is not being updated.

**Comment by mobsense** [comment]
I think we can go even further and not use a transaction if not updating a unique property. i.e. just a normal update.

Thanks for suggesting. A solid optimization.

**Comment by mobsense** [comment]
Have committed a fix, but plenty more test to do. Please test if this looks okay for you too.

**Comment by garretcharp** [comment]
It looks good to me yes

**Comment by mobsense** [comment]
Thanks, will roll that out in the next few days with some other fixes and enhancements.
