### ISSUE TITLE
[BUG]: Creating transactions with a model that contains unique properties

### ISSUE THREAD

**Issue by garretcharp** [sensedeep/dynamodb-onetable#134]
**Describe the bug**

Whenever you try and create a transaction on a model that contains unique properties the transaction gets executed before expected. (Another small thing to add to this: When creating an item that has unique properties and timestamps enabled the timestamps getd saved as an empty object rather than the expected date)

**To Reproduce**

The following code: https://gist.github.com/garretcharp/5c3215a3e5c914c484922ccf4fbd12de

**Expected behavior**

I would expect that the transaction does not get executed until I call `table.transact('write', transaction)` however the transaction gets executed as soon as I call create on the model that includes unique attributes. (Note that setting { execute: false } in the params does not change this, though I (personally) would expect it not to execute if I pass it in a transaction object regardless of the execute param)

**Comment by mobsense** [comment]
Thanks for reporting. That is a bug.

**Comment by mobsense** [comment]
Easy fix really. Thanks. Will roll out in a few days. Or do you need a quick patch now?

**Comment by garretcharp** [comment]
Whenever the next update is will work.
