### ISSUE TITLE
batchWrite fails

### ISSUE THREAD

**Issue by juranki** [sensedeep/dynamodb-onetable#14]
I have a batch write with one deleteItem and two create operations.

It fails, but if I change condition on [this line](https://github.com/sensedeep/dynamodb-onetable/blob/79f4443c539662151d7dc6e8c351c2ae8da6389f/src/Expression.js#L404) in [Expression.js](https://github.com/sensedeep/dynamodb-onetable/blob/79f4443c539662151d7dc6e8c351c2ae8da6389f/src/Expression.js), it starts to work.

```diff
            } else if (op == 'delete') {
                args = { Key: key }
-            } else if (op == 'update') {
+            } else if (op == 'put') {
                args = { Item: values }
            }
```

**Comment by juranki** [comment]
Here's how the batch is constructed:
https://gitlab.com/juhani/prudent-profile/-/blob/547651742bfd40589c141912a79f6ec3a8e14493/src/lib/db.ts#L109-154

**Comment by mobsense** [comment]
That is right. Thank you.

We'll apply that.

**Comment by juranki** [comment]
Thank you!
:)
