### ISSUE TITLE
[BUG]: Support nested properties in value templates

### ISSUE THREAD

**Issue by junaway** [sensedeep/dynamodb-onetable#140]
**Describe the bug**
Cannot created nested keys.

**To Reproduce**

    const Schema = {
      ...
      Entity: {
          pk:      { type: String, value: '${data.id}' },
          ...
          data:    { type: Object, schema: {
              id:  { type: String }
              ...
          }
          ...
      }
      ...
    };

**Expected behavior**
Using nested properties in value templates should work (?)

[Reference to the forum discussions](https://github.com/sensedeep/dynamodb-onetable/discussions/139)

**Comment by doktor500** [comment]
Thanks for the quick update,

that seems to work with version `1.9.1` and unblocks me to do what I need, however I noticed that I can't reference an `id` attribute in the `pk` if it exists within an object block.

This works

```javascript
const schema = {
  pk: { type: String, value: "entity:${id}" },
  sk: { type: String, value: "entity:${entity.attribute1}-${entity.attribute2}" },
  id: { type: String, uuid: "uuid", validate: /^[0-9A-F]{32}$/i },
  entity: {
    type: Object,
    schema: {
      attribute1: { type: String, required: true },
      attribute2: { type: String, required: true }
    }
  }
};
```


but this doesn't

```javascript
const schema = {
  pk: { type: String, value: "entity:${entity.id}" },
  sk: { type: String, value: "entity:${entity.attribute1}-${entity.attribute2}" },
  entity: {
    type: Object,
    schema: {
      id: { type: String, uuid: "uuid", validate: /^[0-9A-F]{32}$/i },
      attribute1: { type: String, required: true },
      attribute2: { type: String, required: true }
    }
  }
};
```

It would be great to be able to do so
