### ISSUE TITLE
TS1036: Statements are not allowed in ambient contexts

### ISSUE THREAD

**Issue by ganeshan102** [sensedeep/dynamodb-onetable#144]
When we are building the module along with dynamo-onetable facing the below issue.

node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:56:2 - error TS1036: Statements are not allowed in ambient contexts.
56 };

**Comment by mobsense** [comment]
Can I get a bit more info.  Are you building the current main branch of OneTable or are you just trying to use OneTable pre-built?  What version? What is your TSC version?

Can you try adding a semicolon at that location?

**Comment by ganeshan102** [comment]
We are using the following versions,

dynamodb-onetable: 1.8.2
node : 4.3.5

Yeah.. When we removing the semicolon it started working in local. But it should fail in our build tool.. 

Will you guys remove the same and commit it ?

**Comment by mobsense** [comment]
Already done.

Will be fixed in the next version 1.9.0 which is just about ready.
