### ISSUE TITLE
TypeScript Errors

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#15]
This project looks really interesting. However, I am getting several TypeScript compile errors:

```
node_modules/dynamodb-onetable/dist/cjs/Model.d.ts:44:11 - error TS2304: Cannot find name 'OneType'.

44     type: OneType,
             ~~~~~~~

node_modules/dynamodb-onetable/dist/cjs/Model.d.ts:188:2 - error TS1036: Statements are not allowed in ambient contexts.

188 };
     ~

node_modules/dynamodb-onetable/dist/cjs/Table.d.ts:21:25 - error TS2314: Generic type 'Model<T>' requires 1 type argument(s).

21     intercept?: (model: Model, op: string, rec: {}, params: OneParams, raw?: {}) => void,
                           ~~~~~

node_modules/dynamodb-onetable/dist/cjs/Table.d.ts:57:2 - error TS1036: Statements are not allowed in ambient contexts.

57 };
    ~

Found 4 errors.
```

Any ideas? Thanks

**Comment by mobsense** [comment]
Can you rename OneTypes to OneType in that file and see if that works?

**Comment by bytekast** [comment]
changed it. cleaned up a few files. one last error:

```
node_modules/dynamodb-onetable/dist/cjs/Table.d.ts:21:25 - error TS2314: Generic type 'Model<T>' requires 1 type argument(s).

21     intercept?: (model: Model, op: string, rec: {}, params: OneParams, raw?: {}) => void,
                           ~~~~~
```

it looks like the type definitions need to be cleaned up

**Comment by bytekast** [comment]
changed to `intercept?: (model: Model<any>, op: string, rec: {}, params: OneParams, raw?: {}) => void,` and it compiled

**Comment by mobsense** [comment]
Cool. Probably should be AnyModel.

**Comment by bytekast** [comment]
yep. `AnyModel` worked.  FYI I also had to remove the trailing `;` in the following files `Model.d.ts`, `Table.d.ts`

**Comment by mobsense** [comment]
Great. I don't understand removing the trailing semicolon?  Can you explain a bit more? Thanks.

**Comment by mobsense** [comment]
It seems that `type` declarations can use either semicolon or comma as a line terminator. However, the class declarations (Model<T>) require a semicolon.

We have some types line OneTableSchema that use commas:

```
type OneIndexSchema = {
    hash: string,
    sort?: string,
    description?: string,
    follow?: boolean,
}
```

and others that use semicolo:

```
export type Entity<T extends OneTypedModel> = {
    [P in keyof T]?: EntityField<T[P]>;
};
```

I'd like to be consistent. What are the best practices / rules. Comma, semicolon or nothing?

**Comment by mobsense** [comment]
Background:

https://stackoverflow.com/questions/27994253/why-is-the-separator-in-a-typescript-typememberlist-semicolon-as-opposed-to-comm/27994757#27994757

**Comment by bytekast** [comment]
these are the errors:

```

node_modules/dynamodb-onetable/dist/cjs/Model.d.ts:188:2 - error TS1036: Statements are not allowed in ambient contexts.

188 };
     ~
node_modules/dynamodb-onetable/dist/cjs/Table.d.ts:57:2 - error TS1036: Statements are not allowed in ambient contexts.

57 };
```

have no idea why. if i remove the semicolon at the end of the files, it works.

**Comment by mobsense** [comment]
What version of TSC are you using?

I don't see that with 4.0.3

**Comment by mobsense** [comment]
And that is complaining only about the very last semicolon in the file but not the ones before that?

**Comment by bytekast** [comment]
I am at `Version 4.1.5`. yeah, it doesn't complain about the ones before. just the last one.

**Comment by mobsense** [comment]
This is our tsconfig we use when testing:

```
{
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "baseUrl": "src",
        "declaration": true,
        "esModuleInterop": true,
        "inlineSourceMap": false,
        "lib": ["esnext"],
        "listEmittedFiles": false,
        "listFiles": false,
        "moduleResolution": "node",
        "noFallthroughCasesInSwitch": true,
        "pretty": true,
        "resolveJsonModule": true,
        "rootDir": "src",
        "skipLibCheck": true,
        "strict": true,
        "traceResolution": false
    },
    "compileOnSave": false,
    "exclude": ["node_modules", "dist"],
    "include": ["src"]
}
```

Can you please share yours and we'll test.

I'm happy with the fix, but I'd like to understand why.

**Comment by bytekast** [comment]
```
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["es2020", "dom"],
    "target": "es2020",
    "removeComments": true,
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "commonjs",
    "isolatedModules": true,
    "outDir": "./dist",
    "rootDir": "./src",
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules/**/*", ".serverless/**/*", ".webpack/**/*", "_warmup/**/*", ".vscode/**/*"]
}
```

**Comment by mobsense** [comment]
skipLibCheck in our tsconfig was the culprit.

Sorry, we'll apply the fix.  Good to understand why we were not seeing this.

**Comment by bytekast** [comment]
nice! thanks for validating!

**Comment by mobsense** [comment]
That has uncovered a few other issues ... :-(

**Comment by mobsense** [comment]
Thank you for assisting. Appreciated.
