### ISSUE TITLE
unable to use value functions as they are deprecated

### ISSUE THREAD

**Issue by hemanth1226** [sensedeep/dynamodb-onetable#162]
Hi, We are using value function to conditionally remove gsi indexes as below.

```javascript
      gsi3pk: {
        type: String,
        value: (name: string, message: Message): string => message.flagged ? `${message.type}#user#${message.userId}#flagged` : undefined,
      },
      gsi3sk: {
        type: String,
        value: (name: string, message: Message): string => message.flagged ? `message#${message.id}` : undefined,
      },
```
When message is un-flagged, we are removing gsi3pk and gsi3sk
But when we updated the onetable to latest version, we are getting error that value functions are deprecated. 

Can you please help us understand how we can resolve this without using `remove` in update operation? 

Thank you!

**Comment by Muthuveerappanv** [comment]
> @mobsense Having the value function at the table level works fine. But still see warning logs, can you remove warnings when value functions are used at create-table level? (During batch updates, our logs are flooded with warnings)

**Comment by mobsense** [comment]
Can you post the warning text you are seeing and your schema?

You should only be seeing warnings if the schema field value is a function.

**Comment by Muthuveerappanv** [comment]
> Can you post the warning text you are seeing and your schema? You should only be seeing warnings if the schema field value is a function. You need to set the schema field value to `true`
> […](#)
> On Feb 10, 2022, at 5:44 AM, Muthu ***@***.***> wrote: @mobsense <https://github.com/mobsense> Having the value function at the table level works fine. But still see warning logs, can you remove warnings when value functions are used at create-table level? (During batch updates, our logs are flooded with warnings)

ignore my comment, i deleted it - still you might have got notified via email i believe. It works fine, please ignore 👍🏻
