### ISSUE TITLE
FilterExpression IN Query doesn't retrive any values (Typescript)

### ISSUE THREAD

**Issue by ganeshan102** [sensedeep/dynamodb-onetable#164]
**Describe the bug**
When we are sending multiple values in IN parameter, result won't come. But for a single IN value, result will come.

```
const types = await type.find(
        { PK: 'VT' },
        {
            where: '${typeId} IN (@{ids})',
            substitutions: {
                ids: '1,2'
            }
        }
    );
```

**Comment by mobsense** [comment]
Fixed in 2.0.3

**Comment by ganeshan102** [comment]
Still it's not working ..

Add @{...list} substitutions to support lists with filterExpressions and IN

DynamoDB Client Created
1,2
[]

DynamoDB Client Created
1
[
  {
    PK: 'VT',
    SK: 'VT#Required',
    validationTypeId: '1',
    created: 2021-10-18T10:49:44.941Z,
    updated: 2021-10-18T10:49:44.941Z
  }
]

**Comment by mobsense** [comment]
Can you please open a new issue and follow the issue template. 

Our test cases work and we were not able to convert your code snippets to a reproducible test case.

**Comment by ganeshan102** [comment]
Can you plz share your test cases and sample code

**Comment by ganeshan102** [comment]
I got the solution.. Thank you guys for your support..
