### ISSUE TITLE
Table transform not in typedefs

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/dynamodb-onetable#167]
**Describe the bug**
Table.intercept was renamed to transform but the typedefs haven't been updated

**To Reproduce**
Create a table with a transform
```
const table = new Table({
  client: client,
  name: TABLE_NAME,
  schema,
  transform: (model, operation, item, apiParams, rawReadData) => {
    return item
  },
})
```
This will give you type errors because transform isn't part of TableConstructorParams

**Expected behavior**
Type defs for transform exist and are accurate

**Comment by mobsense** [comment]
Issue fixed in 2.0.3
