### ISSUE TITLE
transform params are not consistent for read and write

### ISSUE THREAD

**Issue by rjmackay** [sensedeep/dynamodb-onetable#168]
**Describe the bug**
The table transform receives a different parameter order depends if its read or write

**To Reproduce**
On read, the 4th argument is params and 5th is raw data 
```
rec = this.table.params.transform(this, op, rec, params, raw)
```
https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.js#L858

On write, the 4th argument is raw properties and 5th is params
```
rec = this.table.params.transform(this, op, rec, properties, params)
```
https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.js#L901

**Expected behavior**
Params should be sent in a consistent order

**Comment by mobsense** [comment]
Fixed in 2.0.3

**Comment by rjmackay** [comment]
@mobsense one more issue with the transform function: The docs say the `op` param will be read or write, but for the Table transform it's sending the raw op ie get/delete/find/put/scan/update

**Comment by mobsense** [comment]
I think there are a couple of other issues and we've still not got it quite right.

The read transform must have access to the raw read data in addition to the API params and properties. 
The write transform has no such need.

So the signature needs to be:

```
item = transform(model, operation, item, properties, params, raw)
```

Operation is 'read' or 'write'
Item is the pre-transformed item using the internal transformers.
Properties and params are the supplied API properties and params.
Raw is null for write ops and for read, it is the untransformed data.

The item returned must be the fully transformed item.

**Comment by mobsense** [comment]
We've taken a step back to see how we can better solve this issue for transforms, value templates and validations.

See discussion: #173 

I'd love to get your thoughts.
