### ISSUE TITLE
Add ability to pass ExclusiveStartKey / return LastEvaluatedKey when querying

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#17]

**Comment by mobsense** [comment]
Without checking, I think you can use params.start and result.start. These are mapped to ExclusiveStartKey / LastEvaluatedKey I think. 

Look at the Pagination example in the readme.

**Comment by bytekast** [comment]
I think it's unclear if the result object is an array of records or is it an object with a `start` and `next` properties. I'm confused.

for example: in `let adminUsers = await User.find({accountId: account.id, role: 'admin'})`

what is `adminUsers`?

**Comment by mobsense** [comment]
Find always returns an array. In Javascript, you can also set properties of an array.

So adminUsers is an Array AND adminUsers.start should be set to the next key.

**Comment by bytekast** [comment]
Ah ok. will try that. thanks!

**Comment by mobsense** [comment]
I'll update the doc to clarify. Thanks.

**Comment by mobsense** [comment]
Doc updated to say:

The `find` method will automatically invoke DynamoDB query to fetch additional items and aggregate the result up to the limit specified by `params.limit`. If the limit is exceeded, the last key fetched is set in the 'result.start' property **of the returned array of items**. You can provide this as `params.start` to a subsequent API call to continue the query with the next page of results.

**Comment by mobsense** [comment]
Let me convert this to a discussion for others to benefit.
