### ISSUE TITLE
[Typescript] Looks like 2.0.3 samples are assuming 2.0.4 definitons?

### ISSUE THREAD

**Issue by fsmikedev** [sensedeep/dynamodb-onetable#176]
Hi, I've just started looking at dynamodb-onetable, it looks great so far. 

I've noticed that 'schema' is used even though it's not in 2.0.3? are you able to publish 2.0.4? if not, how do I decribe an object schema? like in this example.

`    address:    { type: Object, default: {}, schema: {
                street: { type: String },
                city:   { type: String },
                zip:    { type: String },
            } },`
            
Thanks.

**Comment by mobsense** [comment]
That should have been supported in 2.0.3.  It may just be missing from the doc. I'll check it out.

We are going to publish 2.0.4 as 2.1.0 this weekend.

**Comment by mobsense** [comment]
Released.
