### ISSUE TITLE
Is lack of DocumentClient in aws-sdk v3 a breaking change?

### ISSUE THREAD

**Issue by jpet710122** [sensedeep/dynamodb-onetable#2]
There is much discussion around the decision by the AWS development team to leave DocumentClient capability out of v3 of the Javascript AWS-SDK. See [#1223](https://github.com/aws/aws-sdk-js-v3/issues/1223), and the response at [#2031](https://github.com/aws/aws-sdk-js-v3/pull/2031).

Does this mean your excellent library will only work with V2? Will there be any plans to support v3?

**Comment by mobsense** [comment]
Currently works with V2 and current requires DocumentClient. We're monitoring the discussion re V3 & DocumentClient. We definitely want to support V3 but would rather not have to write a shim that emulates DocumentClient ourselves. But we will do that if required. My hope is that the community pressure will force some kind of DocumentClient upgrade path for V3 by AWS.

Since V3 is brand new, it will take a little while for the dust to settle.

**Comment by jpet710122** [comment]
Thanks. I'll just stick with v2 for the time being, then!

**Comment by trivikr** [comment]
Update: The AWS SDK for JavaScript has prioritized development of DocumentClient for DynamoDB in v3, and an experimental PR can be viewed at https://github.com/aws/aws-sdk-js-v3/pull/2031

**Comment by mobsense** [comment]
In parallel with the AWS DocumentClient PR, we're prototyping V3 support here. 

Progressing well and will post updates here. 

Our plan is to support both V2 and V3 in the one code base.  The V3 support will provide a helper class which will import the required DynamoDB V3 classes and transparently integrate the marshall / unmarshall into and out of Javascript objects.

**Comment by mobsense** [comment]
Okay, got the basic AWS SDK V3 support working. Really not too bad. The marshall / unmarshall support does most of the heavy lifting. 

@trivikr I still believe that V3 DocumentClient is probably worthwhile for the general developer so they can more easily upgrade to V3. However, for OneTable, there are performance benefits in going directly to the V3 APIs. So we'll offer both options.

V3 support looks like this:

```
import {Dynamo, Model, Table} from 'dynamodb-onetable'
const table = new Table({
    dynamo: new Dynamo(params),
    name: 'MyTable',
    schema: MySchema,
})
```

With this configuration, all OneTable APIs work the same as for AWS V2.

Reminder, to use AWS V2:

```
import DynamoDB from 'aws-sdk/clients/dynamodb'
import {Dynamo, Model, Table} from 'dynamodb-onetable'
const table = new Table({
    client:  new DynamoDB.DocumentClient(params),
    name: 'MyTable',
    schema: MySchema,
})
```

In the V3 support, the OneTable Dynamo class is a helper which constructs the V3 DynamoDBClient (don't confuse with DocumentClient) instance for the given `params`. The Dynamo helper class imports 11  DynamoDBClient commands and wraps these for use by OneTable. The marshall and unmarshall routines are also imported from @aws-sdk/util-dynamodb and passed into OneTable to use transparently.

I know having a helper class import 11 methods defeats ultimate tree shaking, but the benefit in a terse interface I believe outweighs shaking a few more bytes that are probably going to be used in any real app anyway.

If you want to construct the DynamoDBClient instance yourself with V3, pass in as new Dynamo({client}).

```
import DynamoDBClient from '@aws-sdk/client-dynamodb'
import {Dynamo, Model, Table} from 'dynamodb-onetable'

const client = new DynamoDBClient(params)
const table = new Table({
    dynamo: new Dynamo({client}),
    name: 'MyTable',
    schema: MySchema,
})
```

**Comment by mobsense** [comment]
We've cleaned up the API a little by requiring the user to always pass in a DocumentClient or V3 DynamoDBClient instance.

```javascript
import {Table} from 'dynamodb-onetable'

// V2
import DynamoDB from 'aws-sdk/clients/dynamodb'
const client = new DynamoDB.DocumentClient({...})

// V3
import {DynamoDBClient} from '@aws-sdk/client-dynamodb'
import Dynamo from 'dynamodb-onetable/Dynamo'
const client = new Dynamo({client: new DynamoDBClient({...})})

// V2 or V3
const table = new Table({
    client: client,
    name: 'MyTable',
    schema: MySchema,
})
```

**Comment by mobsense** [comment]
Supported added in 0.7.0 released.
