### ISSUE TITLE
Use an existing table?

### ISSUE THREAD

**Issue by RyanHow** [sensedeep/dynamodb-onetable#202]
This is more of a question than an issue...

Is there a way to use an existing table?

I wanted to keep the basic DynamoDB table managed directly by cloudformation (using CDK) and use OneTable for all the interactions with the table, handling GSIs, etc.

Is there a way to use `createTable()`, but pass in an existing minimal table?

The other way I can go about it is to use a custom resource and execute OneTable for the table creation and removal, then import the table for other resources to reference it. Would that be a better way of doing it?

Thanks!

**Comment by mobsense** [comment]
Sure, all you need is a schema and call the Table constructor. In fact, this is the normal mode of operation.

You don't (and shouldn't) call createTable for an existing table. createTable is really for dev and test time testing.
