### ISSUE TITLE
[BUG] OneTable - Build is failing from morning

### ISSUE THREAD

**Issue by ganeshan102** [sensedeep/dynamodb-onetable#208]
**ISSUES will not receive priority that do not follow this template or cannot be easily reproduced or diagnosed**

**Describe the bug**
From morning when we are building the one table application, build is getting failed.

node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:122:54 - error TS2536: Type 'P' cannot be used to index type 'B'.

122 [P in keyof (A & B)]: P extends keyof A ? A[P] : B[P]
~~~~

Found 1 error.

**To Reproduce**

Steps to reproduce the behavior:

1. map the latest version in package.json
2. Do $ npm run build


Check that:

**Screenshots**
![image](https://user-images.githubusercontent.com/31682699/143426424-84eb8bee-e838-4637-b138-85e1f7532bbe.png)

**Environment (please complete the following information):**
 - OS - Linux
 - Node Version - 16.9.1
 - OneTable Version - 2.1.3
 - TypeScript Version - 4.5.2
 - Any other relevant environment information

**Additional context**
Add any other context about the problem here.

**Comment by mobsense** [comment]
That is not enough to reproduce. Need your package.json and tsconfig.json or other files.

Please provide a reproducible test case that we can replicate. Builds work here for us, we need you to provide the details for us to reproduce. Otherwise, we can't help you.

**Comment by ganeshan102** [comment]
[my-files.zip](https://github.com/sensedeep/dynamodb-onetable/files/7602405/my-files.zip)

**Comment by ganeshan102** [comment]
Attached my package.json & tsconfig.json files here.. There is no test case required here.. Just run the build.. it's enough.

**Comment by mobsense** [comment]
Actually it is not enough. Just run the build does nothing as there is nothing to compile. TSC won't do anything without something to compile. You didn't provide a test program (debug.ts) to compile, so TSC does nothing.

We've spent a couple of hours and managed to recreate your scenario -- but this will be the last time. The issues you open, while real, are consistently missing essential pieces (package.json, tsconfig.json, debug.ts etc.) and we go back and forth gathering the essential information that should be provided in the first place according to the issue template.  This is frustrating and counterproductive.

We'll post the fix tomorrow.

**Comment by ganeshan102** [comment]
What debug.ts file needs to share here? We've not changed any configuration recently.. The project who build successfully is not getting build today.. For running a build command, what is the need of debug.js ??

**Comment by ganeshan102** [comment]
![image](https://user-images.githubusercontent.com/31682699/143445009-edc7362d-24dd-4b21-b82c-fc90d4dcc339.png)

**Comment by ganeshan102** [comment]
![image](https://user-images.githubusercontent.com/31682699/143445180-e66342f7-89e0-4fd1-910e-6325bc9bab9b.png)

**Comment by mobsense** [comment]
Fix is committed.

**Comment by ganeshan102** [comment]
Thanks but this is not the right way to treat us.. _This is frustrating and counterproductive._

**Comment by mobsense** [comment]
If you can verify the committed change works for you, we will push the NPM module. Thanks.

**Comment by mobsense** [comment]
The change is:

```
diff --git a/src/Model.d.ts b/src/Model.d.ts
index 2852341..022adf3 100644
--- a/src/Model.d.ts
+++ b/src/Model.d.ts
@@ -118,12 +118,15 @@ export type Optional<T extends OneTypedModel> = {
 /*
     Merge two types
 */
-type Merge<A, B> = {
-    [P in keyof (A & B)]: P extends keyof A ? A[P] : B[P]
+type Merge<A extends any, B extends any> = {
+    [P in keyof (A & B)]: P extends keyof A ? A[P] : (P extends keyof B ? B[P] : never)
 };
```
