### ISSUE TITLE
Unable to project fields using batchGet

### ISSUE THREAD

**Issue by mobsense** [sensedeep/dynamodb-onetable#213]
### Discussed in https://github.com/sensedeep/dynamodb-onetable/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **kunalfleethawks** November 26, 2021</sup>
Hello Team,

We are performing following batchGet operation. For each batch query we are specifying projection fields but when batchGet executes it returns all fields specified in schema. Following is the sample code. 

As per [AWS Documentation ](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html)we can specify projectionFields or fields (incase of this library) for each batch.

```
let batch = {}
await Account.get({id: accountId}, {batch, fields: 'name'})
await User.get({id: userId}, {batch,  fields: 'firstName' })
let results = await table.batchGet(batch)
```

Can you let us know how to achieve expected behaviour?

Thanks

</div>

**Comment by mobsense** [comment]
This is a bug (limitation - never coded).

I've committed a patch which fixes this. 

Please note:

* You must specify the fields on the batchGet and not on the Account/User get. DynamoDB does not permit the ProjectionExpressions on a per request item basis.

Please test it out and let us know if it works.

**Comment by kunalfleethawks** [comment]
Thank you for the quick fix. We well let you know once we test it.
