### ISSUE TITLE
table.queryItems does not support pagination

### ISSUE THREAD

**Issue by sdemjanenko** [sensedeep/dynamodb-onetable#216]
This method returns an array of items, but it doesn't return `next` or `prev` which is useful for paginating the query.

**Comment by mobsense** [comment]
It should return next/prev.  Model.find defers to this function and it returns next/prev.

Can you follow the template and post a test case in debug.ts.

**Comment by sdemjanenko** [comment]
Hey, I discovered that `console.log` doesn't print the `.next` and the `.prev` properties that are on the returned array. Sorry for the trouble.

**Comment by mobsense** [comment]
That is right, they are defined to be non-enumerable so they don't get in the way if you enumerate over the returned object.
