### ISSUE TITLE
TypeScript improvements

### ISSUE THREAD

**Issue by markandrus** [sensedeep/dynamodb-onetable#220]
Hello 👋 I'm currently evaluating libraries for my application's interface to DynamoDB, and I think OneTable looks great! It's basically what we're doing manually today, but y'all have some additional features (like migration support).

I'm curious if you'd be open to improving the TypeScript definitions, or even migrating some of the code entirely to TypeScript. I think we could provide stronger typings for many of the APIs. For example, here is one way we could type the `begins`, `between`, etc., without resorting to `tunnel` (see also in [TypeScript Playground](https://www.typescriptlang.org/play?#code/PTAEHkDsFMBUEMBGAbaoDGBXATt6kAXZAT1ABNoAzASxgGdQCALNSge2WTYHdaBzRsQAO0OoDICALAAoAsLRRoABXjZ4AWwYBeUAG9poUCFCSpAX2nTZI0AFFC1WctVroBaNjoAeOwQfEAfKDaTr7wyN72sv4WUtAAHkJs2AQYyPB0DMp80GSesIHxbpBkDACCuPDEeYF6UgbobJiEAPwAXKCQmGqI7gDc+h2FbaBsiABW0OgE-XWgQngAbsOjE1Mz5lLSRgAS7mjUDGwwoNQU8KDs2HPYbCLYJIJC-KAABj18tHQvADSvPQTcaD4H6gVzoAB0v1ojBYrxoxReoFKigAkuDLHJbJFiE51K53HQAGJJQm0XL5IK6AYAbQA0idIKAANbQYhsSigWAAXXasDpXIGBgAPqAAELQD6QLywX606KzYViiWfADqDiYeVl8oMivFAKBkE1oDlgtAIoAMqI6LAmPBDTLjdqdRarTa7eBsDYAI6YMJGk0Ks22H1+h0BnVBgBybAI3t94TDTsVAHE8PA3Ng3ZAPXHQ1rTSLU9B0+4s-75RsMdZxZLpbLQXEiiVmaz2ZzAtodKB3p9efzQBsrGga6r1f6G02GCy2RyKZ3u8qpQB9XjMPu0rkDqvD1yA-Djwr4ZvTttz3QL-X4drUvkb363rmbweYy0ZMthidHqet2cd88Ack8f91yfbdQFfa1bWzT0QwTetD2Kb8Z3bSku0AzRgM5ftn2sXM4ONT9EJbZCzzQjCQK3GRMWjWNYIPRsv2I08-zQzx-Ewh9KKHUAixLTMoJzOiPwQ48fxQ+d-38cisI3LjMV4jN33ghiiJPX9UNASSOOwmIjDVZgYVEaBfkBDo2FALhIGyK4YByV4CCaGBkBeExaAzSh4HQNAAFk2AoBMagGeEyFAAAKeZbncXxRGGHw-FxFwMyJEkyWqX4hBUdQ6GGBQEroABKdpFBuNQDmgTwshyaoK10sBiSueJ1CEVAoTUeBJTQZgDgwNgXAYSgSteOLZE8Ic2284gAGV0BYNrwTUPzoGQOhwWJNh-Bc6Q3PcDyvNANbYExWoDHYNh2joAhsH4AZEBUdpOm6dxpErKQjBtfBQFM9A7XIczmFYDguF4KyTAaKUUlO3z-PaKGls8A65D-TpOFAdJUcgYgYkhxbkHBYLQuOi42DOzTTv-b4bru89-j3SBrwARl+emAAZmdAsx8qAA)):

```ts
// OneTable currently defines the following types…
type OneParams = {
  // …
}

type EntityParameters<Entity> = Partial<Entity>

export class Paged<T> extends Array<T> {
  count?: number;
  next?: object;
  prev?: object;
}

// Here is one idea for properly typing `begins`, `between`, etc., in the `find` API.
type EntityParametersForFind<T> = {
  [K in keyof T]: T[K]
    | Begins<T, K>
    | BeginsWith<T, K>
    | Between<T, K>
    | LessThan<T, K>
    | LessThanOrEqual<T, K>
    | Equal<T, K>
    | NotEqual<T, K>
    | GreaterThanOrEqual<T, K>
    | GreaterThan<T, K>
}

type Begins<T, K extends keyof T> = { begins: T[K] }
type BeginsWith<T, K extends keyof T> = { begins_with: T[K] }
type Between<T, K extends keyof T> = { between: [T[K], T[K]] }
type LessThan<T, K extends keyof T> = { '<': T[K] }
type LessThanOrEqual<T, K extends keyof T> = { '<=': T[K] }
type Equal<T, K extends keyof T> = { '=': T[K] }
type NotEqual<T, K extends keyof T> = { '<>': T[K] }
type GreaterThanOrEqual<T, K extends keyof T> = { '>=': T[K] }
type GreaterThan<T, K extends keyof T> = { '>': T[K] }

// With these, we no longer need `tunnel`…
interface Model<T> {
  find (properties?: EntityParametersForFind<T>, params?: OneParams): Promise<Paged<T>>
}

// For example, imagine this comes from `Entity<typeof MySchema.models.Foo>`…
interface FooType {
  foo: string
  bar: number
}

// Then we can do the following…
const fooModel: Model<FooType> = null as any

fooModel.find({
  foo: 'foo',
  bar: { between: [1, 100] }
})
```

I believe we could use similar techniques for `add`, `set`, etc.

**Comment by mobsense** [comment]
Definitely open to improvements and PRs.  You are very welcome.

My goals are to keep such changes surgical first. It is easy to come up with a TypeScript PR that is basically 100% code swap which makes accepting such changes very high risk. This change looks very good. Also good to do small such updates one at a time.

The plan was to get all the functionality for TS that we can get using the current declarations *.d.ts files and then prototype what more we could get with a "minimal disruption" conversion to TypeScript. I'm not sure if this is possible, hence the prototype to see if it is possible without turning the code into an incomprehensible heap.

**Comment by KennyDizi** [comment]
it should be very useful feature!

**Comment by markandrus** [comment]
> Definitely open to improvements and PRs. You are very welcome.

Great, I will try to open a PR today 👍 

> My goals are to keep such changes surgical first. It is easy to come up with a TypeScript PR that is basically 100% code swap which makes accepting such changes very high risk.

Yes, sounds good 👍

**Comment by KennyDizi** [comment]
looking forward to it @markandrus !

**Comment by mobsense** [comment]
Merged !!

**Comment by shishkin** [comment]
I think since this is merged (2.2.1) TypeScript compiler complains when `find` operation properties miss any of the required non-key fields. I think those should still be optional for queries.

**Comment by markandrus** [comment]
@shishkin do you have a repro example? I haven't seen this issue yet, but I'd be happy to take a look at it. @mobsense also requested a few more unit tests I could tackle at the same time.

**Comment by shishkin** [comment]
Sorry, for false alarm. It probably was a transient error in my environment. All works well now 👍
