### ISSUE TITLE
`log: true` params doesn't seem to do anything

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#23]

**Comment by mobsense** [comment]
The Model.parms.log enables logging for that one request. It is useful to override the Table logger which is typically set to only log errors and exceptions. If log == true, it will emit a 'data' level log.

First you need to provide a logger to the Table.

```
const table = new Table({
    ...
    logger: (type, message, context) => {
        console.log(tag, message, JSON.stringify)
        console.log(`${new Date}: ${type}, ${message}`)
        console.log(JSON.stringify(context, null, 4) + '\n')
    }
})
```

The design is that 'info' and 'error' messages should be emitted at the default level. Your logger may have a switch to enable emitting 'data' or 'trace' level message.

If you set params.log to true, the following line will be run:

```
this.log('data', `Dynamo "${op}" "${this.name}"`, trace, details)
```

where details has the full details of the request being run.

**Comment by bytekast** [comment]
👍
