### ISSUE TITLE
Update with `exists: null` ignores set expressions

### ISSUE THREAD

**Issue by shishkin** [sensedeep/dynamodb-onetable#231]
**Describe the bug**
DynamoDB command doesn't include `set` values and attributes when `exists:  null` is set in params. Same `set` expression is included when `exists` is either `true` or `false`. Unfortunately, neither `true` nor `false` would make sense for me as I need the updated to work regardless of wether or not the item exists, e.g. to set or update analytical data.

**To Reproduce**
Do model `update` with `set` expression and `exists: null`.

**Expected behavior**
Set expression is included in the DynamoDB command.

**Comment by shishkin** [comment]
I was not able to reproduce the bug in a small unit test inside the repo. However, I figured that desired update works if I put attributes and values to be set inside `properties` instead of `params.set`.

**Comment by mobsense** [comment]
Please follow the issue template and post complete code to reproduce.

**Comment by mobsense** [comment]
FYI: params.set can only be used for update and not create. I've tested this with update and it seems to work fine.

```
  user = await User.create({name: 'john', email: 'john@example.com', priority: 5, color: 'red'}, {log: true, exists: null})

    await User.update({id: user.id, priority: 23}, {set: {name: 'Mary'}, exists: null, log: true})
```

If this is still an issue, please submit a test case.
