### ISSUE TITLE
Missing Partial Type on EntityParametersForFind (?)

### ISSUE THREAD

**Issue by ahisley** [sensedeep/dynamodb-onetable#232]
**Describe the bug**
When using the latest version of oneTable, I noticed that a call to .find is throwing a type error when the find invocation fails to include all model properties that have been marked with required:true.  This is a change from old find Entity typing, which was using a partial type.  I see this change was made recently (https://github.com/sensedeep/dynamodb-onetable/commit/238acfd25cb63fa14f3e77f855df80c0153efd83#diff-dd51439fa31db4f94cac248b6e3bb9c79ba6d0842ef38a2193f88342528f3b16).  I don't claim to be a TS expert but I noticed that the previously existing EntityParameters type was defined as Partial.  It seems to me that EntityParametersForFind should possibly be defined in the same way?  Going back to an older version of the library removes this type error.

Lastly, I'm not a onetable expert, I'm using it for the first time to follow a workshop that includes DynamoDB and noticed this error in the workshop's code (which, I presume, worked without any TS error prior to the change above).  Apologies if I'm missing something obvious that makes this a non-issue.

**To Reproduce**

Below is the schema and find call I was using when I encountered this issue.

```const schema = {
  indexes: {
    primary: {
      hash: 'pk',
      sort: 'sk',
    },
  },
  models: {
    note: {
      type: {
        required: true,
        type: 'string',
        value: 'note',
      },
      pk: {
        type: 'string',
        value: 'note',
      },
      sk: {
        type: 'string',
        value: '${date}',
      },
      note: {
        required: true,
        type: 'string',
      },
      date: {
       required: true,
        type: 'string',
      },
      subject: {
        required: true,
        type: 'string',
      },
    },
  },
  version: '0.1.0',
  params: {
    typeField: 'type',
  },
  format: 'onetable:1.0.0',
} as const;
```

**Code throwing the type error**
```
import type { APIGatewayProxyResultV2 } from 'aws-lambda';
import { Notes, NoteType } from './notesTable';

export const handler = async (): Promise<APIGatewayProxyResultV2> => {
    const notes = await Notes.find({ pk: 'note' }, { limit: 10, reverse: true });
    return { body: JSON.stringify(notes), statusCode: 200 };
};
```

**Error Received**
```
Argument of type '{ pk: string; }' is not assignable to parameter of type 'EntityParametersForFind<NoteType>'.
  Type '{ pk: string; }' is missing the following properties from type 'EntityParametersForFind<NoteType>': type, note, date, subjectts(2345)
```

**Expected behavior**
I expected to be able to call .find without a type error.

**Screenshots**

**Environment:**
 - OS: Windows
 - Node Version: v16.13.1
 - OneTable Version: 2.2.1
 - TypeScript Version: 4.5.4

**Additional context**

**Comment by mobsense** [comment]
Did this get resolved or is it still open as an issue?

**Comment by braekevelt** [comment]
@mobsense This is still an open issue. The build of the typescript sample even fails because of it.

![image](https://user-images.githubusercontent.com/28069994/147957857-2178095f-d143-4feb-b98c-2e49ec77fa64.png)

**Comment by mobsense** [comment]
Just committed a fix. Please test and let me know if it fixes all cases.

The sample now runs.

**Comment by ahisley** [comment]
Can confirm this is working for me now.  Appreciate the fix!
