### ISSUE TITLE
Feature request: Add TTL attribute support

### ISSUE THREAD

**Issue by sdemjanenko** [sensedeep/dynamodb-onetable#233]
In order to more easily work with a TTL attribute, I would like to mark the type as Date, but have this library automatically encode the value as a Number (in seconds): https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-before-you-start.html#time-to-live-ttl-before-you-start-formatting

**Comment by mobsense** [comment]
You can set the Table params isoDates to be false, which will store dates as Unix epoch numbers as you require. However, this is not on a per API basis.

Are you suggesting we have isoDates be a parameter to the model APIs so you could do:

    await model.update({expire: Date.now() + 7 * 86400 * 1000}, {isoDates: false})

**Comment by sdemjanenko** [comment]
I was thinking something along the lines of:
```js
export const DemoSchema = {
  version: "0.0.1",
  indexes: {
    primary: { hash: "pk", sort: "sk" },
  },
  models: {
    Model: {
      ...
      expireAt: { type: Date, ttl: true },
      ...
    },
  },
};
```

The `ttl` option would use a Number field in Dynamo to encode the Date as unix epoch seconds. Then when loading the record, it would deserialize the seconds into a JS date object.

**Comment by mobsense** [comment]
Cool. Thank you.

We'd probably use the isoDates instead of TTL to avoid introducing a new term.

i.e.
    expireAt: { type: Date, isoDates: false },

This would then override your Table isoDates setting.

**Comment by mobsense** [comment]
Okay, about to commit a change to permit isoDates in model fields.

If you set isoDates in a field definition, it overrides the table definition for that field only. Works for any field including the timestamp fields. Set isoDates to true to get an ISO date. Set to false to get a Unix epoch number date. Set to null or leave unset to get the table default value.

For example:
```
const schema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
        gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    },
    models: {
        User: {
            pk:         { type: String, value: '${_type}#' },
            sk:         { type: String, value: '${_type}#${id}' },
            name:       { type: String },
            expire:     { type: Date, isoDates: false},
        }
    }
}

let expire = new Date(Date.now() + 86400 * 1000)
user = await User.create({name: 'john', email: 'john@example.com', expire}, {log: true, exists: null})
```

**Comment by mobsense** [comment]
While this is generally useful, unfortunately DynamoDB stores TTL dates in seconds not milliseconds. So the above won't solve your case and we'll need a "ttl" parameter to divide by 1000.

One question:

Would it be better to provide a number which is the number of seconds to expire in vs a date which is the date to expire on?

**Comment by sdemjanenko** [comment]
You change to take the `ttl` option on the field definition and to serialize/deserialize Date objects is great. Thanks!
