### ISSUE TITLE
Using the type field as hash key in GSI is not working; find operation throws.

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#239]
**Describe the bug**
I've created a GSI with PK the type field, and some other (name) field as sk. When I do a find by name, using this GSI instead of a query to DDB I get an error thrown stating 'Empty hash key'

**To Reproduce**

CODE in test/debug.ts
```
/*
    debug.ts - Just for debug

    Edit your test case here and invoke via: "jest debug"

    Or run VS Code in the top level directory and just run.
 */
import {AWS, Client, Entity, Match, Model, Table, print, dump, delay} from './utils/init'

jest.setTimeout(7200 * 1000)

//  Change with your schema
const schema = {
  indexes: {
    primary: { hash: "id" },
    external: { hash: "type", sk: "name" }
  },
  models: {
    User: {
      type: {
        required: true,
        type: String,
        value: "group"
      },
      id: {
        type: String
      },
      name: {
        required: true,
        type: String,
        unique: true
      },
    }
  },
  version: "0.1.0",
  params: {
    typeField: "type"
  },
  format: "onetable:1.0.0"
}

//  Change your table params as required
const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema,
    logger: true,
})

//  This will create a local table
test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Test', async() => {
    let User = table.getModel('User')
    let name = 'guest';
    let users = await User.find({name}, { index: 'external', log: true })
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```

OUTPUT of running the test:
```
$ pnpx jest debug
Determining test suites to run...Using local Java to run dynamoDB
Spawn DynamoDB 14790
Waiting for 0.0.0.0:4567...
Connected!
DynamoDB is ready
  console.log
    error Empty hash key {
        "properties": {
            "name": "guest",
            "type": "User"
        },
        "params": {
            "parse": true,
            "high": true,
            "index": "external",
            "log": true,
            "checked": true
        },
        "op": "find"
    }

      at Log.defaultLogger (src/Table.js:945:21)

 FAIL  test/debug.ts
  ✓ Create Table (1038 ms)
  ✕ Test (375 ms)
  ✓ Destroy Table (148 ms)

  ● Test

    OneError: Empty hash key. Check hash key and any value template variable references.

      924 |         if (op != 'scan' && this.getHash(rec, this.block.fields, index, params) == null) {
      925 |             this.table.log.error(`Empty hash key`, {properties, params, op})
    > 926 |             throw new OneError(`Empty hash key. Check hash key and any value template variable references.`, {
          |                   ^
      927 |                 properties, rec, code: 'Missing',
      928 |             })
      929 |         }

      at Model.prepareProperties (src/Model.js:926:19)
      at Model.queryItems (src/Model.js:771:27)
      at Model.find (src/Model.js:542:27)
      at Object.<anonymous> (test/debug.ts:61:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        3.141 s, estimated 11 s
Ran all test suites matching /debug/i.

```

**Expected behavior**
I expect a DynamoDB query to be issued with key { type: 'User', name: 'admin' }, against GSI 'external' and if such a record exists, to be returned.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS ```Linux [...] 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
 - Node Version v14.18.2
 - OneTable Version     "2.2.2"
 - TypeScript Version "^4.4.0"

**Additional context**
In src/Model.js, selectProperties function, lines 1058-1059 the type field is explicitly omitted. I had hoped the type field could participate as hash key in GSI. I couldn't find it in the documentation that such a configuration is disallowed.

I did add another field, whose value is '${type}', and using that as pk in the GSI seemed to work. Being forced to duplicate the field seems counter-intuitive and wasteful.

**Comment by mobsense** [comment]
Thanks @adrian-grajdeanu. Very good bug report. Easy to reproduce, thank you.

We don't include the type field in the properties because in 99% of cases, it is a redundant filter. However in your case, it is also the index. So it must be included.

BTW: In your User schema. You have value == 'group'. This doesn't impact the issue, but probably not what you want. If you are providing the type, you don't want a value template.

We'll commit this fix after some more test.

Here is a quick diff that fixes the issue:

```
diff --git a/src/Model.js b/src/Model.js
index 749d9f9..d2016c8 100644
--- a/src/Model.js
+++ b/src/Model.js
@@ -1055,7 +1055,7 @@ export class Model {
                     //  Attribute is not projected
                     omit = true

-                } else if (name == this.typeField && op == 'find') {
+                } else if (name == this.typeField && name != index.hash && name != index.sort && op == 'find') {
```

**Comment by adrian-grajdeanu** [comment]
Ty for quick action on fixing this.

The other matter you mentioned I'm puzzled. The 'group' value is obviously a leftover offender that snuck in through cut&paste. Normally for User it should be something akin to 'user'. But you say i should not include a value. So what should I do? Leave no value? Does it hurt if I have it in there?

Ty

Jan 4, 2022 18:40:51 mobsense ***@***.***>:

**Comment by mobsense** [comment]
A value template is a computed string that contains ${attribute} references. The run-time value for a field is computed by expanding the value template. However, if you provide an explicit property value, it overrides the value template. In your case, an explicit property value is provided for "type". Not by you, but by OneTable. i.e. it overrides the value template which was set to "group". That saved the day.

If you are using "type" for the hash key, it's value is being explicitly provided by OneTable so a value template is not needed.

**Comment by adrian-grajdeanu** [comment]
Confirm the issue is fixed with the proposed fix.
