### ISSUE TITLE
Errors (OneError, OneArgError) are not exported and not ready to be exported.

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#240]
## Errors (OneError, OneArgError) are not exported
```
import { OneError } from 'dynamodb-onetable';
```
Above statement fails. Errors thrown outside by a library should be documented, and exported, so they can be caught and handled appropriately.

## OneError.toString implementation discloses stack information.
I understand why a developer would want the stack, but the security minded guardian would not  allow solution to be shipped while leaking internals.

## Naming (OneError, OneArgError) could be improved
Suggest OneTableError and OneTableArgError for example.

**Comment by mobsense** [comment]
Good suggestion. It should be exported.

Regarding the stack, what do you suggest. It is essential for the developer to understand where an exception was thrown and Error itself captures the stack.  Can you please be a bit more specific about what you recommend?

**Comment by adrian-grajdeanu** [comment]
Error, as well as the (currently named) OneError both capture the stack. But Error.toString doesn't dump the stack. If needed, developers catch the Error, or OneError and log the toString output, as well as stack _in addition_.

**Comment by mobsense** [comment]
Quick patch to export:

```
diff --git a/src/index.js b/src/index.js
index 98758fd..4ba63a0 100644
--- a/src/index.js
+++ b/src/index.js
@@ -5,7 +5,8 @@
 import { Expression } from './Expression.js'
 import { Model } from './Model.js'
 import { Table } from './Table.js'
+import { OneError, OneArgError } from './Error'
 import ULID from './ULID.js'
 import UUID from './UUID.js'

-export { Expression, Model, Table, ULID, UUID }
+export { Expression, Model, OneArgError, OneError, Table, ULID, UUID }
```
