### ISSUE TITLE
Not all fields are returned from an update operation if it executes part of transaction due to unique fields

### ISSUE THREAD

**Issue by adrian-grajdeanu** [sensedeep/dynamodb-onetable#245]
**Describe the bug**
Update an item without any unique fields, ALL_NEW fields are returned as expected.
However, presence of unique field causes the update to be part of a transaction and in this case not all fields are returned as expected.

Making things more difficult is that even the logging is changed; One gets ```Message: OneTable "transactWrite" "_Generic"```, but no ```Message: OneTable result for "update" "User"```, so what comes back from the db is obscured.

**Cut/Paste**

test/debug.ts
```
import { inspect } from 'util';
import {AWS, Client, Match, Table, Entity, print, dump, delay} from './utils/init'

const Schema = {
  indexes: {
    primary: { hash: 'id' },
  },
  models: {
    User: {
      id: { type: String, },
      nam: {
        type: String,
        unique: true,           // this is the cause of the problem; without this line test succeeds
      },
      cAt: { type: Date, hidden: false },
      uAt: { type: Date, hidden: false },
    },
  },
  version: "0.1.0",
  params: {
    timestamps: true,
    isoDates: true,
    createdField: 'cAt',
    updatedFiled: 'uAt',
  },
  format: "onetable:1.0.0"
}

type UserType = Entity<typeof Schema.models.User>;

const id = 'aswpfhaeswr'
const nam = 'foo'
const nameOther = 'bar'

const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema: Schema,
    logger: (level, message, context) => {
        // if (level == 'trace' || level == 'data') return
        const contextMessage = context ? `Context: ${inspect(context, false, null)}` : ''
        console.log(`At: ${new Date().toISOString()}\nLevel: ${level}\nMessage: ${message}\n${contextMessage}`)
    }
})

test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Create user', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.create({ id, nam })
    expect(user.nam).toMatch(nam)
    expect(user.cAt).toBeDefined()
})

test('Update nam field should return created field too', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.update({ id, nam: nameOther }, {updateIndexes: true, log: true})
    expect(user.nam).toMatch(nameOther)
    expect(user.cAt).toBeDefined()                     // this is where the problem is observed
})

test('The nam field is really updated', async() => {
    const User = table.getModel('User')
    const user: UserType = await User.get({ id, nam })
    expect(user.nam).toMatch(nameOther)
    expect(user.cAt).toBeDefined()
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})

```

STDOUT: too long (15k+ lines) Even with the expression expansion suppressed, it is 310 lines.
Maybe this is what is relevant:
```
  console.log
    At: 2022-01-13T01:06:46.388Z
    Level: trace
    Message: OneTable "transactWrite" "_Generic"
    Context: {
      trace: {
        model: '_Generic',
        cmd: {
          TransactItems: [
            {
              Delete: {
                TableName: 'DebugTable',
                Key: { id: { S: '_unique#User#nam#foo' } }
              }
            },
            {
              Put: {
                ConditionExpression: 'attribute_not_exists(id)',
                TableName: 'DebugTable',
                Item: {
                  id: { S: '_unique#User#nam#bar' },
                  _type: { S: '_Unique' }
                },
                ReturnValues: 'NONE'
              }
            },
            {
              Update: {
                ConditionExpression: 'attribute_exists(id)',
                ExpressionAttributeNames: { '#_0': 'nam', '#_1': 'updated' },
                ExpressionAttributeValues: {
                  ':_0': { S: 'bar' },
                  ':_1': { S: '2022-01-13T01:06:46.376Z' }
                },
                TableName: 'DebugTable',
                ReturnValues: 'ALL_NEW',
                UpdateExpression: 'set #_0 = :_0, #_1 = :_1',
                Key: { id: { S: 'aswpfhaeswr' } }
              }
            }
          ]
        },
        op: 'transactWrite',
        properties: <ref *6> {
          exists: true,
          parse: true,
          high: true,
          updateIndexes: true,
          log: true,
          checked: true,
          transaction: {
            TransactItems: [
              {
                Delete: {
                  TableName: 'DebugTable',
                  Key: { id: { S: '_unique#User#nam#foo' } }
                }
              },
              {
                Put: {
                  ConditionExpression: 'attribute_not_exists(id)',
                  TableName: 'DebugTable',
                  Item: {
                    id: { S: '_unique#User#nam#bar' },
                    _type: { S: '_Unique' }
                  },
                  ReturnValues: 'NONE'
                }
              },
              {
                Update: {
                  ConditionExpression: 'attribute_exists(id)',
                  ExpressionAttributeNames: { '#_0': 'nam', '#_1': 'updated' },
                  ExpressionAttributeValues: {
                    ':_0': { S: 'bar' },
                    ':_1': { S: '2022-01-13T01:06:46.376Z' }
                  },
                  TableName: 'DebugTable',
                  ReturnValues: 'ALL_NEW',
                  UpdateExpression: 'set #_0 = :_0, #_1 = :_1',
                  Key: { id: { S: 'aswpfhaeswr' } }
                }
              }
            ]
          },
          prepared: {
            id: 'aswpfhaeswr',
            nam: 'bar',
            _type: 'User',
            updated: 2022-01-13T01:06:46.376Z
          },
...
```

STDERR:
```
$ pnpx jest test/debug.ts >/dev/null
FAIL test/debug.ts (6.342 s)
  ✓ Create Table (317 ms)
  ✓ Create user (123 ms)
  ✕ Update nam field should return created field too (56 ms)
  ✓ The nam field is really updated (8 ms)
  ✓ Destroy Table (11 ms)

  ● Update nam field should return created field too

    expect(received).toBeDefined()

    Received: undefined

      63 |     const user: UserType = await User.update({ id, nam: nameOther }, {updateIndexes: true, log: true})
      64 |     expect(user.nam).toMatch(nameOther)
    > 65 |     expect(user.cAt).toBeDefined()                     // this is where the problem is observed
         |                      ^
      66 | })
      67 |
      68 | test('The nam field is really updated', async() => {

      at Object.<anonymous> (test/debug.ts:65:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        6.406 s, estimated 7 s
Ran all test suites matching /test\/debug.ts/i.
$
```

**Expected behavior**
Expected the update to return all the item fields, as implied by default ALL_NEW. This doesn't happen, even if the { return : ALL_NEW } is specified in the update statement.

**Comment by mobsense** [comment]
Been a bit swamped the last few days. Will dig into this over the weekend.

**Comment by mobsense** [comment]
The issue here is DynamoDB write transactions do not return results.

Looking for a solution.

**Comment by mobsense** [comment]
The only solution is to do a get after the update as DynamoDB will not return results for a transactWrite.

We can optimize this if you supply params.return == 'NONE', then we can omit the get.

**Comment by adrian-grajdeanu** [comment]
Ddb does return records that were updated as part of the transaction. Admittedly i have not performed such a call to spy the content if this documented claim. But i grant you that matching the results that ddb may return with the actual customer call would be some work.

I can't argue for anything yet, as i have not seen what ddb returns and reading the documentation is fallible.

Jan 15, 2022 23:09:20 mobsense ***@***.***>:

**Comment by mobsense** [comment]
I'm not getting any item attributes in the results. The transaction has a delete, create and update. There does not seem to be a way for the API to return results.

The doc does not indicate any items returned:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

![image](https://user-images.githubusercontent.com/168091/149648438-9df0c356-5cff-4ae6-a5a5-ed2d0daadbcd.png)

**Comment by mobsense** [comment]
BatchGet returns items but batchWrite does not seem to.

**Comment by adrian-grajdeanu** [comment]
But this is not batchWrite. It is a transactWrite instead.

Jan 16, 2022 00:41:51 mobsense ***@***.***>:

**Comment by mobsense** [comment]
I mis-typed. I meant transact*

**Comment by adrian-grajdeanu** [comment]
I have grokked the documentation now, and tried calls every which way, and indeed, transactWrite is a shot in the dark; when it succeeds it is silent; one can only get details of the items in case of failure. The failure scenario is not what we are interested in right now.

You suggest performing a 'get' right after success, but that can return the wrong item content - if it were to be updated between the transactWrite and the the actual fetching by the 'get' operation. Even in the happy case, when the content is indeed unchanged, there is no efficiency gained by the library issuing the 'get'. In cases like this, I feel the library should surface to the user what it cannot do. In other words, I propose the library throw error if anything other than NONE (and a new setting, see later) is requested to be returned, explaining that transactWrite does not provide for this feature and that the caller should issue a 'get' and be prepared to handle no-atomic changes.

If I'm not mistaken the library defaults to return ALL_NEW on an 'update' operation. All of a sudden throwing error is not backwards compatible. I suggest that in the case of transacted updates, and only in the case of transacted updates, the library silently defaults to return TRANSACT_CLIENT_SIDE_VALUES (a new setting) that mimics the existing behavior. The documentation should be updated to reflect this, so that callers do not have the expectation of getting ALL_NEW.

This being said, if I were to write the library from scratch, I would have the 'update' operation and a separate 'transactUpdate' (or some such), with different documentation and different possible return settings. One variant would always do things without a transaction, the second would always invoke a transaction. When the first variant is invoked but that would result in the need for a transaction, throw error.

**Comment by mobsense** [comment]
Thanks for your detailed thoughts.

You raise a very important non-atomic issue with get returning stale data. 

If I had it again, I'd probably NOT have the default for update to return values and have users explicitly ask for them.  i.e. params.return == NONE. This would be a little faster as most updates do not require the values to be returned as the caller most often already has the item. Then we could have the update throw an exception if you use params.return != NONE when the item has unique fields. But that feels like a BIG change.

We could try to transition to this model by warning on update for users to specify params.return, then reverting the default in a future release. TS bindings may be able to warn/insist on this too for update. Thoughts?

**Comment by adrian-grajdeanu** [comment]
What you propose would be ideal, if you're willing to transition to it. Specifically having the default return be NONE, and throw error if anything else, in case the update results in transaction.

Jan 17, 2022 17:10:10 mobsense ***@***.***>:

**Comment by mobsense** [comment]
Big change .... it is a common pattern:

    let item = await db.update(....)

If we did, I'd propose we evolve to a default for params.return be NONE. Add a new option 'get' to do a non-transactional get after the update. Only throw if a transaction (i.e. unique items) and return != NONE AND return != get.

To do this, we'd probably add a warning if params.return is not defined in 2.3 with the default remaining ALL_NEW. Then in 2.4, change the default to NONE and add the exception for transactional updates requesting returned values.

**Comment by mobsense** [comment]
## Change to Update Return Value

Here is what we've implemented to fix update returning incorrect results for items that have unique properties. This solution will transition to update() not returning a result by default.

There are 2 cases:

1. Update item with unique attributes that requires a transaction
2. Update item without unique attributes that does not use a transaction

### Release Transition

For the 2.3 release, update() will continue to return a result for (2) to preserve existing behavior but will issue a warning.
For (1), the return value will be null as the current update() return value with unique attributes returns an incomplete item as transactions do not return the item.

For the 2.4 release, update will not return a result by default in all cases. i.e. the default will be {return: 'NONE'}.

Return values can be controlled via the existing params.return property. This is enhanced to make it easier to use by adding the aliases {return: true} which is the same as 'ALL_NEW' and {return: false} which evaluates to 'NONE'.

### Warnings

In 2.3, warnings will be issued for update() without a param.return that will say:

```
DEPRECATED. Update will soon not return items by default. 
Use an explicit params {return: true} to return the updated item.
Use {return: false} or Table params {warn: false} to squelch this warning.
Read more at https://github.com/sensedeep/dynmaodb-onetable/issues/245 for details.
```

If the update item has unique properties, the warning will say:

```
Update with unique items uses transactions and cannot return the updated item. Use params {return: 'get'} to do a non-transactional get of the item after the update.
```

To squelch these warnings, use the new Table param `warn: false`.

## Exceptions

In version 2.4, using a params.return to request that the item be returned for items that use or require a transaction or batched request will throw an exception.

### Documentation for Return Params

| return | `string` | Set to 'ALL_NEW', 'ALL_OLD', 'NONE', 'UPDATED_OLD' or 'UPDATED_NEW'. The `created` and `updated` APIs can return the item properties. This parameter controls the `ReturnValues` DynamoDB API parameter. The value true, is an alias for ALL_NEW. The value false is an alias for 'NONE'. The create() API defaults to 'ALL_NEW'. The updated() API defaults to 'NONE'. |

**Comment by mobsense** [comment]
We've been reviewing existing OneTable code bases to see what this change would look like and it isn't pretty.

The dominant pattern seems to be update to return an updated item. The proposed change requires the majority of update calls to be modified and more problematic, factories and wrappers around OneTable would need to be modified to always pass in the params.return.

The alternative proposal is pretty much what you suggested. i.e. transactional updates to:

1. Throw an exception if params.return requests a result be returned.
2. If no params.return supplied keep current behavior and return the client supplied properties but warn and say this will throw an exception in 2.4.
3. Support {return: 'get'} to do a transparent full get request.
4. Normal non-transactional update() path remains the same.

**Comment by mobsense** [comment]
Thanks for drawing attention to the docs.

We've improved several sections regarding {return: *} and update()
