### ISSUE TITLE
Generate parameter doesn't work in AWS environment

### ISSUE THREAD

**Issue by NevRA** [sensedeep/dynamodb-onetable#247]
**ISSUES will not receive priority that do not follow this template or cannot be easily reproduced or diagnosed**

**Describe the bug**
Hey. It looks like a great library, but I stumbled on the first step. I'm trying to test the lib in my AWS account, but for some reason the generate param from the schema doesn't work in AWS but works locally

```
export default {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
      primary: { hash: 'pk', sort: 'sk' }
  },
  logger: true,
  models: {
      Account: {
          pk:          { type: String, value: 'account' },
          sk:          { type: String, value: 'account#${id}' },
          id:          { type: String, generate: 'ulid' },
          users:       { type: Set, require: true },
          createdAt:   { type: String },
          updatedAt:   { type: String },
      },
      User: {
          pk:          { type: String, value: 'user' },
          sk:          { type: String, value: 'user#${id}' },
          id:          { type: String, require: true },
          accounts:    { type: Set },
          createdAt:   { type: String },
          updatedAt:   { type: String },
      }
  },
  params: {
      'isoDates': true,
      'timestamps': true,
      'createdField': 'createdAt',
      'updatedField': 'updatedAt',
  },
}
```

When Im trying  to:
```
type AccountType = Entity<typeof Schema.models.Account>
const table = new Table({
  client: client,
  name: process.env.TABLE,
  schema: Schema,
})

const accountResult = await AccountDb.create({
  users: new Set([userId])
})
```

But Im getting 
```
{
    "errorType": "OneError",
    "errorMessage": "Validation Error in \"Account\" for \"sk\"",
    "code": "ValidationError",
    "name": "OneError",
    "context": {
        "validation": {
            "sk": "Value not defined for required field \"sk\""
        }
    },
    "date": "2022-01-16T21:05:06.046Z",
    "stack": [
        "OneError: Validation Error in \"Account\" for \"sk\"",
        "    at Model.validateProperties (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:1304:25)",
        "    at Model.collectProperties (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:992:14)",
        "    at Model.prepareProperties (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:912:24)",
        "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:754:35)",
        "    at Generator.next (<anonymous>)",
        "    at /opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:8:71",
        "    at new Promise (<anonymous>)",
        "    at __awaiter (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:4:12)",
        "    at Model.putItem (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:748:16)",
        "    at Model.<anonymous> (/opt/nodejs/node_modules/dynamodb-onetable/dist/cjs/Model.js:481:37)"
    ]
}
```

It force me to specify sk index, but it should be generated. Locally it works, using typescript example and my schema. 
And if I specify SK manually it works in AWS:
`  const accountResult = await AccountDb.create({
    sk: 'test',
    users: new Set([userId])
  })`

What am I doing wrong? I guess I missed something but can't figure it out.

**Expected behavior**
To save record with generated id and sk to DB

**Environment (please complete the following information):**
 - OS - MacOS
 - Node Version - 14
 - OneTable Version - ^2.2.1
 - TypeScript Version - 4.5.4

**Additional context**
My serverless config:
```
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamodb.mytable}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
```
Bundler - esbuild from serverless-esbuild plugin
OneTable saved in the shared AWS Layer

**Comment by mobsense** [comment]
Could you be running a public NPM version vs the github repo?

The `generate` keyword is not yet released in an NPM version but is in the master branch. Should be released over the next week or so.

**Comment by NevRA** [comment]
Ahhh. You are right! Im using a version from npm, but Schema from the main (copy-pasted from the readme and tests). So, because it doesn't validate by TS I do not see any errors. :) I guess I should switch to the uuid.

**Comment by mobsense** [comment]
The ULID is supported in the npm version, just via a 'uuid': 'ulid' param.

The new `generate` keyword should be out in a week and hopefully will be much clearer.

**Comment by NevRA** [comment]
Btw it would be great to have TS types checking for the Schema. Thanks!

**Comment by mobsense** [comment]
What part of the schema is not being type checked?

**Comment by NevRA** [comment]
`{ type: String, generate: 'ulid' },`

**Comment by mobsense** [comment]
Can you please explain a bit more. What error were you expecting?

**Comment by NevRA** [comment]
See screenshot from VSCode above. There's a typo, but no errors, before running. It would be a great timesaver to have an error on compile-time before uploading it to AWS
![image](https://user-images.githubusercontent.com/768328/149757890-596bb6e8-fc70-4ec6-90d5-39ce66eaddf0.png)

**Comment by mobsense** [comment]
That should be picked up if you type your Schema as OneSchema.

**Comment by NevRA** [comment]
Wow, it's really working! Thanks!
