### ISSUE TITLE
Setting a limit value param that is greater than the total record count result in an error

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#26]
Error: `No value defined: {}`

Fix: https://github.com/sensedeep/dynamodb-onetable/pull/25

**Comment by mobsense** [comment]
For the record. Can you give a few more details to capture this issue more fully?

**Comment by bytekast** [comment]
sure... 

```
const items: Paged<UserMessage[]> = await UserMessageModel.find(
   { userId: 'abc' }, { limit: 5, metrics: {} }
)
``` 

if I user `abc` only has 2 messages but I set the limit to `5`, I get the error.

if I user `abc` has 5 or more messages and I set the limit to `5`,  it works fine.

I believe the `unmarshall` fails when the value of the `LastEvaluatedKey` is `{}`

**Comment by mobsense** [comment]
Thanks, appreciated.

Pull request applied and released.

**Comment by bytekast** [comment]
👍
