### ISSUE TITLE
Suggestion: Expose entity unmarshalling API

### ISSUE THREAD

**Issue by shishkin** [sensedeep/dynamodb-onetable#265]
I'm using DynamoDB Stream Events in Lambda functions. Stream records have same DynamoDB JSON structure as onetable library tries to abstract with its higher-level schema. It would really help if I could call `model.unmarshall(json)` with the event stream record item and get my entity back with all its types mapped properly as they are when fetched from a DB.

I've tried to hack my way around this by calling non-public API `model.transformReadItem` with a result from `@aws-sdk/client-dynamodb'`s `unmarshall`, but it doesn't handle attributes of type `Object`, e.g. not able to translate attributes of type `Date`. Also it's not public API and looks really hacky.

**Comment by mobsense** [comment]
Can you post a sample of what you are wanting to parse and what you want to end up with.

Sounds like you want to convert from DynamoDB unmarshalled data into Javascript AND use OneTable type transforms.

**Comment by shishkin** [comment]
Sorry for not explaining it clearly. I need to parse [`DynamoDBRecord ` objects](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/dynamodb-stream.d.ts) that look like this (omitting remaining metadata):

```json
{
  "eventName": "MODIFY",
  "dynamodb": {
    "NewImage": {
      "mydbattr1": { "S": "foo" }
    },
    "OldImage": {
      "mydbattr1": { "S": "bar" }
    }
  }
}
```

I'd like to be able to map `NewImage` and `OldImage` values into simply `{ "mydbattr1": "foo" }`. For simple case with just string attributes, dynamo client unmarshalling would do. However,  I want to apply OneTable type transforms as well to handle more complex cases, e.g. `Date` types and nested objects.

**Comment by ChristianRich** [comment]
This usually works for me:

```
import { marshall } from '@aws-sdk/util-dynamodb';

const data = {
  eventName: 'MODIFY',
  dynamodb: {
    NewImage: {
      mydbattr1: { S: 'foo' },
    },
    OldImage: {
      mydbattr1: { S: 'bar' },
    },
  },
};

unmarshall(data.dynamodb);
```

Outputs:

```
{
  NewImage: {
    mydbattr1: 'foo',
  },
  OldImage: {
    mydbattr1: 'bar',
  },
}
```

**Comment by shishkin** [comment]
> @ChristianRich This usually works for me:

Yes, that works for me too until my attributes are all primitives. This would not support `Date` attributes or map-packed attributes or encryption and would require further transformations that [Model class does](https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.js#L872-L954) under the hood. I would like that transformation exposed as a first-class API.

**Comment by mobsense** [comment]
Internally Model does the following after fetching data in parseResponse:

```
item = table.unmarshall(item, params)
model.transformReadItem(op, item, properties, params)
```

Where op is 'get', properties are used for table level transform functions only, and params are the usual API params.

You said it didn't work for objects / dates. But transformReadItem calls transformReadAttribute which does handle dates.

Note: you need a valid model with backing schema for this to work.

I'm happy to make a public wrapper over transformReadItem that does the above, but I'd like to know it works for you first.

**Comment by shishkin** [comment]
Thanks @mobsense! I wrote a test for the unmarshalling code I currently use: https://github.com/shishkin/dynamodb-onetable/blob/unmarshall-model/test/unmarshall.ts. First test case with a simple model passes. The second test case with a nested model currently fails to map attribute types.

**Comment by mobsense** [comment]
I think nested schemas are not converting dates in all use cases, not just manually by calling transform*

**Comment by mobsense** [comment]
I've committed a solution that transforms nested schemas. I've added your unit test as `test/marshal.ts` if that is okay with you under this repo MIT license. If not, I'll remove it. Just say the word.

Thanks for raising the issue.

**Comment by shishkin** [comment]
Thanks @mobsense!

**Comment by mobsense** [comment]
For some reason the CI/CD github actions are failing the marshal.ts unit test, but it works on my system. Let me know if it works for you.

**Comment by mobsense** [comment]
Looks like it is AWS V2 SDK specific.

**Comment by shishkin** [comment]
@mobsense Thanks for fixing nested transforms in https://github.com/sensedeep/dynamodb-onetable/commit/81ddf84759a6a8c4172e26bef519045cd575d98c.

I saw you closed this issue. Does it mean `unmarshallModel` is not going to make it into public API?

**Comment by mobsense** [comment]
I just wanted to have the solution tested first.

We can now make Table.unmarshall public.
