### ISSUE TITLE
Cannot install npm package in node.js APP.

### ISSUE THREAD

**Issue by jay-bhatt-jb** [sensedeep/dynamodb-onetable#27]
Command : npm i onetable-cli -g
Error : 
npm ERR! code ENOLOCAL
npm ERR! Could not install from "C:\Users\jb\AppData\Roaming\npm\node_modules\onetable-cli\src\paks\js-blend" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jb\AppData\Roaming\npm-cache\_logs\2021-04-29T11_48_31_546Z-debug.log

Can someone help me with this issue?

**Comment by mobsense** [comment]
Upgrade your npm to the latest supported npm version.
