### ISSUE TITLE
Schema has too many LSIs

### ISSUE THREAD

**Issue by mobsense** [sensedeep/dynamodb-onetable#299]
### Discussed in https://github.com/sensedeep/dynamodb-onetable/discussions/298

<div type='discussions-op-text'>

<sup>Originally posted by **kunalfleethawks** March  7, 2022</sup>
Hello @mobsense 

I have the following schema with indexes:
```
    indexes: {
                    primary: { hash: 'pk', sort: 'sk' },
                    'pk-internalActID-index': {
                        hash: 'pk',
                        sort: 'internalActID',
                        follow: false,
                    },
                    'pk-txnDate-index': {
                        hash: 'pk',
                        sort: 'txnDate',
                        follow: false,
                    },
                    'pk-stlStatus-index': {
                        hash: 'pk',
                        sort: 'stlStatus',
                        follow: false,
                    },
                    'pk-entityID-index': {
                        hash: 'pk',
                        sort: 'entityID',
                        follow: false,
                    },
                    'pk-accSk-index': {
                        hash: 'pk',
                        sort: 'accSk',
                        follow: false,
                    },
                    'pk-invNo-index': {
                        hash: 'pk',
                        sort: 'invNo',
                        follow: false,
                    },
                    'pk-invStatus-index': {
                        hash: 'pk',
                        sort: 'invStatus',
                        follow: false,
                    },
                    'acctID-trxCreated-index': {
                        hash: 'acctID',
                        sort: 'trxCreated',
                        follow: false,
                    },
                    'pk-entityId-index': {
                        hash: 'pk',
                        sort: 'entityId',
                        follow: false,
                    },
                    'pk-sk-index': {
                        hash: 'pk',
                        sort: 'sk',
                        follow: false,
                    },
                    'pk-actName-index': {
                        hash: 'pk',
                        sort: 'actName',
                        follow: false,
                    },
                    'pk-actType-index': {
                        hash: 'pk',
                        sort: 'actType',
                        follow: false,
                    },
                    'pk-payModeDate-index': {
                        hash: 'pk',
                        sort: 'payModeDate',
                        follow: false,
                    },
                    'pk-payModeNo-index': {
                        hash: 'pk',
                        sort: 'payModeNo',
                        follow: false,
                    },
                },

```
As you see all are GSI indexes, but when I run the code it gives me the following error: 
`Schema has too many LSIs` 
Is it the correct error? 
Further, I see you have added code for a limit check on LSI and GSI's in Schema.ts which is good. But, there is one caveat, LSI's are limited to 5 and GSI's are limited to 20 but GSI's can be increased on request, so if anyone is using this version of the library and has more than 20 GSI's it would fail. 

AWS Documentation 
[Amazon DynamoDB](https://aws.amazon.com/dynamodb/) made it easier for you to perform a variety of queries by increasing the [number of global secondary indexes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes) you can create per table to 20. If you need more than 20 global secondary indexes, you can [request an increase(https://aws.amazon.com/support).

</div>

**Comment by mobsense** [comment]
Thanks for the issue.

BTW: with single table design, you can reduce the number of GSIs by using overloaded sort. i.e. have a prefix that indicates a subtype. Your design will be very expensive as you are replicating the data many times.

e.g.

value: 'PayMode#${payMode}'

Then you can filter using the sort key.

**Comment by kunalfleethawks** [comment]
Yes. Thanks for the suggestion. I read about you yesterday. I will be doing the same and reducing GSI's as it will help to reduce the cost

**Comment by kunalfleethawks** [comment]
When this fix will be published?

**Comment by mobsense** [comment]
Published now.
