### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by ganeshan102** [sensedeep/dynamodb-onetable#304]
4405-b39c-2071c9c26e26 INFO TypeError: Converting circular structure to JSON --> starting at object with constructor 'IncomingMessage' | property 'req' -> object with constructor 'ClientRequest' --- property 'res' closes the circle at JSON.stringify (<anonymous>) at Log.defaultLogger (/var/task/node_modules/dynamodb-onetable/dist/cjs/Table.js:1096:46) at Log.process (/var/task/node_modules/dynamodb-onetable/dist/cjs/Table.js:1087:18) at Log.error (/var/task/node_modules/dynamodb-onetable/dist/cjs/Table.js:1077:14) at Table.<anonymous> (/var/task/node_modules/dynamodb-onetable/dist/cjs/Table.js:588:34) at Generator.throw (<anonymous>) at rejected (/var/task/node_modules/dynamodb-onetable/dist/cjs/Table.js:11:65) at processTicksAndRejections (internal/process/task_queues.js:95:5)

Team, when we check our logs, it showing the above issue at many times. Could you please check and let me know if you need any further details.

**Comment by mobsense** [comment]
Please follow the issue template and the items it asks for.

**Comment by ganeshan102** [comment]
There is no further data to update the issue template.. I just got the above issue in my logs.

**Comment by mobsense** [comment]
The issue template asks for what software version you are using and other essential information.

We can't help, unless we can reproduce the issue. You can help by creating a reproducible test case in debug.ts that we can use to isolate the issue.

Otherwise, it will be up to you to find the issue. We have insufficient information to progress here.

**Comment by ganeshan102** [comment]
Information is not sufficient. Hence closing the issue

**Comment by mobsense** [comment]
One way to diagnose this is for you to catch the exception in your code and see why the exception object has req/res. Express seems to have circular references in these objects. When that is stringified, JSON fails.

**Comment by mobsense** [comment]
See #289
