### ISSUE TITLE
Feature Request: upsert/put operation on Model

### ISSUE THREAD

**Issue by simondean** [sensedeep/dynamodb-onetable#307]
Hi.  onetable’s Model type provides `create` and `update` methods.   Would it be possible to provide an `upsert` or `put` method, that like DynamoDB’s native `put` operation, can be used regardless of whether or not a record already exists.  

At the moment, when we need upsert semantics, we’re having to bypass onetable and use the underlying DynamoDB client (just for that operation).  

Thanks

**Comment by mobsense** [comment]
We do upsert via {exists: true|false} in the params.

You can do exactly what you want via those:

```
await model.update({props}, {exists: null})
await model.create({props}, {exists: null})
```

**Comment by simondean** [comment]
Thanks for the info.  We'll change our code to that approach

I guess an entry for upserting under https://github.com/sensedeep/dynamodb-onetable/blob/main/README.md or https://doc.onetable.io/start/quick-tour/ could help people discover it future.
