### ISSUE TITLE
UnprocessedKeys not handled in batchGet (UnprocessedItems is handled in batchWrite)

### ISSUE THREAD

**Issue by huntharo** [sensedeep/dynamodb-onetable#311]
**Describe the bug**

The `batchWrite` wrapper method handles the `UnprocessedItems` return result that can happen when some writes in the batch are to shards that are overloaded.  The method correctly resubmits the items that were not written.

https://github.com/sensedeep/dynamodb-onetable/blob/edd61b47747a10a9ceaef1cac6b955588c2135ae/src/Table.js#L642-L664

The `batchGet` wrapper method does not handle the `UnprocessedKeys` return result that can happen when some of the gets in the batch are to shards that are overloaded.

https://github.com/sensedeep/dynamodb-onetable/blob/edd61b47747a10a9ceaef1cac6b955588c2135ae/src/Table.js#L601-L635

`UnprocessedKeys` does not appear anywhere in the repo (not in a comment / doc / issue saying why it was intentionally not handled while `UnprocessedItems` was handled).

**Comment by mobsense** [comment]
We have a problem here.

We can (and will) fix batchGet to process unprocessed items as you point out. That is an easy fix.

However, there is another issue with batchGet when parse == false. Currently this returns the response object. The doc is vague on what it should do and only generally says that Table.batchGet returns the items. With parse == false, it returns the items in a response.Responses[TABLE_NAME] list.

When we start processing unprocessed items, we can't just return a simple response object. With V2 SDK, the response object includes a $response and the V3 SDK return $metadata. When doing unprocessed items, we can blend the Responses items, but can't return $response or $metadata.

But this may break some existing code. I'm not sure how many people are doing batchGet with parse == false and looking at $metadata or $response. Probably few.

I'll commit the fix with these caveats.

Thoughts?
