### ISSUE TITLE
How to set GSI attributes only if referenced attributes are set?

### ISSUE THREAD

**Issue by sweepy84** [sensedeep/dynamodb-onetable#316]
Hi - Firstly I just want to say thank you for the awesome work that's been done with this library! 

I'm new to this, tried to read all the docs issues but couldn't find an answer. My issues is quite simple, I have GSIs that I set based one an attribute reference. Now as you can see below I'm doing this to `code` attribute. This is because I want to fetch items using a unique code, which is unique per model hence the prefix with `_type` in the gs1 attributes. But I don't want to fill that GSI if code doesn't exist for an item, however the below ends up filling the gs1pk and gs1sk attributes with just the type, which creates an unnecessary GSI item. How do I conditionally fill the GSI attributes only if the referenced attributes exist (without throwing an error of course) and including the `_type` prefix so I can query the GSI by that model and code?

The only thing I can think of is to have the gs1pk just be `${code}` so that it is undefined if code does not exist and gs1sk to `${_type}`, but that still creates the gs1sk unnecessarily. Ideally I can conditionally set those attributes only if `code` is defined.

```
const ProjectSchema = {
  version: '0.0.1',
  client,
  name: 'ProjectSchema',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'gs1sk' },
  },
  models: {
    Project: {
      pk: { type: String, value: '${_type}#${id}' },
      sk: { type: String, value: '${_type}#' },
      id: { type: String, required: true, generate: 'ulid' },
      code: { type: String, unique: true },
      name: { type: String, required: true },

      gs1pk: { type: String, value: '${_type}#${code}' },
      gs1sk: { type: String, value: '${_type}#' },

    },
  } as const,
}
```

**Comment by mobsense** [comment]
Good question. Are you saying, if you set the gs1pk to '${code}' and gs1sk to '${_type}' that the GSI gets created if the code is undefined?

I'll look into a good solution. But you always have the work around of providing the gs1pk and gs1sk value explicitly on your API call. That then overrides the value template.

**Comment by sweepy84** [comment]
Thanks for quick reply @mobsense 

Not quite, if I set gs1pk to `${code}` then the GSI won't be created, but what I wanted to do is `${_type}#${code}`, however is code isn't provide (because its not required) then it will def. create GSI with just `Project#`.

Yeah I totally can, but it's less than ideal. It would be great if we can have more control over the conditions of creating an attribute. I noticed that value functions have been deprecated, but I feel without function it really limits peoples ability to customise for their use case.

**Comment by mobsense** [comment]
You can do functions via the Table constructor. We want to keep the schema literal with no code. This way tools can manage the schema.

If the codes are pretty unique and you have the type in the SK, then code in the PK alone should suffice?

Another hack would be to create another attribute "typeCode" set to '${_type}#${code}' and then set the PK to "${typeCode}".  Not ideal but would work.

**Comment by sweepy84** [comment]
Yeah the first option would suffice, but yeah its not ideal.

Now I'm very curios as to why the heck that heck works?! If I put `${_type}#${code}` in gs1pk it results in "Project#" but for some reason in typeCode it doesn't resolve to anything??

**Comment by mobsense** [comment]
Apologies, I may have given bad advice.

If you use the following:

```
            pk:          { type: String, value: '${_type}#' },
            sk:          { type: String, value: '${_type}#${id}' },

            gs1pk:       { type: String, value: '${_type}#${code}' },
            gs1sk:       { type: String, value: '${_type}#' },
```

and do:

```
    let user = await User.create({
        name: 'Peter Smith',
    }, {log: true})
```

You get:

```
            "cmd": {
                "ConditionExpression": "(attribute_not_exists(#_0)) and (attribute_not_exists(#_1))",
                "ExpressionAttributeNames": {
                    "#_0": "pk",
                    "#_1": "sk"
                },
                "TableName": "DebugTable",
                "Item": {
                    "pk": "User#",
                    "sk": "User#01G0TPR3XS67Q436GS4E3EZ96J",
                    "gs1sk": "User#",
                    "name": "Peter Smith",
                    "email": "peter@example.com",
                    "id": "01G0TPR3XS67Q436GS4E3EZ96J",
                    "_type": "User"
                },
                "ReturnValues": "NONE"
            },
```

Note: the gs1pk is not present and the gs1sk is set.

This should not create a GSI entry because there is no gs1pk value.

How does OneTable do this?

When running templates, if any ${var} value is undefined, the property is excluded from the set of properties except if it is the SK of the primary key in a find/query in which case the leading prefix that is defined is used for a {beginsWith} expression.

You said:

```
But I don't want to fill that GSI if code doesn't exist for an item, however the below ends up filling the gs1pk and gs1sk attributes with just the type, which creates an unnecessary GSI item.
```

But I can only see the gs1sk being created.

**Comment by mobsense** [comment]
Here is the doc reference to the Model.find method. At the end of this section, it describes how find uses an incomplete sort key. In all other cases, the gs1pk and gs1sk properties should be discarded if they have any undefined ${refs}

**Comment by sweepy84** [comment]
thanks @mobsense!! - hmm my original issue was that the pk was also being generated with just the type because code didn't exist. I'm testing it again and somehow that's not happening...what is this voodoo magic you have done??

Anyway it appears the gs1sk is still being created because it only has the `${_type}#`, but if I use `${_type}#${code}` just like in gs1pk it doesn't resolve to a value. Maybe I just use `${_type}#${code}` for both gs1pk and gs1sk..?

Again I think value functions would be a solution for issues like this. Is this still in discussion or decided that it will be deprecated? Is there a way to still allow tools to manage schema and keep functions?

**Comment by mobsense** [comment]
Not sure, glad it works for you too.

The GSI will be created if you define a key that resolves to a value. ${_type}# will always resolve. If you put ${code} in there and it is undefined, then the PK/SK won't have a value and thus won't be created. This is the expected way to handle sparse indexes.

Putting code in the schema is problematic. So value functions mean your logic is split and the schema is no longer a literal document. So tools cannot understand how to create the keys. This breaks some modeling tools. SenseDeep being one.

So if there is a way to achieve the result by not using value functions, we strongly advise it. We could support value functions but STRONGLY document that you do not use them for the above reason. That could be a mid-ground. 

The recommended solutions are:

- Use a ${var} reference in GSI keys that will be defined for those items you want indexed in the GSI (the solution you are using).
- Provide the GSI pk/sk explicitly in the API call to override the value template.

**Comment by sweepy84** [comment]
ok thanks @mobsense - Really appreciate the support and responses! 
If I may give my 2 cents - I'm not sure what features SenseDeep cannot support as a results of using functions, but from a library adopters perspective, that is less of a concern to me than solving problems in the core use case of the library. In my humble opinion library features should not be compromised for an external tool (which I may or may not use). 
thanks again! :)

**Comment by mobsense** [comment]
HI @sweepy84. Thanks for your comments -- and we do listen and hear those.

We'll probably in the next release allow functions, but highlight what you may lose by using inline functions. Then it is your choice.
