### ISSUE TITLE
Example from README throws errors in TypeScript

### ISSUE THREAD

**Issue by m-radzikowski** [sensedeep/dynamodb-onetable#32]
Code from the README:

```typescript
import Dynamo from 'dynamodb-onetable/Dynamo';
import {Entity, Model, Table} from 'dynamodb-onetable';
import {DynamoDBClient} from '@aws-sdk/client-dynamodb';

const client = new Dynamo({client: new DynamoDBClient({})});

const MySchema = {
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
        gs1:     { hash: 'gs1pk', sort: 'gs1sk', follow: true },
    },
    models: {
        Account: {
            pk:          { value: 'account:${name}' },
            sk:          { value: 'account:' },
            id:          { type: String, uuid: true, validate: /^[0-9A-F]{32}$/i },
            name:        { type: String, required: true },
            status:      { type: String, default: 'active' },
            zip:         { type: String },
        },
        User: {
            pk:          { type: String, value: 'account:${accountName}' },
            sk:          { value: 'user:${email}' },
            id:          { type: String, required: true },
            accountName: { type: String, required: true },
            email:       { type: String, required: true },
            firstName:   { type: String, required: true },
            lastName:    { type: String, required: true },
            username:    { type: String, required: true },
            role:        { type: String, enum: ['user', 'admin'], required: true, default: 'user' },
            balance:     { type: Number, default: 0 },

            gs1pk:       { value: 'user-email:${email}' },
            gs1sk:       { value: 'user:' },
        },
    },
};

const table = new Table({
    client: client,
    name: 'MyTable',
    schema: MySchema,
});
```

throws TypeScript errors because of:

- `pk` and `sk` fields do not have `type` defined - if String is default, types do not respect that
- `User.balance` field type Number is incompatible:

```
TS2322: Type '{ indexes: { primary: { hash: string; sort: string; }; gs1: { hash: string; sort: string; follow: boolean; }; }; models: { Account: { pk: { type: StringConstructor; value: string; }; sk: { type: StringConstructor; value: string; }; id: { ...; }; name: { ...; }; status: { ...; }; zip: { ...; }; }; User: { ...; }; }; }' is not assignable to type 'OneSchema'.   Types of property 'models' are incompatible.     Type '{ Account: { pk: { type: StringConstructor; value: string; }; sk: { type: StringConstructor; value: string; }; id: { type: StringConstructor; uuid: boolean; validate: RegExp; }; name: { ...; }; status: { ...; }; zip: { ...; }; }; User: { ...; }; }' is not assignable to type '{ [key: string]: OneModelSchema; }'.       Property 'User' is incompatible with index signature.         Type '{ pk: { type: StringConstructor; value: string; }; sk: { type: StringConstructor; value: string; }; id: { type: StringConstructor; required: boolean; }; ... 8 more ...; gs1sk: { ...; }; }' is not assignable to type 'OneModelSchema'.           Property 'balance' is incompatible with index signature.             Type '{ type: NumberConstructor; default: number; }' is not assignable to type 'OneFieldSchema'.               Types of property 'default' are incompatible.                 Type 'number' is not assignable to type 'string | (() => any) | undefined'.
```

On top of that, there are missing commas in the example code.

**Comment by mkovel** [comment]
@m-radzikowski yeap, I've already  created MR for this 
https://github.com/sensedeep/dynamodb-onetable/pull/29

**Comment by mobsense** [comment]
Thanks for the commas and pk/sk missing the type. For JavaScript this defaults to String, but agree it is needed by TypeScript to drive the typing.

Thanks. Can you explain the "User.balance field type Number is incompatible"?  Are you saying the Number type is not working? I don't think the "balance" field is used as pk/sk in any of the examples.

Thanks.

**Comment by m-radzikowski** [comment]
> Thanks. Can you explain the "User.balance field type Number is incompatible"? Are you saying the Number type is not working? I don't think the "balance" field is used as pk/sk in any of the examples.

@mobsense yes, when schema in Table has a field with Number type, you get an error I posted:

> Type '{ type: NumberConstructor; default: number; }' is not assignable to type 'OneFieldSchema'.

It does not have to be used anywhere, just the declaration alone is problematic.

**Comment by mobsense** [comment]
Great, thank you. Can you post a short example?

**Comment by mobsense** [comment]
It looks like the issue isn't with Number but with the default type for numbers.

Can you please try the following patch

```
type OneFieldSchema = {
    crypt?: boolean,
    default?: (() => any) | string | number | boolean | object,
```

This changes the default type to permit number and boolean as well.

**Comment by markandrus** [comment]
Hey y'all, I do believe this is still an issue. I wanted to try out dynamodb-onetable in TypeScript an hit type errors immediately. Riffing off of one of the examples, I wrote this:

```typescript
const oneFieldSchema: OneFieldSchema = { type: String, value: 'card:${id}' }
const oneModelSchema: OneModelSchema = { pk: oneFieldSchema }
new Model(table, 'Card', {
  fields: oneModelSchema
})
```

However, this gives a type error at `fields`, which is supposed to have type

```ts
{
  [key: string]: OneModelSchema
}
```

as defined [here](https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.d.ts#L112-L114). It seems to me that there is one too many levels of nesting in the TypeScript definitions, and that `fields` should have type `OneModelSchema` directly.

**Comment by mobsense** [comment]
Hi Mark, thanks for digging into this. I've reopened the issue and have tested and applied your pull request.

Testing around the issue, and creating some unit tests for this revealed a couple of other issues that we are addressing. 

We've been migrating our internal tests to use Jest and add to the repo. I expect to push this tomorrow.

Generally, we find it easier to define schema centrally via the Table constructor. You can certainly do it per model, but I think it is easier via the schema.models in the table constructor and then use the following to create the type and the model.

```
type CardType = Entity<typeof DefaultSchema.models.Card>
let Card: Model<CardType> = table.getModel('Card')
```

I've mocked up your code sample and used it in our tests. I've defined the schema as a plain object. I've then derived the CardType from the schema. By giving <CardType> to the Model constructor, the returned model "Card" is fully typed. and Card.create is fully typed.

With your patch (thank you), this works well.

```typescript
import {AWS, Client, Entity, Model, Table, dump, print} from './utils/init'

test('Debug', async () => {

    const table = new Table({
        name: 'TypeScriptDebugTestTable',
        client: Client,
        schema: {
            indexes: {primary: {hash: 'pk'}},
            models: {},
        }
    })
    await table.createTable()

    const CardSchema = {
        pk:     { type: String, value: 'card:${id}' },
        id:     { type: String },
        issuer: { type: String },
    }
    type CardType = Entity<typeof CardSchema>

    let Card = new Model<CardType>(table, 'Card', { fields: CardSchema })

    let card = await Card.create({id: 'x4567', issuer: 'visa'}, {hidden: true})

    console.log(card.issuer)
    //. Will fail  console.log(card.x)

    expect(card.issuer).toBe('visa')
    expect(card.pk).toBe('card:x4567')

    await table.deleteTable('DeleteTableForever')
})
```

**Comment by markandrus** [comment]
Thanks a lot, @mobsense!
