### ISSUE TITLE
"String" entity properties are typed as "Buffer"

### ISSUE THREAD

**Issue by ArielPrevu3D** [sensedeep/dynamodb-onetable#320]
**Describe the bug**

When using a model definition with `String` typed properties, the properties get typed as `Buffer` by `EntityFieldFromType`.
![image](https://user-images.githubusercontent.com/77351275/164069776-f4c443a6-c616-47eb-b51e-25e68524557f.png)

This bug was introduced in `2.3.5` and was not present in `2.3.4`.

**To Reproduce**

```typescript
import { Entity } from "dynamodb-onetable";
const Model = {
  pk: { type: String, value: "${_type}:${id}" },
  sk: { type: String, value: "${_type}:" },
};

type ModelType = Entity<typeof Model>;
```

**Expected behavior**
`ModelType.pk`  and `ModelType.sk` should have the type `string | undefined`
![image](https://user-images.githubusercontent.com/77351275/164068103-5e28164d-99c4-4f60-a818-21e9b4738a77.png)

**Environment (please complete the following information):**
 - Windows 10 19044
 - Node 14.19.1
 - OneTable 2.3.5
 - TypeScript 4.4.4
 - Module `commonjs`, target `es2020`, lib `es2020`

**Additional context**
The definition of `BufferConstructor` does not seem to exist. It's good to note that the the `Buffer` type's constructor is deprecated, so the type does not make sense to me.
![image](https://user-images.githubusercontent.com/77351275/164067806-6212229c-ceaf-4dca-a33c-777f24c83a65.png)

The `String` constructor and `Buffer.from` can both take `any[]` as input, which could lead to an awkward overlap.

**Comment by mobsense** [comment]
What version of VS code are you using. 

For me, BufferConstructor is defined and the ModelType.sk and pk are typed as string.

I'm using:

vscode:

1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64

Node: 14.17
TSC: 4.3.2

**Comment by mobsense** [comment]
Typescript: 4.6.3 also works

**Comment by ArielPrevu3D** [comment]
VS Code 1.66.2 x64
TSC 4.4.4
Node v14.19.1

Can you share your tsconfig? In which file is `BufferConstructor` type defined?

**Comment by InspiredJason** [comment]
I've found I had the same issue when upgrading to 2.3.5. Only String types are affected as mentioned above. For me, my versions are:

VS Code 1.66.2 
Typescript 4.6.3
Node v14.19.0

I received errors like 'Cannot assign Buffer | undefined to string' when assigning string properties from a OneTable model

**Comment by mobsense** [comment]
A BufferConstructor is the constructor function for Buffer. It is part of Node core.

Does the error disappear when you remove the BufferConstructor line in Model.d.ts?

When you see:
>I received errors like 'Cannot assign Buffer | undefined to string' when assigning string properties from a OneTable model

Where are you seeing that error?  I need some more details as it works perfectly here and on some other sites too.

Can someone create a debug.ts (stand-alone file) that I can use in VS code to see the issue.

**Comment by simi-obs** [comment]
Same here.
dynamodb-onetable: 2.3.5
typescript: 4.6.3
node: 16.13.1
vscode: 1.66.2

Minimal reproduction file:
```ts
import { Entity } from 'dynamodb-onetable';

export const Schema = {
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'gs1sk', follow: true }
  },
  models: {
    OperationSummary: {
      pk: { type: String, value: 'stack#${stackName}' }
    }
  } as const
};

export type OperationRecord = Entity<typeof Schema.models.OperationSummary>;
```

In VS-Code it shows like this

![image](https://user-images.githubusercontent.com/90974642/164666383-e7063e71-ffdd-480a-bb6e-bb0e9853c68a.png)

**Comment by mobsense** [comment]
Thanks everyone for helping.

It works in the tree, but in a stand alone sample (thanks @simi-obs), it fails.

Quick fix is to delete the Buffer and BufferConstructor lines in the dist/mjs/Model.d.ts.

Can everyone test this out and also, change those lines to ArrayBuffer and see if that works.

Buffer is a node internal class that Typescript does not natively understand. ArrayBuffer is understood.

If I can get quick confirmation of this, we'll roll out an quick update using ArrayBuffer.

**Comment by mobsense** [comment]
I've committed this to the repo if you want to test it from there.

**Comment by simi-obs** [comment]
@mobsense yep this change fixes it for me
