### ISSUE TITLE
Best way to add support for a unique within a scope?

### ISSUE THREAD

**Issue by phstc** [sensedeep/dynamodb-onetable#321]
We have a use case where we want a uniqueness constraint for an attribute within a `scope`, for example, we want `name` to be unique scoped by `company_id`.

[Rails calls it `scope`](https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validates_uniqueness_of): 

> It can also [validate](https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validate) whether the value of the specified attributes are unique based on a :scope parameter:
`validates_uniqueness_of :user_name, scope: :account_id`.

What would be the best way to implement that functionality using OneTable?

### Some alternatives changing OneTable

* a)  optional `uniqueScope` that takes a template
* b)  optional `uniqueScope` that takes a list of attribute names

### Other alternatives without changing OneTable 😢

* c) create a virtual attribute `name_company_id` and set it with `name` + `company_id`. Cons: need to keep in sync with `name` and `company_id` changes and unnecessary use of space (new column).
* d) use a `transform` to mutate the unique PK. Cons: need to make sure all related references to `_unique` are transformed.

**Comment by mobsense** [comment]
Thank you for the suggestion.

I think I'm following you.

Are you suggesting we do something like:

    email: { type: 'string', unique: true, scope: '${company}' }. 
    company: { type: 'string' ....

And then we construct the unique string using the ${company} to scope it?

**Comment by phstc** [comment]
Hi @mobsense 

thanks for the quick reply!

> ```
> email: { type: 'string', unique: true, scope: '${company}' }. 
> ```

Yes, exactly like that. I suggested `uniqueScope` because `scope` sounds very generic, but it works for me too.


Rails actually has something like `unique: true` or `unique: { scope: '...' }` accepting `unique` as a  boolean or hash. So `scope` is not that "lose" in context. 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/105652/164125424-03f911ce-1ed4-4c69-be1d-91d822200f23.png">

See https://guides.rubyonrails.org/active_record_validations.html#uniqueness

**Comment by mobsense** [comment]
Got a patch for this working. Pretty simple really.

It works like proposed:

    email: { type: 'string', unique: true, scope: '${company}' }. 

i.e. A `scope` property that can be a literal or a template that references other properties.

The unique PK is as follows:

_unique#SCOPE#MODELE#ATTRIBUTE#VALUE

Where `scope` will be the provided scope with a '#' delimiter.

**Comment by mobsense** [comment]
Having developed this, I can see now all the use cases. Previously I avoided using unique attributes unless they were necessary to be unique globally. This greatly expands the potential for unique checks.

**Comment by mobsense** [comment]
Shipped in 2.4
