### ISSUE TITLE
Model.update returning an array instead of a single entity

### ISSUE THREAD

**Issue by phstc** [sensedeep/dynamodb-onetable#322]
**Describe the bug**

I'm calling `Branding.update` (where `Branding` is a `Model`) and it is suppose to return a `Promise<BrandingType>` but it is returning an array instead.

It says `BrandingType`, but it is returning `BrandingType[]`.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/105652/164125871-8838ad7b-1773-4174-bb5e-37f2df2f8a7c.png">

**To Reproduce**

Create a model with an unique attribute:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/105652/164126674-91fbcd7f-62c6-4bc3-8b60-c16bb256fe29.png">

Log the result of `update` and it is returning an array.

```typescript
const branding = await this.Branding.update(params, { exists: false });

console.log({ branding })
```

👇 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/105652/164126334-b3a20117-3bc7-4f18-b61c-705efb0d6cf9.png">

**Expected behavior**

Get a single entity back.

**Comment by mobsense** [comment]
Not seen this before. Must be something unique in your test. Can you please create a standalone debug.ts for us to replicate.

Update here does not return arrays for strings.

**Comment by phstc** [comment]
@mobsense sure!

```typescript
import DynamoDB, { DocumentClient } from 'aws-sdk/clients/dynamodb';
import { Entity, Table } from 'dynamodb-onetable';

const Schema = {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
  },
  models: {
    Test: {
      pk: { type: String, value: '${id}' },
      sk: { type: String, value: 'test' },
      id: { type: String, required: true },
      name: { type: String, unique: true },
    },
  } as const,
  params: {
    isoDates: true,
    timestamps: true,
  },
};

type TestType = Entity<typeof Schema.models.Test>;

const getTable = (tableName: string, client: DocumentClient) => {
  return new Table({
    client: client,
    name: tableName,
    schema: Schema,
  });
};

void (async () => {
  console.log('starting');
  const client = new DynamoDB.DocumentClient({ region: 'us-east-1' });
  const tableName = 'debug-table';
  const Test = getTable(tableName, client).getModel<TestType>('Test');

  const resultCreate = await Test.create({ name: 'test', id: '1' });
  console.log({ resultCreate });

  const resultUpdate = await Test.update({ name: 'test2', id: '1' });
  console.log({ resultUpdate }); // WRONG - it will return an [], but the interface is defined to ``Test | undefined``
  console.log('done');
})();
```

output

```
starting
{
  resultCreate: {
    id: '1',
    name: 'test',
    created: 2022-04-28T21:45:44.350Z,
    updated: 2022-04-28T21:45:44.350Z
  }
}
Update with unique items uses transactions and cannot return the updated item.Use params {return: 'none'} to squelch this warning. Use {return: 'get'} to do a non-transactional get of the item after the update. In future releases, this will throw an exception.
{
  resultUpdate: [
    {
      pk: '1',
      sk: 'test',
      id: '1',
      name: 'test2',
      _type: 'Test',
      updated: 2022-04-28T21:45:44.815Z
    }
  ]
}
done
```

The function return type `Test | undefined` does not match with the returned array.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/105652/165853875-159417ef-87c6-4b78-913a-e6de0389dcb0.png">

If I `await Test.update({ name: 'test2', id: '1' }, { return: 'get' })` (or `none`) it matches with `Test | undefined`

**Comment by mobsense** [comment]
Okay, we've got an issue with caveats.  It should return an item.

However, the item is merely a reflection of the properties you give and not a re-read of the actual updated item. They should be the same if the transaction works, however, you won't get all the properties of the item -- only the ones you updated.

Use params {get: true} to perform a transparent get after the transaction if you need all the properties. That will also bypass the issue of returning [properties] as the result.

We've committed a fix for when you don't use params.get.

**Comment by phstc** [comment]
Thank you for the explanation.

Is this https://github.com/sensedeep/dynamodb-onetable/commit/7fcd24ec0d71df5c04b41fe008e148ed4d567dd5 the fix?

> however, you won't get all the properties of the item -- only the ones you updated

I'm wondering if it should return `undefined` unless `return: get`. Returning partial properties can be confusing.

**Comment by mobsense** [comment]
Yes, but you should be able to use the live-at-head currently.

We weighed that up too. Both are sub-optimal. {return: 'get'} was the solution.  Undefined would be similarly confusing. The doc does explain this. Unfortunately, there is no elegant solution.

**Comment by phstc** [comment]
I agree, that both can be confusing. One option would be to make it void, if users want to load after updating they can do that manually. The TypeScript will help to inform. I believe that might be less confusing.
