### ISSUE TITLE
Trying to upsert with exists: false throws UniqueError on updates

### ISSUE THREAD

**Issue by phstc** [sensedeep/dynamodb-onetable#323]
**Describe the bug**

Trying to upsert within `unique: true` attributes is causing `UniqueError` on updates.

👇  works on create

```typescript
const branding = await this.Branding.update(params, { exists: false });
```

fails on update 👇 

<img width="975" alt="image" src="https://user-images.githubusercontent.com/105652/164126986-55a9825f-2072-45c7-9bbb-293c1421dbd4.png">

**To Reproduce**

Sample model:

![](https://user-images.githubusercontent.com/105652/164126674-91fbcd7f-62c6-4bc3-8b60-c16bb256fe29.png)

Call `await this.Branding.update(params, { exists: false });` twice, first works, second fails.

**Comment by mobsense** [comment]
Can you please create a debug.ts that replicates this. Then we can fix quickly.

**Comment by phstc** [comment]
@mobsense sure!

First upsert work, then I try to update again, changing a random attribute, and it fails. 

```typescript
import DynamoDB, { DocumentClient } from 'aws-sdk/clients/dynamodb';
import { Entity, Table } from 'dynamodb-onetable';

const Schema = {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
  },
  models: {
    Test: {
      pk: { type: String, value: '${id}' },
      sk: { type: String, value: 'test' },
      id: { type: String, required: true },
      name: { type: String, unique: true },
      random: { type: String },
    },
  } as const,
  params: {
    isoDates: true,
    timestamps: true,
  },
};

type TestType = Entity<typeof Schema.models.Test>;

const getTable = (tableName: string, client: DocumentClient) => {
  return new Table({
    client: client,
    name: tableName,
    schema: Schema,
  });
};

void (async () => {
  console.log('starting');
  const client = new DynamoDB.DocumentClient({ region: 'us-east-1' });
  const tableName = 'debug-table';
  const Test = getTable(tableName, client).getModel<TestType>('Test');

  const resultCreate = await Test.update(
    { name: 'testx', id: '4', random: String(Math.random()) },
    { exists: false, return: 'get' },
  );
  console.log({ resultCreate });

  const resultUpdate = await Test.update(
    { name: 'testx', id: '4', random: String(Math.random()) },
    { exists: false, return: 'get' },
  ); // <==== This will fail: TransactionCanceledException: Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed]
  console.log({ resultUpdate });
  console.log('done');
})();
```

### output

```
tarting
{
  resultCreate: {
    id: '4',
    name: 'testx',
    random: '0.9448450278360672',
    updated: 2022-04-28T22:01:59.188Z
  }
}
TransactionCanceledException
TransactionCanceledException: Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed]
```

**Comment by phstc** [comment]
As a workaround, what I'm currently doing for simulating upsert is:

```typescript
function upsert(...) {
  try {
   Test.update({ ... })
  } catch (e) {
    if (e instanceof OneTableError && e.code is `NotFoundError`) {
      Test.create({ ... })
    } else {
      throw e
    }
  }
}
```

**Comment by mobsense** [comment]
You are using {exists: false} in the first and 2nd update. The first works because the item does not exist. The second fails because the item exists.

What were you expecting to happen?

**Comment by phstc** [comment]
I wanted a true upsert. `Test.update(...)` to create or update. Similarly to `putItem` that creates or replaces. Is this possible with OneTable or should I stick with this implementation https://github.com/sensedeep/dynamodb-onetable/issues/323#issuecomment-1112719960

**Comment by mobsense** [comment]
Yes, just use exists: null on update. 

See: https://doc.onetable.io/api/model/methods/#update

```
In update, the params.exists will default to a true value to ensure the item exists. If set to null, an update will be permitted to create an item if it does not already exist. This implements an "upsert" operation.
```

**Comment by phstc** [comment]
@mobsense thank you, but I believe that's the bug, it is not, you can test this example [here](https://github.com/sensedeep/dynamodb-onetable/issues/323#issuecomment-1112695274). It is set to `false`, which should work as `null` and it does not work because of the unique attribute. 

![image](https://user-images.githubusercontent.com/105652/167064244-b1995598-a8ee-496a-9975-a3518ee20adb.png)

**Comment by mobsense** [comment]
False does not mean the same as null.

False means the item must not exist. Null means we don't create if it exists or not. If not, it is created. If so, it is updated.
True means the item must exist.
