### ISSUE TITLE
ConditionCheck operation is not supported in transaction write

### ISSUE THREAD

**Issue by pop-srw** [sensedeep/dynamodb-onetable#328]
Hi team, I have been using onetable for a while. I've found that ConditionCheck operation is not supported in transaction write. Sometime I have to ensure that data is correct before the following transaction was executed. Do you have a plan for it in the future?

Separating get item, manually check, and write transaction in order may cause the problem when concurrent task changes the same item after another task gets item and writes transaction.

```
const transaction = {}
const department = await Department.get({id: departmentId})
if (department.title == 'hr') {
  await User.create({name: 'stieve'}, {transaction: transaction})
  await table.transact('write', transaction)
}
```

May be we can do something like
```
const transaction = {}
await Department.check({id: departmentId}, {
  where: '${title} = {"hr"}',
  transaction: transaction
})
await User.create({name: 'stieve'}, {transaction: transaction})
await table.transact('write', transaction)
```

I also attach dynamodb api as a reference.
[https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html](url)

**Comment by mobsense** [comment]
Just to make sure, you are saying DynamoDB does not support condition check in transactions, but you'd like some kind of OneTable workaround?

What would the check() actually do?  Is that just a get?  If so, how can that translate into what DynamoDB actually supports?

**Comment by pop-srw** [comment]
Not really. I mean `ConditionCheck` operation already support by AWS DynamoDB. Here is how it can be used in transaction write API. https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html
```
{
   "ClientRequestToken": "string",
   "ReturnConsumedCapacity": "string",
   "ReturnItemCollectionMetrics": "string",
   "TransactItems": [ 
      { 
         "ConditionCheck": { 
            "ConditionExpression": "string",
            "ExpressionAttributeNames": { 
               "string" : "string" 
            },
            "ExpressionAttributeValues": { 
               "string" : { 
                  "B": blob,
                  "BOOL": boolean,
                  "BS": [ blob ],
                  "L": [ 
                     "AttributeValue"
                  ],
                  "M": { 
                     "string" : "AttributeValue"
                  },
                  "N": "string",
                  "NS": [ "string" ],
                  "NULL": boolean,
                  "S": "string",
                  "SS": [ "string" ]
               }
            },
            "Key": { 
               "string" : { 
                  "B": blob,
                  "BOOL": boolean,
                  "BS": [ blob ],
                  "L": [ 
                     "AttributeValue"
                  ],
                  "M": { 
                     "string" : "AttributeValue"
                  },
                  "N": "string",
                  "NS": [ "string" ],
                  "NULL": boolean,
                  "S": "string",
                  "SS": [ "string" ]
               }
            },
            "ReturnValuesOnConditionCheckFailure": "string",
            "TableName": "string"
         }, ...
```

However, I can not find the way to use condition check in `transact` method.
https://doc.onetable.io/api/table/methods/#transact](https://doc.onetable.io/api/table/methods/#transact

I suggest that `check` method can be used for condition checking before executing other operations in a transaction. The condition check can be useful in many cases.

I also attach the example of condition check implementation below
[Access control](https://www.alexdebrie.com/posts/dynamodb-transactions/)

**Comment by mobsense** [comment]
The condition check is part of the individual operations that are part of the transaction. It is not part of the top-level transaction itself.

You can use {exists: true} in the Model.create API to use a condition check.

```
let transaction = {}
await User.create({name: 'stieve'}, {exists: true, transaction: transaction})
await table.transact('write', transaction)
```

**Comment by erik-dreamteam** [comment]
submitted a PR as a proposal to adding support for this
https://github.com/sensedeep/dynamodb-onetable/pull/409

**Comment by AaronFinn95** [comment]
> submitted a PR as a proposal to adding support for this
> #409

@erik-dreamteam This is merged so I think this issue can be closed now?

**Comment by mobsense** [comment]
Yes, thank you.
