### ISSUE TITLE
runTemplate method call missing 2 arguments in Model class

### ISSUE THREAD

**Issue by dj-rabel** [sensedeep/dynamodb-onetable#334]
Hello guys, just stumbled upon a small bug.

There is a call to the runTemplate method inside of the template method in class Model, where the field is fetched but never passed as an argument.

It's right here:
https://github.com/sensedeep/dynamodb-onetable/blob/e91b1c121117ae8c41637c6f254cca1b4ff4b052/src/Model.js#L1394

**Screenshots**
Method signature of runTemplate() looks like this:
![image](https://user-images.githubusercontent.com/4653214/167803557-4b1e1b0a-6cf8-4645-b6bc-3ea3de3aa4dd.png)

But call is looking like this:
![image](https://user-images.githubusercontent.com/4653214/167803782-2ce75c18-8936-484a-a249-4e45685d1b1e.png)

Looks like the fix is pretty simple. I already checked it on my machine an it is working like this:
![image](https://user-images.githubusercontent.com/4653214/167804079-86596f32-b1b4-43cf-9bc4-6cec115db8b9.png)

So just adding field and field.value to the method call args, does the trick.

**To Reproduce**
Just simply create yourself a model with a property as a template (eg "foo-${bar}-buz"). Get the model in js/ts and try to call the template method. It fails with an error like "Cannot call method replace on undefined!". Caused by not passing field.value.

Example code snippet:
```
const schema = {
  "indexes": {
    "primary": {
      "hash": "PK",
      "sort": "SK"
    }
  },
  "models": {
    "Order": {
      "type": {
        "type": "string",
        "value": "Order"
      },
      "PK": {
        "type": "string",
        "value": "ORDER~${OrderId}"
      },
      "SK": {
        "type": "string",
        "value": "ORDER"
      }
    }
  },
  "version": "0.1.0",
  "params": {
    "typeField": "type"
  },
  "format": "onetable:1.0.0",
  "queries": {}
} as const;

const client = new Dynamo({
  client: new DynamoDBClient({}),
});
const table = new Table({
  client,
  name: process.env.TABLE,
  schema: schema as OneSchema,
  hidden: false,
  isoDates: true,
});

type OrderEntity = Entity<typeof schema.models["Order"]>;
const str = table.getModel<OrderEntity>("Order").template("PK", {
  OrderId: 123,
});

console.log(str);
```

**Expected behavior**
Output should be "ORDER~123" then.

**Environment (please complete the following information):**
 - OS: Windows 10 WSL 2 Ubuntu 20.04
 - Node Version: v16.14.2
 - OneTable Version: 2.3.6
 - TypeScript Version: 4.6.3

**Additional info**
The template method is not present in Model.d.ts, not sure why as it is indeed present in the onetable docs.
https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.d.ts#L259
https://doc.onetable.io/api/model/methods/#template

Don't hesitate to contact me if there are any relevant information missing.

**Comment by mobsense** [comment]
Thank you!.

**Comment by dj-rabel** [comment]
Your welcome, but I'm sorry to tell you, that the fix is still wrong 🙈 

you've added this:
`return this.runTemplate('find', null, properties, params, field.value)`

but should be this:
`return this.runTemplate('find', null, field, properties, params, field.value)`
