### ISSUE TITLE
Setting `metrics.source` and `metrics.tenant` per request to a lambda function

### ISSUE THREAD

**Issue by simondean** [sensedeep/dynamodb-onetable#336]
## Describe the bug

The `table.setParams(params)` function is available in the library's `Table.js` but it is not included in the type definition for the Table class in the `Table.d.ts` file

##  To Reproduce

N/A

## Cut/Paste

N/A

## Expected behavior
The `table.setParams(params)` function is available to use from TypeScript code

## Screenshots
N/A

## Environment (please complete the following information)
N/A

## Additional context
I'm trying to set `params.metrics.source` and `params.metrics.tenant` per request to a lambda.  The lambda is handling resolve requests from an AppSync instance, and I want to vary the `source` for `dynamodb-onetable`'s metrics based on what query/mutator has been called for each request.  The `tenant` also varies per request to the lambda, and I'd like to set that per request too

It would be great if the `Table` class exposed a new `setMetrics(metrics)` function that could be used to set `source` and `tenant` rather than having to call `setParams(params)` per request to a lambda

Thanks for the great library

**Comment by mobsense** [comment]
Thanks. Good suggestion.
