### ISSUE TITLE
🐛 "Model API Params" link is broken in the docs

### ISSUE THREAD

**Issue by phstc** [sensedeep/dynamodb-onetable#341]
👋 "Model API Params" link is broken in the docs.

https://doc.onetable.io/api/model/methods/#model-api-params

![image](https://user-images.githubusercontent.com/105652/171321029-12af9216-968a-4f43-8c82-c2d6ef08d17a.png)

**Comment by mobsense** [comment]
Thanks. We'll fix.

These issues can be logged at: 

https://github.com/sensedeep/onedoc
