### ISSUE TITLE
cant install the package 

### ISSUE THREAD

**Issue by ahmedesa** [sensedeep/dynamodb-onetable#347]
$ npm install dynamodb-onetable
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sts@3.121.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by mobsense** [comment]
Can you provide more info as per the issue template.
