### ISSUE TITLE
Feature: Add types in batch get

### ISSUE THREAD

**Issue by mobsense** [sensedeep/dynamodb-onetable#348]
### Discussed in https://github.com/sensedeep/dynamodb-onetable/discussions/337

<div type='discussions-op-text'>

<sup>Originally posted by **ShivamJoker** May 21, 2022</sup>
It would be great to get typescript types in the batchGet response as well.

Right now it returns an array of unknown which is not helpful at all.

![image](https://user-images.githubusercontent.com/23727670/169645979-2e28eb4a-6ffc-44e4-9b96-5473515b2af1.png)
</div>

**Comment by loetjvr** [comment]
I believe I have this one sorted as well. I will open a PR after #369 cause I need those changes

**Comment by mobsense** [comment]
Great! Thank you.

**Comment by sdemjanenko** [comment]
One note on this typing, I've found that `batchGet` returns a `Responses` key normally, but when `parse: true` is set as an option, it returns an array of initialized models. Its a little confusing that setting an option changes the response type so drastically.

**Comment by mobsense** [comment]
Thanks for raising the issue.

That is the case for all APIs. Parse has a big impact.

When you use parse() which is the default for the low level APIs, the returned data is parsed as models.

If not, then it is useful to get the raw responses.

Can you point out where in the doc you found this confusing and we can clarify.

**Comment by mobsense** [comment]
Sorry, nothing yet. Do you want to try to propose a solution.

**Comment by mobsense** [comment]
Sorry for the slow answer.

But batchGet is typically used to fetch multiple different types. I suppose you could provide a union as the generic type: e.g. User | Account | Item ....

If you just want to fetch users, then find() would be a better choice.

**Comment by mobsense** [comment]
The downside of that change to use a generic type would be that it would break existing TS code would it not?

**Comment by martinmicunda** [comment]
> The downside of that change to use a generic type would be that it would break existing TS code would it not?

it shouldn't (depends on the `ts-config`) as generic type would be optional because of default initialisation `<T = {}>`

```
batchGet<T = {}>(batch: any, params?: OneParams): Promise<T[]>
```

use type

```
const users = await this.table.batchGet<User>(params.batch, params)
```

or without type


```
const users = await this.table.batchGet(params.batch, params)
```

**Comment by mobsense** [comment]
We'll commit that change. If you and other could test and if okay, we'll add to the next point release.

**Comment by martinmicunda** [comment]
@mobsense yeah I can test it :)
