### ISSUE TITLE
OneTable Build Issue

### ISSUE THREAD

**Issue by ganeshan102** [sensedeep/dynamodb-onetable#353]
Hi,

We're getting the below issue suddenly in the environment build. We've not changed anything recently related with One Table. Please check and provide the solution. Thanks.

**Node - 16.x
dynamodb-onetable - 2.3.6**

**Issue:**
~/CDK/gc_validation$ npm run build

content-gc-validation@0.1.0 build
tsc

node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:109:65 - error TS2344: Type 'T["schema"]' does not satisfy the constraint 'OneTypedModel'.
**Type 'OneModelSchema | undefined' is not assignable to type 'OneTypedModel'.**
Type 'undefined' is not assignable to type 'OneTypedModel'.

109 : T['type'] extends (ObjectConstructor | 'object') ? Entity<T["schema"]>
~~~~~~~~~~~

node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:114:61 - error TS2344: Type 'T["items"]' does not satisfy the constraint 'OneField'.
Type 'OneField | undefined' is not assignable to type 'OneField'.
Type 'undefined' is not assignable to type 'OneField'.

114 : T['type'] extends 'typed-array' ? EntityFieldFromType<T["items"]>[]
~~~~~~~~~~

Found 2 errors in the same file, starting at: node_modules/dynamodb-onetable/dist/mjs/Model.d.ts:109

**Package.json**
{
"name": "content-gc-validation",
"version": "0.1.0",
"bin": {
"content_gc_validation": "bin/content-gc-validation.js"
},
"scripts": {
"build": "tsc",
"watch": "tsc -w",
"test": "jest",
"cdk": "cdk",
"build+synth": "npm run build && npm run cdk synth",
"validate": "npm run build && npm run test && npm run cdk synth && npx tslint --project ./tslint.json"
},
"devDependencies": {
"@aws-cdk/assert": "^1.96.0",
"@types/jest": "^26.0.24",
"@types/jsonwebtoken": "^8.5.6",
"@types/jwk-to-pem": "^2.0.1",
"@types/node": "16.3.2",
"aws-cdk": "^1.96.0",
"jest": "^26.6.3",
"ts-jest": "^26.5.6",
"ts-node": "^10.1.0",
"typescript": "^4.3.5"
},
"dependencies": {
"@aws-cdk/aws-cloudwatch": "^1.96.0",
"@aws-cdk/aws-dynamodb": "^1.96.0",
"@aws-cdk/aws-glue": "^1.96.0",
"@aws-cdk/aws-iam": "^1.96.0",
"@aws-cdk/aws-kinesisfirehose": "^1.96.0",
"@aws-cdk/aws-kinesisfirehose-destinations": "^1.96.0",
"@aws-cdk/aws-lambda": "^1.96.0",
"@aws-cdk/aws-lambda-event-sources": "^1.96.0",
"@aws-cdk/aws-lambda-nodejs": "^1.96.0",
"@aws-cdk/aws-logs": "^1.96.0",
"@aws-cdk/aws-route53-targets": "^1.96.0",
"@aws-cdk/aws-s3": "^1.96.0",
"@aws-cdk/aws-sqs": "^1.96.0",
"@aws-cdk/aws-ssm": "^1.96.0",
"@aws-cdk/aws-stepfunctions": "^1.96.0",
"@aws-cdk/aws-stepfunctions-tasks": "^1.96.0",
"@aws-cdk/core": "^1.96.0",
"@aws-cdk/custom-resources": "^1.96.0",
"@aws-sdk/lib-dynamodb": "^3.44.0",
"aws-sdk": "^2.1039.0",
"dynamodb-onetable": "^2.3.6",
"fast-csv": "^4.3.6",
"jsonpath-plus": "^6.0.1",
"jsonwebtoken": "^8.5.1",
"jwk-to-pem": "^2.0.5",
"source-map-support": "^0.5.19",
"request": "^2.88.2"
}
}

**Comment by mobsense** [comment]
A schema and reproducible test file would help.

**Comment by ganeshan102** [comment]
export const schema = {
    version: '1.0.1',
    indexes: {
        primary: {
            hash: 'PK',
            sort: 'SK'
        },
        GSI1: {
            hash: 'GSI1PK',
            sort: 'GSI1SK'
        }
    },
    models: {
        ValidationType: {
            PK: {
                type: String
            },
            SK: {
                type: String
            },
            id: {
                type: String
            },
            name: {
                type: String
            },
            name_de: {
                type: String
            },
            description: {
                type: String
            },
            description_de: {
                type: String
            },
            parameters: {
                type: Array
            },
            priorityQueueArn: {
                type: String
            },
            standardQueueArn: {
                type: String
            }
        },
        ValidationSchema: {
            PK: {
                type: String,
                value: '${name}-${created}'
            },
            SK: {
                type: String
            },
            id: {
                type: String,
                value: '${PK}'
            },
            name: {
                type: String
            },
            description: {
                type: String
            },
            scope: {
                type: String
            },
            GSI1PK: {
                type: String,
                value: '${SK}'
            },
            GSI1SK: {
                type: String,
                value: '${PK}'
            },
            family: {
                type: String
            },
            templateIds: {
                type: Array
            },
            importRejectBelow: {
                type: Number
            },
            importApproveAbove: {
                type: Number
            },
            status: {
                type: String
            },
            executionCount: {
                type: Number
            }
        },
        ViolationSeverity: {
            PK: {
                type: String
            },
            id: {
                type: String,
                value: 'S-${created}'
            },
            SK: {
                type: String,
                value: 'VS#S#${id}'
            },
            name: {
                type: String
            },
            uiColor: {
                type: String
            },
            scoreMultiplier: {
                type: Number
            }
        },
        ValidationRule: {
            id: {
                type: String,
                value: 'R-${created}'
            },
            PK: {
                type: String,
                value: '${schemaId}'
            },
            violationSeverityId: {
                type: String
            },
            SK: {
                type: String,
                value: 'VS#R#${violationSeverityId}#R#${id}'
            },
            name: {
                type: String
            },
            description: {
                type: String
            },
            validationTypeId: {
                type: String
            },
            parameters: {
                type: Object
            },
            GSI1PK: {
                type: String,
                value: '${schemaId}'
            },
            GSI1SK: {
                type: String,
                value: 'R#${id}'
            },
            schemaId: {
                type: String
            }
        },
        CatalogValidationSchema: {
            PK: {
                type: String
            },
            SK: {
                type: String,
                value: 'CVS#${catalogId}'
            },
            GSI1PK: {
                type: String,
                value: '${catalogId}'
            },
            GSI1SK: {
                type: String,
                value: 'CVS#${PK}'
            },
            scope: {
                type: String
            },
            catalogId: {
                type: String
            }
        }
    }
};


Above is our schema.ts file.. We don't have test file to reproduce this issue.. This is an existing code which is building without issues till last week.. From this week only, we are facing the build issue.. We've not changed anything on our end.

**Comment by ganeshan102** [comment]
@mobsense Could you please check the attached image for your reference.
![image](https://user-images.githubusercontent.com/31682699/177531836-c4914197-c8e2-43f5-9007-c3b6020136eb.png)

**Comment by mobsense** [comment]
Did  you upgrade. If so, from what version?

**Comment by ganeshan102** [comment]
We've upgraded npm from 14 to 16

**Comment by ganeshan102** [comment]
And our code is failing on node 14 also :(

**Comment by ganeshan102** [comment]
Any updates regarding this?

**Comment by mobsense** [comment]
That schema works fine for us. 

If your build was working and your OneTable version was pinned via the package.json to a specific version and you have not upgraded OneTable, then the issue must be elsewhere. We cannot change your build if it was working. Even if we release a new version, NPM will never modify an old version -- so we cannot impact your build.  So you must have changed something in your build environment or your other list of packages or tools. I'd suggest you revert back to what was working and then surgically change things to see what works.

Now there could have been a bug all along and something in your build system masked the issue. But I've not seen this reported by anyone else yet. So the same prescription applies. Revert back to what worked and then step forward. 

Otherwise, the standard advice works. Create a reproducible test case that demonstrates the problem that we can use here.
i.e. cut down a simple test.ts that includes your schema and demonstrates these issues in vs code.

**Comment by ganeshan102** [comment]
Thanks for your recommendations. We will try with Node16 and OneTable version 2.3.8 and update to you here.

**Comment by sdemjanenko** [comment]
I ran into this issue and the problem is that there is a mis-match between my TSConfig and the one this project uses. 

If you update the tsconfig.json of this project to
```
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["es2020"],
    "module": "commonjs",
    "outDir": "./lib",
    "declaration": true,
    "strict": true,
    "allowJs": false,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```
The issue will show. 
![image](https://user-images.githubusercontent.com/234437/185987475-7d5f7ac1-7f94-4fe4-9296-d94696638f35.png)

**Comment by sdemjanenko** [comment]
Adding `"skipLibCheck": true` fixes the issue, but it would be ideal if I didn't have to turn that off because of this library.

**Comment by mobsense** [comment]
We'll have a look at this as part of our current TS work. Thanks for raising.

**Comment by dev-embedthis** [comment]
Was this just due to the  "strict": true?  What setting is the one that triggers this?
