### ISSUE TITLE
Recursive merge check is preventing real object to be stored

### ISSUE THREAD

**Issue by kujtimiihoxha** [sensedeep/dynamodb-onetable#356]
**Describe the bug**

If you have very deeply nested objects that you want to store in one field this line here prevents that:
https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Table.js#L1037

I think there needs to be a better way to detect a recursion.

**To Reproduce**
Just try to store an object that has more than 20 nested parameters.

**Expected behavior**
Onetable should not prevent us from storing something in the DB based on the complexity of the object.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mobsense** [comment]
I don't know of a better way to check recursion. But the limit of 20 could certainly be much higher say 1K.

If you have recursion, you'll very quickly get 1K or more. So it is simply a safety catch for bad nested objects.

We'll up the limit to 1K.

**Comment by kujtimiihoxha** [comment]
Ok this is great... thanks for the quick fix :)

**Comment by kujtimiihoxha** [comment]
@mobsense when is this supposed to be released? I am seeing some issues in my app because of this and was wondering if I should work around this or is this close to a release. Thanks.

**Comment by mobsense** [comment]
Looking to release this weekend.
