### ISSUE TITLE
Nested schema properties with required flag are required when updating entity

### ISSUE THREAD

**Issue by AXSJ** [sensedeep/dynamodb-onetable#359]
**Describe the bug**
When using onetable with typescript, in a nested schema if there is a required flag on the properties, those fields will be required when updating the entity. Typescript will produce an error. Nested properties should only be required when creating the entity, not when updating it. 

**To Reproduce**

Run the below code.

**Cut/Paste**

```
import { Table, Entity } from 'dynamodb-onetable'
import * as DynamoDB from 'aws-sdk/clients/dynamodb'

const client = new DynamoDB.DocumentClient({ region: REGION })

const ProductSchema = {
  version: '0.0.1',
  client,
  name: 'ProductSchema',
  models: {
    Product: {
      key: { type: String, value: '${_type}#${id}' },
      rangekey: { type: String, value: '${_type}#' },
      id: {
        type: String,
      },
      measurements: {
        type: Object,
        required: true,
        schema: {
          size: { type: Number, required: true },
          frontage: { type: Number, required: true },
          depth: { type: Number, required: true },
        },
      },
      address: {
        type: Object,
        required: true,
        schema: {
          street: { type: String, required: true },
          city: { type: String, required: true },
          state: { type: String, required: true },
        },
      },
    },
  } as const,
  params: {
    isoDates: true,
    timestamps: true,
  },
}

const table = new Table({
  client,
  name: TABLENAME,
  schema: ProductSchema,
  logger: true,
  timestamps: true,
})

type ProductType = Entity<typeof ProductSchema.models.Product>

export const ProductModel = table.getModel<ProductType>('Product')

async function test() {
const update = {
  product: {
    name: `Lot ${Math.random()}`,
    stage: 'new updated stage',
    price: {
      price: 444.444,
    },
    measurements: {
      size: 1.2,
      frontage: 1.3,
      // depth: 1.4,
    },
    address: {
      street: '123 New Street',
      city: 'New City',
      postcode: '4212',
      state: 'NSW',
    },
  },

}

const { id, product: productUpdate } = update

const product = await ProductModel.update(
  {
    id,
    ...productUpdate,
  },
  {
    return: 'get',
    log: true,
  },
)
}

test()
```

You will see if you uncomment `depth` in the `update` variable the error goes away. 

**Expected behavior**
The required flag for nested properties should only produce errors If a value is not provided on the creation of the entity, not when updating the entity. 

**Environment (please complete the following information):**
 - Node 14.19.1
 - MacOS 12.3
 - OneTable 2.38
 - TypeScript Version "^4.6.3"

**Additional context**

**Comment by mobsense** [comment]
Hi, I think this is the same issue as #358.

The typescript warning is correct for the current behavior. i.e. it is telling you that if you supply the object, you must supply all required nested fields.

If you agree, let's close this and continue the discussion in #358

**Comment by AXSJ** [comment]
Yes, I think it's somewhat related but not sure if the issue should be closed. When creating an item any field marked as required must be provided as it is necessary for the creation of the item, the item should'nt/cannot exist without the required fields. However, after the creation of the item, those "required" parameters have been met, and you should be free to update the item in your database as you see fit. That is how it currently works for fields that are not in an object, if the field is marked as required they are not required when updating the ite, only when creating. If you were to change the method to a 'create' instead of 'update' and then commented out the name field from the `update` variable you will rightly see an error, but when you change the method back to an `update` the error for the name field not being provided will go away. I believe the same functionality should exist for the nested fields inside an object. 

I guess this is how #358 is related, if you don't provide all required nested fields in an object during an update, and any nested fields that were previously existing will be removed and replaced with the update.    

The issue is that updates should be as flexible as possible. It's not possible to foresee all possible future data changes that may occur and accomodate that in the schema. That is why in my opinion that updates should be flexible. Currently, onetable is dictating the form of my update and what should be included in my update.

**Comment by mobsense** [comment]
No disagreement, updates should be flexible, but the current implementation will overwrite the contents of nested objects unless all properties are provided (See #358). I know this is not ideal. Nested schemas were added after the original implementation and if I could have it again, I'd change the default to not overwrite. Because we have existing code that assumes this behavior, any change must be done in a non-breaking way.

The typescript warning currently supports the behavior described in #358 which is that you will overwrite nested fields if you don't provide them on an update. So the typescript warning is actually helping if you have designated them as required. 

Lets continue this discussion on #358.
