### ISSUE TITLE
Unable to find with GSI and limited fields projection

### ISSUE THREAD

**Issue by shishkin** [sensedeep/dynamodb-onetable#364]
**Describe the bug**

I have a table that has GSI and a subset of included fields. I'm unable to use `find` to retrieve items by key and get the required field projection.

**To Reproduce**

See https://github.com/shishkin/dynamodb-onetable/blob/5bda799453cf2c1f4ce9f93d4f09ff5f08d4d89d/test/debug.ts.

**Cut/Paste**

Schema:

```typescript
const schema: OneSchema = {
  version: "0.0.1",
  indexes: {
    primary: { hash: "pk", sort: "sk" },
    gs1: { hash: "gs1pk", sort: "gs1sk", project: ["name"] },
  },
  models: {
    User: {
      pk: { type: String, value: "${_type}#" },
      sk: { type: String, value: "${_type}#${id}" },

      gs1pk: { type: String, value: "${_type}#" },
      gs1sk: { type: String, value: "${_type}#${dob}" },

      name: { type: String },
      dob: { type: Date },
      id: { type: String, generate: "ulid" },
    },
  },
  params: {
    isoDates: true,
  },
};
```

Test:

```typescript
  const now = new Date();
  const User = table.getModel("User");
  await User.create({
    name: "Alice",
    dob: now,
  });
  const users = await User.find(
    {
      // This throws: OneTableError: Empty hash key. Check hash key and any value template variable references.
      gs1sk: { ">=": `User#${now.toISOString()}` },

      // This throws OneTableError: Value for "gs1sk" is not a primitive value
      // dob: { ">=": now },
    },
    {
      index: "gs1",
      hidden: true,
    }
  );
  expect(users).toHaveLength(1);
  expect(users[0]).toMatchObject({
    name: "Alice",
  });
```

**Expected behavior**

I expect there to be a way to use DynamoDB find operation with GSI and get projected fields.

**Comment by mobsense** [comment]
Awesome issue description. Thank you for providing the gist to debug.ts -- you go to the front of the queue!

**Comment by mobsense** [comment]
Your project: ["name"] is the cause of the issue. Remove that and it will work.

If you only project the name, the gs1sk is not projected and not present for the query.

**Comment by shishkin** [comment]
Removing it would mean projection of all attributes and I I explicitly need to limit index attribute projection. My example also works if I `project: "keys"` and do `follow: true`. But now I want to optimize it and make use of GSI attribute projection.

According to [AWS docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Projection.html) keys are always projected. How can I represent AWS' `INCLUDE` projection with onetable?

**Comment by mobsense** [comment]
Then add a list of all required attributes. Note: this list is used by OneTable and should match your actual table definition.

For onetable, you need to include the keys in the list and any field used in value templates.

**Comment by shishkin** [comment]
Thanks, I've made it work by adding keys to `project: ["pk", "sk", "gs1pk", "gs1sk", "name"]. It solves the issue, but I think it is inconsistent with AWS DynamoDB API which explicitly states that attributes listed in `INCLUDE` are projected *in addition* to keys. That leads to confusion.

Maybe onetable could take just the extra attributes in `project` and add keys internally depending on which index is used?

**Comment by mobsense** [comment]
Fixed.
