### ISSUE TITLE
Prevent redundant attributes

### ISSUE THREAD

**Issue by raffiht** [sensedeep/dynamodb-onetable#367]
From the README:

<img width="867" alt="Screen Shot 2022-07-20 at 8 06 15 PM" src="https://user-images.githubusercontent.com/89877489/180121215-dc2ba8dd-3176-4ef3-a465-42a49b47ba7c.png">

It's nice not to have to specify a pk/sk (or gsi) as an attribute when creating items. Passing down an id, username, etc. instead of gs1pk: `username:${username}` is certainly more readable. 

But it also seems redundant to have id persisted as a separate attribute in dynamo, since we can always translate it back from the (ie. id = pk.replace(`account:`, ``). Is there a way to prevent an attribute in the schema from being persisted?

**Comment by mobsense** [comment]
You can set the index.project to a list of properties to project. Then a supplied ID will be used for the value template, but will not be independently saved.

However, when you read the item, you will not get the ID. The sk can be returned if you set hidden: true. But you will need to decode via sk.split(':')[1] to get the ID. May be worthwhile if you are really pressed for storage.
