### ISSUE TITLE
Substitution for a where clause on a create fails

### ISSUE THREAD

**Issue by jsaundersonc** [sensedeep/dynamodb-onetable#368]
**Describe the bug**

Performing a create operation on a model using a where clause and substitutions fails as attribute values for the where clause do not get attached to the DynamoDB command. 

Previously we were using an update and this works as expected, but we needed to change to using a create with `exists: null` to override the existing record each time.

The cause appears to be in [Expression.js](https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Expression.js#L487).

`ExpressionAttributeValues: (namesLen > 0 && valuesLen > 0) ? values : undefined,`

Attribute values are only attached to the command if there is at least one name, but when performing a create there are no names - only the values referenced in the where.

**To Reproduce**

**Cut/Paste**

Include the code from your debug.ts here and replace the CODE segment. Remember to preserve the three backticks above and below the code block.  See [Formatting Code](https://www.freecodecamp.org/news/how-to-format-code-in-markdown/) for details.

```
import {AWS, Client, Entity, Match, Model, Table, print, dump, delay} from './utils/init'
import { OneSchema } from '../src/index.js'

jest.setTimeout(7200 * 1000)

//  Change with your schema
const schema: OneSchema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
        gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    },
    models: {
        User: {
            pk:          { type: String, value: '${_type}#' },
            sk:          { type: String, value: '${_type}#${id}' },

            gs1pk:       { type: String, value: '${_type}#' },
            gs1sk:       { type: String, value: '${_type}#${id}' },

            name:        { type: String },
            email:       { type: String },
            id:          { type: String, generate: 'ulid' },
        }
    }
}

//  Change your table params as required
const table = new Table({
    name: 'DebugTable',
    client: Client,
    schema,
    logger: true,
})

const model = table.getModel("User")

//  This will create a local table
test('Create Table', async() => {
    if (!(await table.exists())) {
        await table.createTable()
        expect(await table.exists()).toBe(true)
    }
})

test('Test', async() => {
    const result = await model.create({
        id: '1',
        name: 'abc',
        email: 'abc@def.com',
    });

    await model.create({
        id: '1',
        name: 'abc',
        email: 'abc@ghi.com',
    }, {
        exists: null,
        where: `email < @{emailSub}`,
        substitutions: {
            emailSub: 'z',
        },
    });
})

test('Destroy Table', async() => {
    await table.deleteTable('DeleteTableForever')
    expect(await table.exists()).toBe(false)
})
```

Log output:
```
     error OneTable exception in "put" on "User" {
        "err": {
            "name": "ValidationException",
            "$fault": "client",
            "$metadata": {
                "httpStatusCode": 400,
                "requestId": "896d695d-63ec-4294-8aab-b762649f5707",
                "attempts": 1,
                "totalRetryDelay": 0
            },
            "__type": "com.amazon.coral.validate#ValidationException",
            "message": "Invalid ConditionExpression: An expression attribute value used in expression is not defined; attribute value: :_0"
        },
        "trace": {
            "model": "User",
            "cmd": {
                "ConditionExpression": "email < :_0",
                "TableName": "DebugTable",
                "Item": {
                    "pk": {
                        "S": "User#"
                    },
                    "sk": {
                        "S": "User#1"
                    },
                    "gs1pk": {
                        "S": "User#"
                    },
                    "gs1sk": {
                        "S": "User#1"
                    },
                    "name": {
                        "S": "abc"
                    },
                    "email": {
                        "S": "abc@ghi.com"
                    },
                    "id": {
                        "S": "1"
                    },
                    "_type": {
                        "S": "User"
                    }
                },
                "ReturnValues": "NONE"
            },
            "op": "put",
            "properties": {
                "pk": "User#",
                "sk": "User#1",
                "gs1pk": "User#",
                "gs1sk": "User#1",
                "name": "abc",
                "email": "abc@ghi.com",
                "id": "1",
                "_type": "User"
            }
        }
    }
```

**Expected behavior**
Attribute values which are used in the condition expression are attached to the command, allowing the command to succeed.

**Environment (please complete the following information):**
 - OS: Mac OS 12.4
 - Node Version: 16.13.1
 - OneTable Version: 2.4.0
 - TypeScript Version: 4.6.3

**Comment by jsaundersonc** [comment]
Whoops, I see now that you're meant to use `{email} < @{emailSub}` rather than `email < @{emailSub}`

Probably better if `email < @{emailSub}` was supported though or some error thrown?

**Comment by mobsense** [comment]
We need the ${} around tokens like email because DynamoDB requires that attribute names be used where special characters and reserved words are present in the tokens. Sorry.

**Comment by jsaundersonc** [comment]
Sure, but why not attach the attribute values anyway if `valuesLen > 0`?

It was quite hard to track down where I had gone wrong, as the code was working with an update, since something else had put an entry into the names

**Comment by mobsense** [comment]
But it is more than just attaching the attribute values. You need to tokenize the where expression and remove "email" and replace with a token reference. Without the ${} we could not know what tokens to remove. You could have other fields for which "email" is a substring.

**Comment by jsaundersonc** [comment]
But technically you don't - putting `email < @{emailSub}` will still result in DynamoDB using `email` as the attribute name?

Which is what we did on an accident with the `update` operation, and it was working.

Again if there is an attribute value, why not add it or error out? Rather than silently ignore it

**Comment by jsaundersonc** [comment]
From what you're saying it sounds like using a `where` should be invalid if it doesn't contain at least one `${}` attribute name

**Comment by mobsense** [comment]
That is probably true. You would only use where to create a clause that tests attribute values in some kind of expression.
