### ISSUE TITLE
Scan COUNT results are not aggregated

### ISSUE THREAD

**Issue by tautologistics** [sensedeep/dynamodb-onetable#376]
**Describe the bug**

When passing the option `count: true` to `find()`/`scan()` the count results are not aggregated when the record set exceeds DB limits and requires paging to get all record counts. Instead, the count result of the last page is returned.

**To Reproduce**

Run any find/scan with the option `count: true` on a data set large enough that it will require paging in order count all records.

Fix provided: https://github.com/sensedeep/dynamodb-onetable/pull/375

**Comment by mobsense** [comment]
Thanks for the PR. Merged.
