### ISSUE TITLE
TypeScript errors on Model definitions with v2.5.0

### ISSUE THREAD

**Issue by rcoundon** [sensedeep/dynamodb-onetable#391]
This is possibly more of a question than a bug, or maybe a request for more information in the documentation for v2.5.0. If this isn't the correct channel for asking these kinds of questions, no problem, just point me where to ask. Thanks in advance.

I just upgraded to 2.5.0 and I'm now seeing TypeScript errors in the definition of my Models.

The model looks like this:

```ts
import { Table, Model, OneSchema } from 'dynamodb-onetable';
import Dynamo from 'dynamodb-onetable/Dynamo';
import { DynamoDBClient, DynamoDBClientConfig } from '@aws-sdk/client-dynamodb';

export class ResourceDynDb {
  public static ddb: DynamoDBClient | undefined;
  public static table: Table;
  public static ResourceTreeModel: Model<{
    resourceTree: string;
    createdDate: string;
  }>;

  private static ResourceSchema: OneSchema = {
    version: '1.0.0',
    models: {
      ResourceTreeModel: {
        PK: { type: String, value: '#ALLRESOURCES' },
        SK: { type: String, value: '#RESERVED' },
        resourceTree: { type: String, required: true },
        createdDate: { type: String, required: true },
      },
    },
    indexes: {
      primary: { hash: 'PK', sort: 'SK' },
    },
  };

  public static createDdbClient(): void {
    if (this.ddb === undefined) {
      const ddbInitParams: DynamoDBClientConfig = {
        apiVersion: '2012-08-10',
        region: process.env.REGION,
      };

      try {
        this.ddb = new DynamoDBClient(ddbInitParams);
      } catch (err) {
        const error = err as Error;
        console.error('Failed to initialise dynamodb', error);
      }
    }
  }

  public static init(): void {
    this.createDdbClient();
    const client = new Dynamo({
      client: this.ddb,
    });

    this.table = new Table({
      client,
      name: this.getTableName(),
      schema: this.ResourceSchema,
    });

    this.ResourceTreeModel = this.table.getModel('ResourceTreeModel');
  }

  public static getTableName(): string {
    return 'my-table';
  }
}

```
This causes a TypeScript error on the assignment of the result of `getModel` that looks like this:
```
TS2322: Type 'Model<Flatten<Merge<Required<any>, Optional<any>>>>' is not assignable to type 'Model<{ resourceTree: string; createdDate: string; }>'.   The types returned by 'create(...)' are incompatible between these types.     Type 'Promise<Flatten<Merge<Required<any>, Optional<any>>>>' is not assignable to type 'Promise<{ resourceTree: string; createdDate: string; }>'.       Type 'Flatten<Merge<Required<any>, Optional<any>>>' is not assignable to type '{ resourceTree: string; createdDate: string; }'.
```

Has the way this works changed in this version, if so, what is the correct way to do this?

**Comment by mobsense** [comment]
What is "DatabaseResource"?

I don't think getModel or Entity definitions changed in 2.5.

**Comment by rcoundon** [comment]
> What is "DatabaseResource"?
> 
> I don't think getModel or Entity definitions changed in 2.5.
> 
> The definition of Model.create() did change to handle generated, required and defaulted properties correctly.

I've updated the code above to be standalone and removed the model that relies DatabaseResource as I get the error with the ResourceTreeModel too and the type definition for that is included inline.

No errors with 2.4.0, if I then upgrade to 2.5.0 with no other changes, I immediately get the stated error.

**Comment by mobsense** [comment]
Try this below:

This has been modified by:

* Removed your replicated definition of ResourceTreeModel. Now all driven from the schema.
* Hoisted the schema outside the class. You may be able to get it working back inside, but a few changes are important:
- Removed the `:OneSchema`. This breaks the type inference on the models. We've not yet worked out how to make this work with the type present.
- Add "as const" to the end of the models list. This is because you need to infer a literal object to create the dynamic types.
* Changed imports (not important) just to get working from the test directory.
* Added ResourceTreeType which is the actual ResourceTree type. vs the model which is the API access object.
* Changed model definition to be: `this.ResourceTreeModel = this.table.getModel('ResourceTreeModel');`
Note: you actually don't need to type the ResourceTreeModel if only using locally as TS will infer the type from getModel()

Let me know if this helps.

Michael


```
import {Client, Dynamo, Entity, Model, Table, dump} from './utils/init'
import {OneSchema} from '../src/index.js'
import { DynamoDBClient, DynamoDBClientConfig } from '@aws-sdk/client-dynamodb';

const ResourceSchema /*: OneSchema */ = {
    version: '1.0.0',
    models: {
        ResourceTreeModel: {
            PK: { type: String, value: '#ALLRESOURCES' },
            SK: { type: String, value: '#RESERVED' },
            resourceTree: { type: String, required: true },
            createdDate: { type: String, required: true },
        },
    } as const,
    indexes: {
        primary: { hash: 'PK', sort: 'SK' },
    },
    params: {}
};

type ResourceTreeType = Entity<typeof ResourceSchema.models.ResourceTreeModel>

export class ResourceDynDb {
    public static ddb: DynamoDBClient | undefined;
    public static table: Table;
    public static ResourceTreeModel: Model<ResourceTreeType>

    public static init(): void {
        this.createDdbClient();
        const client = new Dynamo({ client: this.ddb, });
        this.table = new Table({
            client,
            name: this.getTableName(),
            schema: ResourceSchema,
        });
        this.ResourceTreeModel = this.table.getModel('ResourceTreeModel');
    }

    public static createDdbClient(): void {
        if (this.ddb === undefined) {
            const ddbInitParams: DynamoDBClientConfig = { apiVersion: '2012-08-10', region: process.env.REGION, };
            try {
                this.ddb = new DynamoDBClient(ddbInitParams);
            } catch (err) {
                const error = err as Error;
                console.error('Failed to initialise dynamodb', error);
            }
        }
    }

    public static getTableName(): string {
        return 'my-table';
    }
}

```

**Comment by rcoundon** [comment]
Thank you for taking the time to put this together, this makes more sense now and using the schema as the source of truth for the types is a definite improvement on what I had. I see no compilation errors now, interestingly, I didn't need the `as const` to allow it to compile.
I haven't run the code yet but I'm not expecting any changes to runtime behaviour but will check and report back.

**Comment by mobsense** [comment]
Cool.

The "as const" is important for VS Code intellisense.

**Comment by rcoundon** [comment]
All looks good at runtime too, thanks again
