### ISSUE TITLE
Request: Example Project

### ISSUE THREAD

**Issue by allumbra** [sensedeep/dynamodb-onetable#40]
I'm finding the docs a bit difficult to consume - especially since they are dispersed among 3 projects and blog posts.  I think a complete working example to download and play with would help a lot.

**Comment by mobsense** [comment]
Thanks for the prompting. We're on it and are preparing such an example. Should be posted later this week.

**Comment by mobsense** [comment]
Sorry for the delay, still working on this.

**Comment by mobsense** [comment]
Got the first sample checked in as samples/crud.  This is basic CRUD using Javascript + AWS SDK3.

Working on a typescript one now.

Please speak up for what features you'd like covered in a sample.

**Comment by allumbra** [comment]
Thanks!  I got a "hello world" done yesterday prior to you releasing this based on notes I found in "Discussions" But I think that's super helpful.  At this point, the only other example that I can think of is using the Migration.  I'll keep plugging away and let you know if I think if anything else.
