### ISSUE TITLE
Documentation for OneField.encode is incorrect

### ISSUE THREAD

**Issue by erik-dreamteam** [sensedeep/dynamodb-onetable#404]
**Describe the bug**

https://doc.onetable.io/api/table/schemas/attributes/
lists the property as `encoding` however in other places in the docs it's listed as `encode`

**To Reproduce**

One https://doc.onetable.io/api/table/schemas/attributes/ and look at the table
vs
https://github.com/sensedeep/dynamodb-onetable/blob/main/src/Model.d.ts#L40
**Cut/Paste**
encoding | array | Define how an attribute is encoded in a value template.

**Expected behavior**
should be listed as `encode`

**Screenshots**
![Screen Shot 2022-10-20 at 11 08 07 AM](https://user-images.githubusercontent.com/113385979/197025286-4a488408-96ab-48f7-b95f-653c75cfe06c.png)

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mobsense** [comment]
Thanks - fixed.
