### ISSUE TITLE
[BUG]: calling .next() throws a ValidationException

### ISSUE THREAD

**Issue by demsey2** [sensedeep/dynamodb-onetable#44]
**Describe the bug**
when I fetch some data and got back a LastEvaluatedKey from DynamoDB, then when I call
```
await results.next();
```
I got ValidationException: The provided key element does not match the schema

in Model.js line 376 we have
```
params = Object.assign({}, params, {start: result.LastEvaluatedKey})
```
when I change that to 
```
params = Object.assign({}, params, { start: items.start });
```
that works fine

**Expected behavior**
calling .next() should not throw an exception

**Environment (please complete the following information):**
 - MacOS
 - Node 14

**Comment by mobsense** [comment]
Perfect, thank you.  Yes, the data needs to be unmarshalled and items.start holds that value.

**Comment by mobsense** [comment]
NPM and GitHub updated in 1.4.4
