### ISSUE TITLE
TypeError:    updateTable is not a function

### ISSUE THREAD

**Issue by projaguar** [sensedeep/dynamodb-onetable#441]
● One Repository › update table

    TypeError: this.service.updateTable is not a function

      134 |
      135 |   async updateTable(params: any) {
    > 136 |     const res = await this.table.updateTable(params);
          |                                  ^
      137 |     Logger.verbose(res, 'Table Updated');
      138 |   }
      139 | }

      at Table.<anonymous> (node_modules/dynamodb-onetable/dist/cjs/Table.js:481:43)
      at node_modules/dynamodb-onetable/dist/cjs/Table.js:13:71
      at Object.<anonymous>.__awaiter (node_modules/dynamodb-onetable/dist/cjs/Table.js:9:12)
      at Table.updateTable (node_modules/dynamodb-onetable/dist/cjs/Table.js:395:16)
      at OneRepositoryImple.updateTable (packages/backend/dynamodb/src/one.repository.ts:136:34)
      at Object.<anonymous> (packages/backend/dynamodb/src/one.repository.spec.ts:30:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 7 skipped, 8 total
Snapshots:   0 total
Time:        2.166 s

other table method works well
It seem to be missing a typescript definition.

sample.spec.ts  -----------------------------------------------------------------------------------

```
import Dynamo from 'dynamodb-onetable/Dynamo';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { Table } from 'dynamodb-onetable';

describe('One Table Test', () => {
  let table;

  beforeEach(() => {
    process.env.AWS_ACCESS_KEY_ID = 'sample';
    process.env.AWS_SECRET_ACCESS_KEY = 'sample';
    process.env.AWS_REGION = 'local';

    const client = new Dynamo({
      client: new DynamoDBClient({
        endpoint: 'http://localhost:8000',
      }),
    });

    table = new Table({
      client,
      name: 'sample',
      schema: {
        indexes: {
          primary: { hash: 'pk', sort: 'sk' },
          gsi1: { hash: 'sk', sort: 'pk' },
        },
        models: {
          Account: {
            pk: { type: String, value: 'account#${name}' },
            sk: { type: String, value: 'account#' },
            name: { type: String, required: true },
          },
        },
        version: '0.1.0',
        format: 'onetable:1.0.0',
      },
      partial: true,
    });
  });

  it('should be defined', () => {
    expect(table).toBeDefined();
  });

  it('create table', async () => {
    const res = await table.createTable();
    console.log('create table successed', res);
  });

  it('update table', async () => {
    const res = await table.updateTable({
      remove: {
        name: 'gsi1',
      },
    });
    console.log('update table successed', res);
  });

  it('delete table', async () => {
    const res = await table.deleteTable('DeleteTableForever');
    console.log('delete table successed', res);
  });
});

```

**Comment by dev-embedthis** [comment]
Should be there and there is a typescript definition.

Can you please submit a debug.ts test case as per the template.

**Comment by projaguar** [comment]
> Should be there and there is a typescript definition.
> 
> Can you please submit a debug.ts test case as per the template.

Uploaded the sample code.

**Comment by dev-embedthis** [comment]
Ah, that is down in the DynamoDB layer for the V3 SDK only.

**Comment by projaguar** [comment]
Thank you ~~~~~~ !
