### ISSUE TITLE
Idea: return ConsumedCapacity 'stats' for Write operations

### ISSUE THREAD

**Issue by andrew-permiso** [sensedeep/dynamodb-onetable#444]
Hey team!

# Summary

I'm optimizing Dynamo writes for a write-heavy workload, and I wanted to make a case for adding support for WriteUnits to the `stats` API parameter. The OneTable documentation ([stats param)](https://doc.onetable.io/api/model/params/#stats) suggests this is only for `find/query/scan` operations for now, and it would be great to have it for Write operations (e.g. DeleteItem, PutItem, UpdateItem, BatchWriteItem).

# Motivation

Why this may be helpful to others:

- Writes cost more than reads, per unit
- Write Units may not be intuitive, especially for deletions or update expressions
  - Writing a 1 character field writes the whole entry (ie 1 byte may cause > 1 WCU write)
  - Indexes affect overall write usage
- Estimations are helpful, but not as precise as empirical measurements with AWS counts
 
Or if someone can guide me to the place in the codebase where the change should be made, and it's quick enough, maybe I/someone else can find some time to submit a Pull Request.

# Code Sample

Example Output with ConsumedCapacity when calling DeleteItem and PutItem:
```Typescript
/** Output via raw Dynamo lib, of the code snippet below:
 * Starting: dynamoWriteExperiments.ts
 * Deletion: { ConsumedCapacity: { TableName: 'example', CapacityUnits: 2 } }
 * Creation { ConsumedCapacity: { TableName: 'example', CapacityUnits: 2 } }
 */
```

Code sample using underlying AWS SDK:
```Typescript
import DynamoDB from "aws-sdk/clients/dynamodb";

const dynamodb = new DynamoDB({ region: "us-east-1" });
const table = "example";
const keys = { pk: { S: "pk1" }, sk: { S: "sk1" } };

const createParams = {
  Item: {
    ...keys,
    str: { S: new Array(2_000).join("0") }, // Generate 2k string of 0's
  },
  ReturnConsumedCapacity: "TOTAL",
  TableName: table,
};

// Deletion returns write units
const deletion = await dynamodb.deleteItem({
  Key: keys,
  ReturnConsumedCapacity: "TOTAL",
  TableName: table,
}).promise();
console.log("Deletion:", deletion);

// PutItem returns write units
const creation = await dynamodb.putItem(createParams).promise();
console.log("Creation", creation);
```

**Comment by mobsense** [comment]
Thank you. That is actually an easy fix.

Will apply.

**Comment by andrew-permiso** [comment]
Awesome, thanks @mobsense!
