### ISSUE TITLE
Hard-dependency on "aws-sdk"

### ISSUE THREAD

**Issue by Haringat** [sensedeep/dynamodb-onetable#446]
`src/Table.js` got a broken hard-depency on "aws-sdk" in `cc20894`. This breaks a lot of code as the import does not have a file extension and is thus defunct. Furthermore, aws-sdk is still only listed as devDependency rather than dependency.
This breaks the entire library ATM.

**To Reproduce**

https://gist.github.com/Haringat/d0b6ec9d958ad035bc14ed7d2c74d58d

1. Install current version of dynamodb-onetable.
2. import dynamodb-onetable in your javascript/typescript file.

**Comment by dev-embedthis** [comment]
Fixed in 2.6.1
