### ISSUE TITLE
Access to builtin fields (e.g. created) in typesafe way 

### ISSUE THREAD

**Issue by sweepy84** [sensedeep/dynamodb-onetable#449]
**Describe the bug**

Using Typescript I expect the builtin attributes like created, updated to be returned with the created type here:

```
export type ProjectType = Entity<typeof ProjectSchema.models.Project>

export const ProjectModel = table.getModel<ProjectType>('Project')
```

**To Reproduce**

Create any standard model as per documentation with any attributes.

**Expected behavior**
Expect the type above to include the builtin fields created and updated etc.
If this is not possible how would i go about including say the created field?

Do i just add `createField: 'created'` and add ` created: { type: Date, required: true }` to the model schema? But if i do that when creating an item I'm obliged to provide the created date - i don't want to have to provide that. I just want a way to be able to in a typesafe way use the created field that is builtin.

**Environment (please complete the following information):**
 - MacOX
 - Nodejs18.x
 - onetable 2.,5.1

**Comment by dev-embedthis** [comment]
The builtin attributes can be declared in your schema if you need them in your TS definitions.

There isn't a way to introduce them auto-magically like we do for defined attributes.

**Comment by AlexStansfield** [comment]
The key thing here is not to set the field `required` and everything will be fine.

so just define the field:
```
  created: {
    type: Date 
  }
```

The date time will be automatically set when saving the item and it will be returned in the model

**Comment by sweepy84** [comment]
ok thanks @dev-embedthis and @AlexStansfield !

automagically would be great since they're built-in

**Comment by dev-embedthis** [comment]
One last tip.

If you need to override timestamps with an explicit update. Set params.timestamps == false. Then provide an explicit update value in the update properties. That disables the auto-generated created/updated values.
