### ISSUE TITLE
How to do a paginated scan/query?

### ISSUE THREAD

**Issue by tqhoughton** [sensedeep/dynamodb-onetable#452]
I'm using oneTable as part of a GraphQL API and I'm trying to figure out how to set up a paginated query, however I cannot for the life of me figure out what option I need to be passing in to get the base functionality of using the `ExclusiveStartKey` and `LastEvaluatedKey` in the raw Dynamo SDKs

I have the following code:

```ts
const findOptions: OneParams = {
    index: "by_createdAtYear_createdAtDateAndSlug",
    limit,
    reverse: options.order === Order.OldToNew,
    ...options.after && { next: JSON.parse(options.after) },
    log: true
  };

  const postsPage = await Post.model.scan({},
    findOptions
  );
```

where `options.after` is the `next` value of a previous scan.

However, when I pass in `next` like this I get an error from Dynamo saying that I'm trying to pass in an undefined value in a map, set or list. I found a blog post that suggested I use the `start` option instead, however that appears to set the scan start position AT that item and not use it as an `ExclusiveStartKey`:

```ts
const findOptions: OneParams = {
    index: "by_createdAtYear_createdAtDateAndSlug",
    limit,
    reverse: options.order === Order.OldToNew,
    ...options.after && { start: JSON.parse(options.after) },
    log: true
  };

  const postsPage = await Post.model.scan({},
    findOptions
  ); // returns the same item as in pass when using limit: 1
```

Any idea what I'm doing wrong or docs that explain how to do pagination?

**Comment by tqhoughton** [comment]
I have since realized that using `reverse` is not possible with scans so I have modified my table to support a query, however I am running into the same issue after refactoring to use a query/find:
```ts
const findOptions: OneParams = {
    index: "by_authorUserId_createdAtDateAndSlug",
    limit,
    reverse: options.order === Order.OldToNew,
    ...options.after && { start: JSON.parse(options.after) },
    log: true,
    maxPages: 1
  };

  const postsPage = await Post.model.find({
    authorUserId: userId
  }, findOptions) // returns same next no matter what gets passed in
```

**Comment by dev-embedthis** [comment]
Next / prev should work without exceptions.

Can you please do 2 things:

* Use log: true to see the actual DynamoDB request
* Simplify your params replacing ...options with a literal. It would help to see the actual params passes.

Also, a debug.ts test case that reproduces the issue.
