### ISSUE TITLE
ExpressionAttributeName unnecessarily wrapped in another ExpressionAttributeName

### ISSUE THREAD

**Issue by c-st** [sensedeep/dynamodb-onetable#455]
**Describe the bug**

When using ExpressionAttributeNames inside the param `set`, variables prefixed with `#` are wrapped in another ExpressionAttributeName instead of letting DynamoDB handle the value evaluation.

We have a use-case where we want to atomically add or remove entries in a map based on their key. To avoid multiple entries to be added (with the same key) and to not overwrite existing values we would like to use an UpdateExpression with `attribute_not_exists`.

Example item:

```json
{
  "pk": "my-entity#123",
  "sk": "none",
  "_type": "MyEntity",
  "openIssues": {
    "TOPIC_A": "123456",
    "TOPIC_B": "678901"
  }
}
```

Please note that the keys inside the `openIssues` are dynamic. 

**To Reproduce**

We have the following schema and API usage to implement our use-case:

```typescript
const Schema = {
  version: "0.0.1",
  indexes: {
    primary: { hash: "pk", sort: "sk" },
  },
  models: {
    MyEntity: {
      pk: { type: String, value: "my-entity#${id}" },
      sk: { type: String, value: "none" },
      id: { type: String, required: true },
      openIssues: { type: Object, default: {} }, // dynamic schema
    },
  },
} as const;

export class IssueRepository {
  private client = new Dynamo({
    client: this.dynamoDbClient,
  });

  private table = new Table({
    client: this.client,
    name: this.tableName,
    schema: Schema,
    partial: true,
    logger: true,
  });

  private Model = this.table.getModel("MyEntity");

  public constructor(
    private dynamoDbClient: DynamoDB,
    private tableName: string = config.dynamoDbTableName
  ) {}

  public addIssue = async (
    id: string,
    issueName: string,
    issueId: string
  ): Promise<void> => {
    await this.Model.update(
      {
        id,
      },
      {
        where: "attribute_not_exists(openIssues.#issueName)",
        set: {
          [`openIssues.${issueName}`]: "@{issueId}",
        },
        postFormat: (_model, cmd: any) => {
          cmd.ExpressionAttributeNames["#issueName"] = issueName;
          return cmd;
        },
        substitutions: {
          issueId,
        },
        throw: true,
        log: true,
      }
    );
  };
}
```

This results in the following DynamoDB operation:

```json
{
  "trace": {
    "model": "MyEntity",
    "cmd": {
        "ConditionExpression": "(attribute_exists(#_0)) and (attribute_exists(#_1)) and (attribute_not_exists(openIssues.#issueName))",
        "ExpressionAttributeNames": {
            "#_0": "pk",
            "#_1": "sk",
            "#_2": "openIssues",
            "#_3": "TOPIC_C",
            "#_4": "id",
            "#issueName": "TOPIC_C"
        },
        "ExpressionAttributeValues": {
            ":_0": {
                "S": "678901"
            },
            ":_1": {
                "S": "123"
            }
        },
        "TableName": "dynamodb",
        "ReturnValues": "ALL_NEW",
        "UpdateExpression": "set #_2.#_3 = :_0, #_4 = :_1",
        "Key": {
            "pk": {
                "S": "my-entity#123"
            },
            "sk": {
                "S": "none"
            }
        }
    },
    "op": "update",
    "properties": {
        "pk": "my-entity#123",
        "sk": "none",
        "id": "123",
        "_type": "MyEntity"
    }
  }
}
```

**Expected behavior**

Using the API this way we got it working. However we are not sure if the usage of the `set` object is correct because we're running into issues with replacing variables in the object key.

To make it work we had to use a string template and inject the variable directly:

```typescript
set: { [`openIssues.${issueName}`]: "@{issueId}" },
```

This is however not the way we're expecting it to work and could potentially cause issues based on the value of `issueName` (for example if it contains a `.`).

We'd rather expect to use a DynamoDB expression attribute name (the one we have added in `postFormat`) but the template evaluation fails in this case:

```typescript
set: { [`openIssues.#issueName`]: "@{issueId}" },
```

This resulted in the following command being executed:

```json
{
  "cmd": {
    "ConditionExpression": "(attribute_exists(#_0)) and (attribute_exists(#_1)) and (attribute_not_exists(openIssues.#issueName))",
    "ExpressionAttributeNames": {
        "#_0": "pk",
        "#_1": "sk",
        "#_2": "openIssues",
        "#_3": "#issueName",
        "#_4": "id",
        "#issueName": "TOPIC_C"
    },
    "ExpressionAttributeValues": {
        ":_0": {
            "S": "678901"
        },
        ":_1": {
            "S": "123"
        }
    },
    "TableName": "dynamodb",
    "ReturnValues": "ALL_NEW",
    "UpdateExpression": "set #_2.#_3 = :_0, #_4 = :_1",
    "Key": {
        "pk": {
            "S": "my-entity#123"
        },
        "sk": {
            "S": "none"
        }
    }
  },
  "items": [
      {
          "id": "123",
          "openIssues": {
              "#issueName": "678901"
          }
      }
  ],
  "op": "update",
  "properties": {
      "pk": "my-entity#123",
      "sk": "none",
      "id": "123",
      "_type": "MyEntity"
  },
  "params": {
      "exists": true,
      "parse": true,
      "high": true,
      "where": "attribute_not_exists(openIssues.#issueName)",
      "set": {
          "openIssues.#issueName": "@{issueId}"
      },
      "substitutions": {
          "issueId": "678901"
      },
      "throw": true,
      "log": true,
      "checked": true
  }
}
```

Instead of letting DynamoDB evaluate `#issueName` with the value provided, it wraps it into another ExpressionAttributeName (`#_3`) with the value `#issueName`. This results in the item having an ExpressionAttributeName as a key:

```json
{
  "id": "123",
  "openIssues": {
    "#issueName": "678901"
  }
}
```

Is this a bug? Or are we using it wrong? We're also open for alternative suggestions for implementing our use-case.

**Comment by dev-embedthis** [comment]
You are certainly stretching the API!

Some comments:

* With partial, we would tend to not use set. i.e.

await update({id, openIssues: { [issueName]: issueId })

The beauty of partial is that whatever properties you provide are updated and only those are updated.

Caveat:  The parent must exist

* Partial == true is now the default

If you do this, you may not need your own expression attribute name except for the test on exists.

Also, if you can make your API idempotent such that updating an existing item does not matter, it greatly simplifies things.

* If you do need to use postFormat, probably simplest to not use @substitutions and just use literal values provided in your Javascript string template.

Please push back if I've mis-understood your use-case.
