### ISSUE TITLE
Improve typing of array items

### ISSUE THREAD

**Issue by LouisPinsard** [sensedeep/dynamodb-onetable#466]
Hello!

When defining an the schema of the items of an array, the enum property is not correctly taken into account. For instance, for this schema:

```
 {
            pk: {type: 'string', value: '${_type}#'},
            sk: {type: 'string', value: '${_type}#${id}'},

            gs1pk: {type: 'string', value: '${_type}#'},
            gs1sk: {type: 'string', value: '${_type}#${id}'},
            arrayProperty: {
                        type: Array,
                        items: {type: String, enum: ['enumValue1', 'enumValue2'},
            },
            name: {type: 'string'},
            email: {type: 'string'},
            id: {type: 'string', generate: 'ulid'},
        },
    } as const,
```

the return type of the methods on this model would contain: `arrayProperty: string[]` instead of `arrayProperty: 'enumValue1' | 'enumValue2' []`

I wonder if there is a reason not to use EntityField instead of EntityFieldFromType in the following code of Model.d.ts which seems to fix the issue:

```
type ArrayItemType<T extends OneField> = T extends {items: OneField} ? EntityFieldFromType<T['items']> : any
```

wdyt? happy to help if I can!

**Comment by mobsense** [comment]
Same comment again as with your other great suggestions.

Thank you, really appreciated.

**Comment by mobsense** [comment]
See discussion poll at #471
