### ISSUE TITLE
Typing information not available with moduleResolution: nodenext

### ISSUE THREAD

**Issue by RalphSleigh** [sensedeep/dynamodb-onetable#467]
Its possible I am misunderstanding something, or this setup is unsupported in which case feel free to close. 

My environment is all esm:

`"dynamodb-onetable": "2.6.2",`
Typescript v5 with `"moduleResolution": "nodenext"`
package.json with `"type": "module"`

The issue is I have is no typing information available for imports. So if we e.g:

`import { Table, Entity } from 'dynamodb-onetable'`

The type of Entity is just `import Entity`. 

Typescipt can see into:

`node_modules\dynamodb-onetable\dist\mjs\index.d.ts`

But the imports inside that are all broken as:

`A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './Table.js' instead?ts(2846)`

Adding `import type` I get:

`Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './Table.js'?ts(2835)`

I can fix this by adding the .d.ts extensions to the imports manually, or changing my `moduleResolution` back to `node`.

**Comment by mobsense** [comment]
Which lines did you need to change in which files (adding .d.ts). I'd like to check if this change works for moduleResolution "node". i.e. can we safely make that change for all?

**Comment by mobsense** [comment]
The solution may be to update the package.json exports types:

```
    "exports": {
        ".": {
            "import": "./dist/mjs/index.js",
            "require": "./dist/cjs/index.js",
            "types": "./dist/mjs/index.d.ts"
        },
        "./Dynamo": {
            "import": "./dist/mjs/Dynamo.js",
            "require": "./dist/cjs/Dynamo.js",
            "types": "./dist/mjs/Dynamo.d.ts"
        }
}
```

**Comment by frmrm** [comment]
These are my current tsc compiler options if it's helpful:

```
    "target": "es2022",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "module": "es2022",                                /* Specify what module code is generated. */
    "moduleResolution": "Node16",
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true,                                /* Skip type checking all .d.ts files. */
```

**Comment by mobsense** [comment]
Can you mock up a simple repo that demonstrates the issue.

We use the following with a pure TS app fine.

```
        "moduleResolution": "nodenext",
         "lib": ["esnext"],
        "module": "esnext",
        "target": "esnext"
```
