### ISSUE TITLE
model.upsert({ ...data }) returns a data with encrypted values

### ISSUE THREAD

**Issue by valdestron** [sensedeep/dynamodb-onetable#491]
**Describe the bug**

Using model.upsert({...})
1. upserts some stringified json field value flagged with crypt:true 

model schema like this:
```
const ASchema = {
  id: { type: String, generate: 'ulid', validate: Match.ulid },
  org_id: { type: String },
  account_id: { type: String, unique: true, required: true },
  name: { type: String, required: true, crypt: true },
  email: { type: String, required: true, crypt: true },
  active: { type: Boolean, default: true },
  description: { type: String, required: true, crypt: true },
  environment: {
    type: String,
    enum: Object.keys(XXX2),
    required: true,
  },
  subtype: { type: String, enum: Object.keys(XXXX3), required: true },
  type: { type: String, enum: Object.keys(XXXX4), required: true },
  xx1: { type: String, required: true },
  xxv1: {
    type: String,
    required: true,
    crypt: true,
  },
  xxv2: {
    type: String,
    required: true,
    crypt: true,
  },
  xxgSec: {
    type: String,
    crypt: true,
  },
} as const
```

Before upserting, the data has correct values JSON strings on xxv1, xxv2 etc... fields.

After upsert I get a result from model.upsert with encrypted fields. 

model.create works as expected.
model.update also returns encrypted strings on those fields

What is more, if I then try to retrieve this model using model.find, i will retrieve encrypted string inside those fields also, so means that the upsert/update methods encrypts a string two times and the value is encrypted string in the schema model.

**Comment by mobsense** [comment]
Can you create a minimal debug.ts as outlined in the template so we can reproduce your issue.

**Comment by mobsense** [comment]
Closing for now. Feel free to reopen with a debug.ts
