### ISSUE TITLE
Need release to resolve Typescript ESM Resolution issues

### ISSUE THREAD

**Issue by frmrm** [sensedeep/dynamodb-onetable#492]
**Describe the bug**

There is an outstanding issue with types when using ESM resolution ( #467 ) that has not been fixed in a tagged release. It appears to be present on the 2.6.4 tag, but that tag hasn't been released on npm, meaning we have to depend directly on the git repository to 

**To Reproduce**

Try to use opentable 2.6.3 with ESM resolution and see that types are all reported as `any`

**Cut/Paste**

N/A

**Expected behavior**

We need a release that includes the fix for #467 on npm!

**Screenshots**

N/A

**Environment (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by frmrm** [comment]
Actually, I stand corrected. Those additional exports don't solve my problem. I'm still seeing everything as `any` - I think we need to reopen #467 - this doesn't appear to be solved.

**Comment by mobsense** [comment]
We're using ESM resolution with some packages fine. So we'd need a test repo to see what you are doing differently that is not working.
