### ISSUE TITLE
Cannot resolve type when ESM

### ISSUE THREAD

**Issue by yamatatsu** [sensedeep/dynamodb-onetable#506]
**Describe the bug**

When using Native ESM following [TypeScript Official Blog](https://www.typescriptlang.org/docs/handbook/esm-node.html), Onetable cannot resolve type(e.g. `Table`, `OneSchema` and `Entity`).

When cjs:
<img width="967" alt="image" src="https://github.com/sensedeep/dynamodb-onetable/assets/11013683/cbe2034c-b280-4580-8637-45156825a647">

When esm:
<img width="188" alt="image" src="https://github.com/sensedeep/dynamodb-onetable/assets/11013683/cfd48ece-c496-4665-a57b-28ee234a40d6">

**To Reproduce**

https://github.com/yamatatsu/reproduction-onetable-unresolve-type

1. Clone this repository.
2. `npm i`.
3. Open `./debug.ts` and you can see no error on `schema.foo.bar`.
4. And it will be error when remove `"type": "module",` from `package.json`.

**Environment (please complete the following information):**
 - OS: macOS 14.0
 - Node Version: v18.18.0
 - OneTable Version: 2.7.1
 - TypeScript Version: 5.2.2
 - Any other relevant environment information: nothing

**Additional context**

I found some solutions:

1. Add `.js` to all imports in `*.d.ts` following [Official Documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions:~:text=This%20code%20works%20in%20CommonJS%20modules%2C%20but%20will%20fail%20in%20ES%20modules%20because%20relative%20import%20paths%20need%20to%20use%20extensions.%20As%20a%20result%2C%20it%20will%20have%20to%20be%20rewritten%20to%20use%20the%20extension%20of%20the%20output%20of%20foo.ts%20%2D%20so%20bar.ts%20will%20instead%20have%20to%20import%20from%20./foo.js.).
2. I don't know why but it resolve this issue to replace `dist/mjs/index.d.ts` to `dist/cjs/index.d.ts` at [`package.json#L7`](https://github.com/sensedeep/dynamodb-onetable/blob/main/package.json#L7) and remove `exports:` from `package.json`.  
   It probably also resolve to separate directories to `mjs` and `types` same as any other libraries such as [`@aws-sdk/client-dynamodb`](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-dynamodb/package.json#L17-L19).

**Comment by mobsense** [comment]
Thank you for the reproduction repo.

**Comment by dbain-texada** [comment]
Any updates on this?
