### ISSUE TITLE
Create method does not create the sort key if one attribute is undefined

### ISSUE THREAD

**Issue by clemzangrilli** [sensedeep/dynamodb-onetable#514]
Hello, I have a problem when I try to create an item with an undefined value used for the sort key of my GSI. 

**Describe the bug**
1. I have a schema of a simple item, with one primary key (pk + sk) and one gsi (gs1pk and gs1sk). 
```
Item: {
      pk: {
        type: String,
        value: 'resource#${id}',
      },
      sk: { value: 'resource#', type: String },

      gs1pk: { value: 'resource#${siteId}', type: String },
      gs1sk: {
        value: 'resource#${externalId}',
        type: String,
      },

      id: { type: String, required: true },
      siteId: { type: String, required: true },
      externalId: { type: String },
    },
```
2. I want to create some items without an externalId, but I still want to be able to find them using the primary key of the GSI (gs1pk).
```
const item = await TABLE.create({id: 'id', 'siteId': 'siteId'});
```

3. The item is created with all its attributes, except for the sort key of the gsi (gs1sk). 
--> When I attempt to find items with gs1pk, none is found via the aws console.
--> The item is in dynamodb, but the gs1sk is not defined. Dynamodb does not seem to like it when querying with the gs1pk. 
--> I expected to find a gs1sk with a value like "resource#". If I manually update the gs1sk with this value, everything works fine.

**Summary**
When I attemptto create an item with gs1sk = resource#{nullValue}, the item is created, but gs1sk is absent. A query on the gs1pk does not retrieve the elements, likely because dynamodb does not expect a null value for a sort key (of a gsi here).

Is it normal ? Do we have an option to activate or else ?

**Workaround**
I can manually specify the gs1sk during the creation, like this :
```
const item = await TABLE.create({...itemToCreate, gs1sk: 'resource#'});
```

But all already created items would not be impacted, so I would need to manually update all items with gs1sk = resource#. 

Thank you for your help.

**Comment by mobsense** [comment]
Can you run with logging enabled so we can see the actual query being run.

I think if a template is incomplete - i.e. component fields are not provided, then the field is not supplied.

You could set the externalId to "" and that will probably work.

**Comment by clemzangrilli** [comment]
Thank you for your response. Yes, it works if I manually set the 'externalId' to "". 

I think you are right, and this is inherent to dynamodb : 

> A global secondary index only tracks data items where its key attributes actually exist ([doc aws](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html)).

--> However, I would like to be able to query all my items with the gs1pk, i.e. my 'siteId' property. Do you have a recommendation in this case ? 

Possibility n°1 : Create another gsi with 'siteId' only and no gsk.

Possibility n°2 : Manually set externalId to "" at each creation. How do we do for existing items ? Update on all items to set 'externalId' to "" ? 

**Log of the request whithout externalId, gs1sk not provided**
```
{
  "cmd": {
      "ConditionExpression": "(attribute_not_exists(#_0)) and (attribute_not_exists(#_1))",
      "ExpressionAttributeNames": {
          "#_0": "pk",
          "#_1": "sk"
      },
      "TableName": "clementdev-ckl-project-service-dynamodb-table",
      "Item": {
          "pk": {
              "S": "resource#7fdfac2e-63f6-4456-8d39-2c58e0c5bc7d"
          },
          "sk": {
              "S": "resource#"
          },
          "gs1pk": {
              "S": "resource#14ae59fe-2783-4501-912b-85bba7507921"
          },
          "id": {
              "S": "7fdfac2e-63f6-4456-8d39-2c58e0c5bc7d"
          },
          "siteId": {
              "S": "14ae59fe-2783-4501-912b-85bba7507921"
          },
          "_type": {
              "S": "Resource"
          }
      },
      "ReturnValues": "NONE"
  },
  "items": [
      {
          "id": "7fdfac2e-63f6-4456-8d39-2c58e0c5bc7d",
          "siteId": "14ae59fe-2783-4501-912b-85bba7507921",
      }
  ],
  "op": "put",
  "properties": {
      "pk": "resource#7fdfac2e-63f6-4456-8d39-2c58e0c5bc7d",
      "sk": "resource#",
      "gs1pk": "resource#14ae59fe-2783-4501-912b-85bba7507921",
      "id": "7fdfac2e-63f6-4456-8d39-2c58e0c5bc7d",
      "siteId": "14ae59fe-2783-4501-912b-85bba7507921",
      "_type": "Resource"
  },
  "params": {
      "parse": true,
      "high": true,
      "exists": false,
      "log": true,
      "checked": true
  }
}
```

**Comment by mobsense** [comment]
If you do a "find" / query and supply only the GSI PK, you will get all the items with that PK. 

You can update items and provide the empty string externalId, that will then create the GSI item.

This is a facet of both OneTable and DyanmoDB. DynamoDb will create the item in the GSI only when complete keys are provided. OneTable will not provide a partial GSI SK. You must provide all the key components to create/update a GSI item. i.e. there must be a unique key to identify the item. When doing a find/query, you can provide only the GSI PK and it will return all matching items.

**Comment by clemzangrilli** [comment]
That confirms what I thought. It would be great to have a warning from the library when the developer is in this scenario, because it can be a significant problem when they find out that the GSI is not updated because due to a null value. 

Thank you again for your help.
