### ISSUE TITLE
Support for Mapped Types

### ISSUE THREAD

**Issue by jshear** [sensedeep/dynamodb-onetable#516]
I have come across several instances where it would be most intuitive to use a mapped type within my DynamoDB modeling. For example, consider a situation where you need to track an object where the keys are usernames and the values are the number of friends they have. This object might look like this:

```json
{
    "userA": 5,
    "userB": 2,
    "userC": 6
}
```

We do not know the usernames of all users at the time of application development, making this impossible to model with a traditional Object schema. Because of this, I often find myself declaring the Object type in my models without a schema, which defeats the purpose of the modeling. It would be very beneficial to have type safety for mapped types for situations like this. The model declaration could use a keyword like `values` that defines the schema for every value in the object. Keys must be strings, but all keys will be included and have the value type enforced. Such a model might look like this:

```js
{
    friends: {
        type: Object,
        values: {
            type: Number
        }
    }
}
```

A more complex example might have Object values to track user information, like this:

```js
{
    users: {
        type: Object,
        values: {
            type: Object,
            schema: {
                friends: { type: Number },
                address: { type: String }
            }
        }
    }
}
```

This model would support an object with the format:
```json
{
    "anyUsername": {
        "friends": 5,
        "address": "123 Some Road"
    },
    "anyOtherUsername": {
        "friends": 2,
        "address": "456 House Lane"
    }
}
```
Is there any current support for enforcing mapped types? If not, are there any arguments against it? I could try to work on a solution myself if it has the support of the team.

**Comment by mobsense** [comment]
Thank you for the suggestion. Please feel free to try to prototype something. A caution is that the TS magic is somewhat brittle. But if you can find a clean solution with low risks to existing code, that would be great.

**Comment by martinmicunda** [comment]
@mobsense is this supported as I have similer requirement? It seems `one-table` doesn't support Mapped Type

**Comment by jshear** [comment]
@martinmicunda Unfortunately my priorities shifted and I haven't had a chance to work on this myself, so I'm assuming it's not supported yet. I still think it would be a very valuable feature and if I'm ever fortunate enough to have some spare time I'll try to work on it, but I don't see that happening in the near future.
