### ISSUE TITLE
OneSchema type for getCurrentSchema() not set

### ISSUE THREAD

**Issue by kinesra75** [sensedeep/dynamodb-onetable#518]
Hi,

I think there is a missing type for getCurrentSchema() in table.d.ts line 110 it should be something like getCurrentSchema(): OneSchema

If not we can't deconstruct the object.

Thanks !

**Comment by mobsense** [comment]
Added:

    getCurrentSchema(): OneSchema | null

**Comment by kinesra75** [comment]
Thank you !
