### ISSUE TITLE
OnUpdate features in Model schema

### ISSUE THREAD

**Issue by tommy921092** [sensedeep/dynamodb-onetable#52]
Wondering if there's the on update feature: Forces default values to be passed on every update.
as in dynamodb-toolbox its provided with such feature.
Coz I'm recently working on the project using dynamodb-toolbox but it seems not to provide cli for db migration & auto id generation, log emit, validate etc which I found in dynamodb-onetable so Im considering a change of dynamodb library.

**Comment by mobsense** [comment]
Can you describe that in more detail?

Do you mean values that use "default: value" in the schema?

OneTable uses a default value on create and when reading an item for which the value has not yet been defined. But not for update, as the value should be already defined by either a default value, or the caller providing a non-default value.  Can you explain why, and what constraints would an update use the default value?

Is your need when the schema default value changes, so you want to force an update?

**Comment by tommy921092** [comment]
For me, it is mainly used for updating gsi. For example I can define a gsi with sort key as: name#status#date
and it is possible that the status/name attribute may change some time. As I worked with dynamodb-toolbox, it is provided with such feature, which allow me to update the status & name, and it will automatically also update the related gsi sort key e.g. with default=(data)=>`${data.name}#${data.status}`
<img width="966" alt="Screenshot 2021-06-19 at 12 10 11 AM" src="https://user-images.githubusercontent.com/41218788/122589341-b8d98d80-d092-11eb-9251-fa21fe218cc8.png">

**Comment by mobsense** [comment]
So what OneTable calls `value templates`, toolbox calls `default` values.  We use default to mean:  if the property is null, use the default value.

Our value templates function similarly:

```
value: '${name}#${status}
```

OneTable will calculate default values on every update currently. So I think OneTable operates already the way you want, provided you pass the name and status properties in the update. If you omit any ingredient property for a value template, the value template will not be used.

I hope this clarifies it for you.
