### ISSUE TITLE
Duplicate Update Allowed for Scoped Unique Field

### ISSUE THREAD

**Issue by AXSJ** [sensedeep/dynamodb-onetable#528]
**Describe the bug**

When updating a field in the schema marked as unique and scoped to a specific context (e.g., an accountID), the following issues occur:

1. The update is permitted even if another record within the same scope already has the same unique field value. This violates the expected unique constraint scoped to the specific context.
2. The unique record of the item being updated is not updated
3. An additional record is inadvertently created in the database. This record appears to have no functional purpose and should not exist.

**To Reproduce**

1. Mark a field in the schema as unique and scope it to a specific context, for example `accountID`.
2. Create a record with a value for this unique field.
4. Create another record with a different value for this unique field, but within the same scope (e.g accountID).
5. Attempt to update the record from step 3, with the same unique field value as the record from step 2.
6. Observe that the update goes through and an extra, seemingly purposeless, record is created.

Use the following code to reproduce in three simple steps - https://gist.github.com/AXSJ/5c4ccd0345683026dcb80cfb5e5d7616

```
info OneTable "transactWrite" "_Generic" { 
    "trace": { 
        "model": "_Generic", 
        "cmd": { 
            "TransactItems": [ 
                { 
                    "Delete": { 
                        "TableName": "table", 
                        "ReturnValues": "ALL_OLD", 
                        "Key": { 
                            "pk": { 
                                "S": "_unique#Account#${accountID}#User#code#b" 
                            }, 
                            "sk": { 
                                "S": "_unique#" 
                            } 
                        } 
                    } 
                }, 
                { 
                    "Put": { 
                        "ConditionExpression": "(attribute_not_exists(#_0)) and (attribute_not_exists(#_1))", 
                        "ExpressionAttributeNames": { 
                            "#_0": "pk", 
                            "#_1": "sk" 
                        }, 
                        "TableName": "table", 
                        "Item": { 
                            "pk": { 
                                "S": "_unique#Account#${accountID}#User#code#a" 
                            }, 
                            "sk": { 
                                "S": "_unique#" 
                            }, 
                            "_type": { 
                                "S": "_Unique" 
                            } 
                        }, 
                        "ReturnValues": "NONE" 
                    } 
                }, 
                { 
                    "Update": { 
                        "ConditionExpression": "(attribute_exists(#_0)) and (attribute_exists(#_1))", 
                        "ExpressionAttributeNames": { 
                            "#_0": "pk", 
                            "#_1": "sk", 
                            "#_2": "id", 
                            "#_3": "code", 
                            "#_4": "updated" 
                        }, 
                        "ExpressionAttributeValues": { 
                            ":_0": { 
                                "S": "2" 
                            }, 
                            ":_1": { 
                                "S": "a" 
                            }, 
                            ":_2": { 
                                "S": "2024-05-20T03:23:48.242Z" 
                            } 
                        }, 
                        "TableName": "table", 
                        "ReturnValues": "ALL_NEW", 
                        "UpdateExpression": "set #_2 = :_0, #_3 = :_1, #_4 = :_2", 
                        "Key": { 
                            "pk": { 
                                "S": "User#2" 
                            }, 
                            "sk": { 
                                "S": "User#" 
                            } 
                        } 
                    } 
                } 
            ], 
            "timestamp": "2024-05-20T03:23:48.242Z" 
        }, 
        "op": "transactWrite", 
        "properties": {} 
    } 
}' 
```

**What the database looks like**

<img width="1029" alt="image" src="https://github.com/sensedeep/dynamodb-onetable/assets/80088012/f2bcfd5e-9dde-496e-89f0-7c0f7a92889d">

**Expected behavior**
1. The update should be rejected if the unique field value already exists within the same context.
2. No additional records should be created as a result of the update attempt.

**Environment (please complete the following information):**
 - Mac OS
 - Node v20.12.2
 - OneTable Version ^2.7.2

**Comment by sweepy84** [comment]
We are facing this issue. Seems like a major flaw in unique checker which is critical to us.

Please help

**Comment by mobsense** [comment]
Hi, 

The issue here is that your update needs to provide all the properties referenced by the scope template.

i.e. you are missing the accountID on the update. Notice in the put expression the ${accountID} was not resolved:

```
                        "Item": { 
                            "pk": { 
                                "S": "_unique#Account#${accountID}#User#code#a" 
```

We are looking into making this throw and exception in the future.

Apologies for the delay in responding to this issue.

**Comment by AXSJ** [comment]
Hi @mobsense, thank you for your help. I believe this has resolved the issue. I will proceed to update our functions to include the fields specified within the scope in the update payload as well
