### ISSUE TITLE
Batch Request: To await or not await

### ISSUE THREAD

**Issue by lohrm-stabl** [sensedeep/dynamodb-onetable#529]
**Describe the bug**

[In the documentation](https://doc.onetable.io/api/table/methods/#batchget) `await` is used for building up the batch. In the [samples included in this repository](https://github.com/sensedeep/dynamodb-onetable/blob/main/samples/typescript/src/index.ts#L136) not. Which one is correct?
Is one more performant/recommended than the other?

**To Reproduce**

```typescript
const batch = {};

ORGS.get({id: "stabl"}, { batch });
DEVICES.get({ id: "01HZEJQX97WA8JPYCTKWVDY7YP"}, { batch });

const results = await TABLE.batchGet(batch);
```

Seems to behave the exact same way as:

```typescript
const batch = {};

await ORGS.get({id: "stabl"}, { batch });
await DEVICES.get({ id: "01HZEJQX97WA8JPYCTKWVDY7YP"}, { batch });

const results = await TABLE.batchGet(batch);
```

**Expected behavior**

The documentation should state what is correct/recommended. The samples should adhere to that.

**Environment (please complete the following information):**
 - Windows, WSL, Arch, Ubuntu
 - dynamodob-onetable 2.7.1

**Additional context**

**Comment by mobsense** [comment]
Correct use is to await. 

You may be able to get away with not using await on some paths, but it has not been tested to be always true.

Until thoroughly tested, I'd recommend using await.
