### ISSUE TITLE
Crypto initialization code is duplicated

### ISSUE THREAD

**Issue by bozzaj** [sensedeep/dynamodb-onetable#541]
**ISSUES will not receive priority that do not complete this template. They will be flagged as "Insufficient Information" and may be closed without any action.**

**Describe the bug**

Initialization of crypto object in `Table` class is duplicated.

**To Reproduce**

Look here: https://github.com/sensedeep/dynamodb-onetable/blob/6c323aaf2844e623d02a3c8adb071b7f04be871b/src/Table.js#L93-L99

This line (93) makes a call to `this.initCrypto()`, which is located here:
https://github.com/sensedeep/dynamodb-onetable/blob/6c323aaf2844e623d02a3c8adb071b7f04be871b/src/Table.js#L1016-L1023

Lines 94-99 that follow the call to `this.initCrypto()` are essentially a duplication of the `initCrypto` method - Compare Lines 94-99 and Lines 1017-1022.

**Expected behavior**
`Table` constructor shouldn't be duplicating work that was already completed.

**Additional context**
As this should be a simple removal of a few lines of code, I didn't think a PR would be necessary. However, if that's preferable, let me know.

**Comment by dev-embedthis** [comment]
Thanks -- we'll remove the lines 94-99

Appreciated, thank you.
