### ISSUE TITLE
[FEAT]: table.fetch method - supported?

### ISSUE THREAD

**Issue by liammullan** [sensedeep/dynamodb-onetable#70]
Hi, firstly great job with the onetable api.

I've been struggling a bit to figure out how to get multiple items (with differing types) given a single partition key. It's possible I've missed something along the way (and apols if so) but here's what I found...

The only example of such an operation in the sample code is in the typescript sample. (I am using typescript).

However it uses **table.fetch** which is _not mentioned in the documentation_ here:

https://github.com/sensedeep/dynamodb-onetable

I tried it, like so:

_items = await table.fetch(["User", "UserProfile"], {pk: `User:${id}`})_

The .d.ts file (and thus my IDE) says this returns _Promise<AnyEntity[]>_ however I found it returns an object with keys of (Model type string) and values of (array of the associated Model type):

    {
      User: [ { id: '0b4c8d6a-1c52-4784-b5da-ad1bac65a3ec', _type: 'User' } ],
      UserProfile: [
        {
          id: '0b4c8d6a-1c52-4784-b5da-ad1bac65a3ec',
          email: 'Colten99@hotmail.com',
          firstName: 'Colten',
          lastName: 'Monahan',
          displayName: 'Colten Monahan',
          _type: 'UserProfile'
        }
      ]
    }

(Not real data, don't worry ;-)

So... I did some fiddling around with casting and was able to get hold of the results ok.

So perhaps actions here might be to 1) document the fetch method 2) fix the types def for it?

**Comment by mobsense** [comment]
Good spelunking!

We're prototyping the `fetch` method and exploring different options.

The alternative is: to use queryItems and groupByType as described in the README. We are exploring a cleaner way to read item collections using fetch.

Can you share your final .d.ts type definition?

**Comment by liammullan** [comment]
Thanks for introducing me to a new word! 

I didn't do anything with the .d.ts file, I just did a horrid cast to any:

        items = await table.fetch(["User", "UserProfile"], {pk: `User:${id}`}) as any // error in types file

        const users: UserType[] = items.User
        const profiles: UserProfileType[] = items.UserProfile

**Comment by mobsense** [comment]
We're still not quite ready to cement the API for `fetch`.  All ideas are welcome.

I'll get the .d.ts type fixed so you can experiment without the cast.

**Comment by liammullan** [comment]
Perfect, many thanks.

Re the groupByType you mentioned, the README has this:

items = db.groupByType(items)

... but doesn't mention what "db" is? (Perhaps I'm being a bit dense here!)

**Comment by mobsense** [comment]
We use `db` sometimes for `table`.  It is a Table instance.

I'll fix the doc for that.

**Comment by mobsense** [comment]
Just pushed to the REPO:

Added a type for fetch() and groupByType to Table.d.ts.

```
export type EntityGroup = {
    [key: string]: AnyEntity
};

fetch(models: string[], properties: OneProperties, params?: OneParams): Promise<EntityGroup>;
groupByType(items: AnyEntity[]): EntityGroup;
```

And added a test/typescript-tennant.ts which does some basic exercise of the fetch API.

Though still not documented (fetch), here is the usage:

```
let collection = await table.fetch(['Account', 'User'], {pk: `account#${account.id}`})
```

You give a list of model types and the PK.  Fetch has an implicit params.parse == true.
Returns similar to groupByType.

**Comment by liammullan** [comment]
Good stuff, thanks Michael, I'll have a look at this as soon as I can and ping you back if any issues

**Comment by mobsense** [comment]
Fixed in 1.5.5.

Please give some feedback about the API. I'd like to settle on this and document it.

**Comment by mobsense** [comment]
I'll keep this issue open until fetch is released fully.

**Comment by liammullan** [comment]
Apologies Michael, I've been pulled onto something else briefly, I'll ping you back about this asap

**Comment by liammullan** [comment]
Hey, so with the change to _table.fetch_... if you key into the EntityGroup the .d.ts says we get a single AnyEntity value, but in reality we get AnyEntity[] don't we?

As far as the fetch api itself goes it is useful, for sure. I can't help wondering whether we could get stronger typing. E.g. rather than keying into a collection by string (type name) could we key by model - i.e.  Model<T> - with the value being a []<T>? May not be possible, I haven't delved into the code.

Cheers!

**Comment by mobsense** [comment]
Understand. You would need to iterate the models first parameter.

Alternatively we could do something like:

let collection = await fetch<User, Account>(['User', 'Account'], {pk})

Otherwise, you would need to iterate the models array and construct type types from that. Not sure if TypeScript can enumerate arrays like we do when iterating the schema to create the model types.

**Comment by mobsense** [comment]
We're going to document the current implementation for now.
