### ISSUE TITLE
[FEAT]: support Select: 'COUNT' Query Parameter

### ISSUE THREAD

**Issue by bytekast** [sensedeep/dynamodb-onetable#72]
**Describe the bug**

DynamoDB supports specifying 'COUNT' as the `Select` query parameter to return only the number of matches, not the items themselves.

- https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#API_Query_RequestSyntax

It would be great if this were supported as well. Thanks.

**Comment by mobsense** [comment]
Thanks, I'll add that to our list.

As you can see, we try to keep our issue list very low, so this should get attention soon.

I'll update here over the next week.

**Comment by mobsense** [comment]
We're prototyping this. 

It doesn't work well having find/scan and variants return a count or items. In typescript, this can be achieved, but then declarations for return values will be number | Entity[]. This causes problems then when those items are used in other APIs that don't allow numbers.

So it looks like we need to add findCount, scanCount, queryItemsCount etc, that return the count.

Not as clean as I'd like, but better than complicating the return type for TypeScript I think.

Thoughts?

**Comment by bytekast** [comment]
Could you add it to the `Paged` class? In DocumentClient, `Count` is in the same object as `LastEvaluatedKey`

**Comment by mobsense** [comment]
That sounds like a good direction. I'll play with that. Thank you.

**Comment by mobsense** [comment]
That worked out really REALLY cleanly. Thank you. I was going down the wrong path before that.
