### ISSUE TITLE
gs1:     { hash: 'gs1pk', sort: 'gs1sk', project: ['gs1pk', 'gs1sk', 'data'] },

### ISSUE THREAD

**Issue by jonathanalberghini** [sensedeep/dynamodb-onetable#74]
I do not understand what the 'data' means?

**Comment by mobsense** [comment]
Those are attributes to project to the Index.  That means that any model that has a data attribute will be projected to the index.

**Comment by mobsense** [comment]
I'll move this to the Discussions
