### ISSUE TITLE
[FEAT] Export types for schema

### ISSUE THREAD

**Issue by omer-to** [sensedeep/dynamodb-onetable#77]
It would be useful to access `OneSchema`, `OneType`, `OneModelSchema`, `OneIndexSchema`,  and `OneFieldSchema` types.

**Comment by mobsense** [comment]
Sounds reasonable.  

Can you help me understand what you are using them for?  Helps guide our thinking.

Can you also test if that works for you by:

1. exporting from model.d.ts
2. importing and re-exporting in index.d.ts

**Comment by mobsense** [comment]
We've added these to the next release
