### ISSUE TITLE
[BUG]: remove in a batch

### ISSUE THREAD

**Issue by demsey2** [sensedeep/dynamodb-onetable#78]
is it possible to run multiple Model.remove in a batch? I am using version 1.5.4

I have a list of ids I want to remove with the following code
```
const batch = this.prepareBatch<CorrespondenceLogByEventType>();

for (const logId of logIds) {
  await this.logByEventType.remove(
    { type: CorrespondenceEventType.UNREAD, logId },
    { batch, many: true, log: this.logEnabled }
  );
}

await this.processBatchWrite<CorrespondenceLogByEventType>(batch);
```

when I execute that code it throws 
```
// Expression.js
throw new Error('Invalid filters with batch operation');
```

**Comment by mobsense** [comment]
You can only do simple put / delete operation in a batch on the primary key.

The OneTable remove ... many: true does a query under the hood to identify the items to remove. So that cannot be done in a batch.

You can do the query yourself, then put each simple remove into the batch. Of course, there is a limit of 25 ops per batch.

It would be great if DDB could provide a higher performance way to delete items. ;-)

**Comment by demsey2** [comment]
> The OneTable remove ... many: true does a query under the hood to identify the items to remove. So that cannot be done in a batch.

1. what is the reason you query first and then delete? 

> You can do the query yourself, then put each simple remove into the batch. Of course, there is a limit of 25 ops per batch.

2. do you mean build a batch with commands based on Expression and then call Table.batchWrite ?

**Comment by mobsense** [comment]
You don't need to. You can just delete using the primary key.

But say you want to delete many items based on a query? i.e. a filter expression.  OneTable supports doing a remove() with a filter expression via params.where. This does a query first, then removes the matching items. The `many:true` is a safety to make  sure you really want to do this.

Regarding (2). Not necessarily. 

Basically, if you know the primary key, just do a remove with batch. Job done. 

If you don't know the primary key, then you need to do a query first to determine those keys. Then you can batch delete.

**Comment by demsey2** [comment]
> Basically, if you know the primary key, just do a remove with batch. Job done.

this is what I am trying to do with the code above, I call logByEventType.remove()
my keys for that model are:
```
pk: { type: String, value: '${slug}#log-event-type#${type}' },
sk: { type: String, value: 'log#${logId}#${id}' },
```
but I need to delete specific records based on pk and sk

**Comment by mobsense** [comment]
So you do:

    await this.logByEventType.remove({slug, logId, id}, {batch})

then run the batch.  The type is supplied by OneTable.

i.e. you provide all the components of the PK/SK.

**Comment by demsey2** [comment]
ok I just realized my problem, my sort key has an additional {id}  component and I was expecting to delete where sk: begins_with but that is only supported for query 

thanks for your help
