### ISSUE TITLE
[FEAT]: Defining structure (properties) of a model attribute of type Object

### ISSUE THREAD

**Issue by fifi98** [sensedeep/dynamodb-onetable#79]
First of all, thank you for the amazing library, it helped me a lot with enforcing the single table design pattern in DynamoDB! :)

I was wondering if you had any thoughts on adding support for defining a structure of a model attribute that has a type of an Object. Specifically, I have a property in my model defined as follows:

`location: { type: Object, required: true }`

What (in my case) would be very helpful feature is to be able to define the properties of that location object and then have those properties added to the TypeScript type by the library. For example I would want to add those properties to my location object:

```
zip: { type: String, required: true }
state: { type: String, required: true },
city: { type: String, required: true },
```

Would this be something that's useful and possible to implement?

**Comment by mobsense** [comment]
Thanks for the feedback. All suggestions to improve are really welcome.

Your suggestion is definitely useful. We're taking increased TypeScript support for things like this step by step and are keen to continue to strength this support. However TS only has so much support and we've not yet stumbled on the solution. If you know of a real TS typing wizard, let us know.

Ideally, we'd like TS types for all nested properties regardless of depth. Still working on how to do that and not sure if that is possible yet.

**Comment by mobsense** [comment]
This issue is really closely related to #76. I'm going to close this issue and deal with it via #76.
