### ISSUE TITLE
[Feat]: Make operations non-blocking

### ISSUE THREAD

**Issue by matthelliwell2** [sensedeep/dynamodb-onetable#85]
**Describe the bug**
I want to use the library to a lot of parallel IO. But because the calls all to an await it only performs one operation at at time and runs too slowly.

**To Reproduce**

Suppose I want to create lots of objects, I want to be able to write code like this so the creation runs in parallel. 

```
export async function create(bordereaux: BordereauxEntityType[]): Promise<BordereauxEntityType[]> {
    const promises = bordereaux.map(async b => Bordereaux.create(b))
    return Promise.all(promises)
}

```

However with the awaits inside the create call this is going to end up blocking. Obviously in this case I could use a batch write but once my logic becomes more complicated I need operations to by asynchronous and running in parallel.

For example I might read a file of 500 lines. For each line I need to read two objects from the database, combine them and write a new object. I want all the IO to be running in parallel as much as possible to minimise the runtime.

**Expected behaviour**
None of the operations in the library await on a promise, instead they chain promises.

For example the create function is currently implemented as:

```
    async create(properties, params = {}) {
        ({ params, properties } = this.checkArgs(properties, params, { parse: true, high: true, exists: false }));
        let result;
        if (this.hasUniqueFields) {
            result = await this.createUnique(properties, params);
        }
        else {
            result = await this.putItem(properties, params);
        }
        return result;
    }
```

but could be written as 

```
    async create(properties, params = {}) {
        ({ params, properties } = this.checkArgs(properties, params, { parse: true, high: true, exists: false }));
        let result;
        if (this.hasUniqueFields) {
            return this.createUnique(properties, params);
        }
        else {
            return this.putItem(properties, params);
        }
    }
```

This also avoids creating an intermediate promise when you do ```return result```

I could have a go at submitting a pull request for this if it helps.

**Environment (please complete the following information):**
 - OS - Windows
 - Node Version - 14
 - typescript - 4.3.5

**Comment by mobsense** [comment]
Thanks for creating this issue.

When create does an internal await, the outer function still returns immediately. It doesn't block.

if you do:

```
promises = []
promises.push(create(....))
await Promise.all(promises)
```

That still runs all the creates in parallel. You can nest awaits and the outer function still returns a promise.

**Comment by mobsense** [comment]
@matthelliwell2  Can you comment on my question?  

The reason we do the await internally is so the result value is actually correct internally instead of being resolved externally to create. You should still be able to parallel your requests by using the promises [] and Promise.all for your create calls.

Or do I have this wrong?

**Comment by mobsense** [comment]
I'll close this now, but please let me know if we need to reopen.
