### ISSUE TITLE
cjs and mjs modules

### ISSUE THREAD

**Issue by hffmnn** [sensedeep/dynamodb-onetable#86]
Hi,

I read up on your module strategy [here](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html). 
To find out which module gets used when, I created [this repo](https://github.com/hffmnn/module_test), where I modified the `dynamodb-onetable` package to log something based on the current module (`Hello from cjs` vs. `Hello from mjs`). After that, I tried different build options:

When bundling with esbuild, it outputs `Hello from mjs`, when building with `tsc` (default config `tsc --init`) or running with node directly it outputs `Hello from cjs`.

My question: Shouldn't it output `Hello from mjs` when building with `tsc`. 

Please have a look at this PR, to see what I did in detail: https://github.com/hffmnn/module_test/pull/1

**Comment by mobsense** [comment]
Totally depends on your tsconfig settings.  What were they?

**Comment by hffmnn** [comment]
More or less the defaults from a `tsc --init`. I only updated the `outDir` I think.

```
{
  "compilerOptions": {
    "target": "es5" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "outDir": "./dist" /* Redirect output structure to the directory. */,
    "strict": true /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**Comment by mobsense** [comment]
You are using module == 'commonjs' so you will load from cjs. If you set module == 'esnext' you should get mjs.

**Comment by hffmnn** [comment]
Setting `"module": "esnext"` gives

```
src/main.ts:1:23 - error TS2792: Cannot find module 'dynamodb-onetable'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

1 import { Table } from "dynamodb-onetable";
                        ~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

Setting `"moduleResolution": "node",` gives

```
(node:87878) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/christian/Desktop/_ThrowAway/module_example/dist/main.js:1
import { Table } from "dynamodb-onetable";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
make: *** [run_tsc] Error 1
```

Setting `"type": "module"` in `package.json` gives

```
hello from mjs
```

but seems to break esbuild.

I guess I can work around that, so thanks for the quick reply.

**Comment by mobsense** [comment]
I think you are right. "type": "module" says the current application uses ES modules. tsconfig "module": "commonjs" says transpile the current app to use commonjs modules.

**Comment by mobsense** [comment]
Is this issue closed for you?  or still unresolved?

**Comment by hffmnn** [comment]
Yes, all good. Thank you very much!
