### ISSUE TITLE
[BUG]: unable to update and delete in a batch

### ISSUE THREAD

**Issue by demsey2** [sensedeep/dynamodb-onetable#94]
When I run a batch with remove and update items I got "Cannot convert undefined or null to object"

in Expression.js we have

```
if (params.batch) {
    if (op == 'get') {
        args = { Keys: key }
    } else if (op == 'delete') {
        args = { Key: key }
    } else if (op == 'put') {
        args = { Item: values }
    }
    if (filters.length) {
        throw new Error('Invalid filters with batch operation')
    }
}
```
when I try to debug I got params.batch = true and op = 'update' so we get no args and then the following code fails
```
args = Object.fromEntries(Object.entries(args).filter(([_, v]) => v != null))
```

I modified one test from test/batch.ts to the following
```
test('Batch update and delete combined', async() => {
    let batch = {}
    table.remove('User', {id: users[0].id}, {batch})
    table.remove('User', {id: users[1].id}, {batch})
    // table.remove('User', {id: users[2].id}, {batch})
    table.update('User', { id: users[2].id, name: 'test'}, {batch})

    let items: any = await table.batchWrite(batch, {parse: true, hidden: false})

    users = await table.scan('User')
    expect(users.length).toBe(1)
    expect(users[0]).toMatchObject(data[0])
})
```
 that test fails, not sure what is going on, when I try to handle op = 'update' I got " ValidationException: One of the required keys was not given a value"

**Comment by mobsense** [comment]
The release 0.7.1 just posted had a if(args) to protect that line.

There may still be an issue, but can you please retest with 0.7.1?

**Comment by demsey2** [comment]
not it throws that exception Unsupport batch operation "update"
```
throw new Error(`Unsupport batch operation "${op}"`);
```

**Comment by mobsense** [comment]
It should throw an exception.  DynamoDB does not support update in batch operations.

**Comment by demsey2** [comment]
sorry, that make sense, I was looking at transactions 
thanks

**Comment by mobsense** [comment]
No worries. All issues and feedback is welcome.
